/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: CommandHandlersListPayload.proto */

#ifndef PROTOBUF_C_CommandHandlersListPayload_2eproto__INCLUDED
#define PROTOBUF_C_CommandHandlersListPayload_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "EndpointListPayload.pb-c.h"
#include "sm_transaction_status_public.pb-c.h"
#include "soa_service_manager_info.pb-c.h"

typedef struct _Fnv__Soa__Framework__Protobuf__CommandHandlersListPayloadProto Fnv__Soa__Framework__Protobuf__CommandHandlersListPayloadProto;
typedef struct _Fnv__Soa__Framework__Protobuf__CommandHandlersListPayloadProto__HandlersEntry Fnv__Soa__Framework__Protobuf__CommandHandlersListPayloadProto__HandlersEntry;


/* --- enums --- */


/* --- messages --- */

struct  _Fnv__Soa__Framework__Protobuf__CommandHandlersListPayloadProto__HandlersEntry
{
  ProtobufCMessage base;
  char *key;
  Fnv__Soa__Framework__Protobuf__EndpointListPayload *value;
};
#define FNV__SOA__FRAMEWORK__PROTOBUF__COMMAND_HANDLERS_LIST_PAYLOAD_PROTO__HANDLERS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fnv__soa__framework__protobuf__command_handlers_list_payload_proto__handlers_entry__descriptor) \
    , NULL, NULL }


/*
 **
 * @fnv_message_proto
 * @fnv_topic SERVICES/REQUEST/FNV/SOA/SERVICEMANAGER
 * @fnv_command GET_CMND_HANDLERS
 * @fnv_description:
 * @fnv_request: CommandListPayloadProto
 */
struct  _Fnv__Soa__Framework__Protobuf__CommandHandlersListPayloadProto
{
  ProtobufCMessage base;
  protobuf_c_boolean has_transactionstatus;
  Fnv__Soa__Framework__Protobuf__SmTransactionStatus__Status transactionstatus;
  /*
   * command handlers map.
   */
  size_t n_handlers;
  Fnv__Soa__Framework__Protobuf__CommandHandlersListPayloadProto__HandlersEntry **handlers;
  /*
   * API version, static field
   */
  Fnv__Soa__Framework__Protobuf__ApiVersion *__api_version;
};
#define FNV__SOA__FRAMEWORK__PROTOBUF__COMMAND_HANDLERS_LIST_PAYLOAD_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fnv__soa__framework__protobuf__command_handlers_list_payload_proto__descriptor) \
    , 0, FNV__SOA__FRAMEWORK__PROTOBUF__SM_TRANSACTION_STATUS__STATUS__OK, 0,NULL, NULL }


/* Fnv__Soa__Framework__Protobuf__CommandHandlersListPayloadProto__HandlersEntry methods */
void   fnv__soa__framework__protobuf__command_handlers_list_payload_proto__handlers_entry__init
                     (Fnv__Soa__Framework__Protobuf__CommandHandlersListPayloadProto__HandlersEntry         *message);
/* Fnv__Soa__Framework__Protobuf__CommandHandlersListPayloadProto methods */
void   fnv__soa__framework__protobuf__command_handlers_list_payload_proto__init
                     (Fnv__Soa__Framework__Protobuf__CommandHandlersListPayloadProto         *message);
size_t fnv__soa__framework__protobuf__command_handlers_list_payload_proto__get_packed_size
                     (const Fnv__Soa__Framework__Protobuf__CommandHandlersListPayloadProto   *message);
size_t fnv__soa__framework__protobuf__command_handlers_list_payload_proto__pack
                     (const Fnv__Soa__Framework__Protobuf__CommandHandlersListPayloadProto   *message,
                      uint8_t             *out);
size_t fnv__soa__framework__protobuf__command_handlers_list_payload_proto__pack_to_buffer
                     (const Fnv__Soa__Framework__Protobuf__CommandHandlersListPayloadProto   *message,
                      ProtobufCBuffer     *buffer);
Fnv__Soa__Framework__Protobuf__CommandHandlersListPayloadProto *
       fnv__soa__framework__protobuf__command_handlers_list_payload_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fnv__soa__framework__protobuf__command_handlers_list_payload_proto__free_unpacked
                     (Fnv__Soa__Framework__Protobuf__CommandHandlersListPayloadProto *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Fnv__Soa__Framework__Protobuf__CommandHandlersListPayloadProto__HandlersEntry_Closure)
                 (const Fnv__Soa__Framework__Protobuf__CommandHandlersListPayloadProto__HandlersEntry *message,
                  void *closure_data);
typedef void (*Fnv__Soa__Framework__Protobuf__CommandHandlersListPayloadProto_Closure)
                 (const Fnv__Soa__Framework__Protobuf__CommandHandlersListPayloadProto *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor fnv__soa__framework__protobuf__command_handlers_list_payload_proto__descriptor;
extern const ProtobufCMessageDescriptor fnv__soa__framework__protobuf__command_handlers_list_payload_proto__handlers_entry__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_CommandHandlersListPayload_2eproto__INCLUDED */
