/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: EndpointListPayload.proto */

#ifndef PROTOBUF_C_EndpointListPayload_2eproto__INCLUDED
#define PROTOBUF_C_EndpointListPayload_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "Endpoint.pb-c.h"

typedef struct _Fnv__Soa__Framework__Protobuf__EndpointListPayload Fnv__Soa__Framework__Protobuf__EndpointListPayload;


/* --- enums --- */


/* --- messages --- */

/*
 **
 * @fnv_message_proto
 * @fnv_deprecated
 */
struct  _Fnv__Soa__Framework__Protobuf__EndpointListPayload
{
  ProtobufCMessage base;
  /*
   * List of endpoints
   */
  size_t n_endpoints;
  Fnv__Soa__Framework__Protobuf__Endpoint **endpoints;
};
#define FNV__SOA__FRAMEWORK__PROTOBUF__ENDPOINT_LIST_PAYLOAD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fnv__soa__framework__protobuf__endpoint_list_payload__descriptor) \
    , 0,NULL }


/* Fnv__Soa__Framework__Protobuf__EndpointListPayload methods */
void   fnv__soa__framework__protobuf__endpoint_list_payload__init
                     (Fnv__Soa__Framework__Protobuf__EndpointListPayload         *message);
size_t fnv__soa__framework__protobuf__endpoint_list_payload__get_packed_size
                     (const Fnv__Soa__Framework__Protobuf__EndpointListPayload   *message);
size_t fnv__soa__framework__protobuf__endpoint_list_payload__pack
                     (const Fnv__Soa__Framework__Protobuf__EndpointListPayload   *message,
                      uint8_t             *out);
size_t fnv__soa__framework__protobuf__endpoint_list_payload__pack_to_buffer
                     (const Fnv__Soa__Framework__Protobuf__EndpointListPayload   *message,
                      ProtobufCBuffer     *buffer);
Fnv__Soa__Framework__Protobuf__EndpointListPayload *
       fnv__soa__framework__protobuf__endpoint_list_payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fnv__soa__framework__protobuf__endpoint_list_payload__free_unpacked
                     (Fnv__Soa__Framework__Protobuf__EndpointListPayload *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Fnv__Soa__Framework__Protobuf__EndpointListPayload_Closure)
                 (const Fnv__Soa__Framework__Protobuf__EndpointListPayload *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor fnv__soa__framework__protobuf__endpoint_list_payload__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_EndpointListPayload_2eproto__INCLUDED */
