/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Endpoint.proto */

#ifndef PROTOBUF_C_Endpoint_2eproto__INCLUDED
#define PROTOBUF_C_Endpoint_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Fnv__Soa__Framework__Protobuf__Endpoint Fnv__Soa__Framework__Protobuf__Endpoint;


/* --- enums --- */


/* --- messages --- */

/*
 * SOA client endpoint.
 * Generic type to be used in most of interfaces.
 */
struct  _Fnv__Soa__Framework__Protobuf__Endpoint
{
  ProtobufCMessage base;
  char *endpoint;
};
#define FNV__SOA__FRAMEWORK__PROTOBUF__ENDPOINT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fnv__soa__framework__protobuf__endpoint__descriptor) \
    , NULL }


/* Fnv__Soa__Framework__Protobuf__Endpoint methods */
void   fnv__soa__framework__protobuf__endpoint__init
                     (Fnv__Soa__Framework__Protobuf__Endpoint         *message);
size_t fnv__soa__framework__protobuf__endpoint__get_packed_size
                     (const Fnv__Soa__Framework__Protobuf__Endpoint   *message);
size_t fnv__soa__framework__protobuf__endpoint__pack
                     (const Fnv__Soa__Framework__Protobuf__Endpoint   *message,
                      uint8_t             *out);
size_t fnv__soa__framework__protobuf__endpoint__pack_to_buffer
                     (const Fnv__Soa__Framework__Protobuf__Endpoint   *message,
                      ProtobufCBuffer     *buffer);
Fnv__Soa__Framework__Protobuf__Endpoint *
       fnv__soa__framework__protobuf__endpoint__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fnv__soa__framework__protobuf__endpoint__free_unpacked
                     (Fnv__Soa__Framework__Protobuf__Endpoint *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Fnv__Soa__Framework__Protobuf__Endpoint_Closure)
                 (const Fnv__Soa__Framework__Protobuf__Endpoint *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor fnv__soa__framework__protobuf__endpoint__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_Endpoint_2eproto__INCLUDED */
