// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetProvisionedServicesResponsePayload.proto

#ifndef PROTOBUF_GetProvisionedServicesResponsePayload_2eproto__INCLUDED
#define PROTOBUF_GetProvisionedServicesResponsePayload_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "sm_transaction_status_public.pb.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

namespace protobuf_GetProvisionedServicesResponsePayload_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsGetProvisionedServicesResponsePayloadProtoImpl();
void InitDefaultsGetProvisionedServicesResponsePayloadProto();
inline void InitDefaults() {
  InitDefaultsGetProvisionedServicesResponsePayloadProto();
}
}  // namespace protobuf_GetProvisionedServicesResponsePayload_2eproto
namespace fnv {
namespace soa {
namespace framework {
namespace protobuf {
class GetProvisionedServicesResponsePayloadProto;
class GetProvisionedServicesResponsePayloadProtoDefaultTypeInternal;
extern GetProvisionedServicesResponsePayloadProtoDefaultTypeInternal _GetProvisionedServicesResponsePayloadProto_default_instance_;
}  // namespace protobuf
}  // namespace framework
}  // namespace soa
}  // namespace fnv
namespace fnv {
namespace soa {
namespace framework {
namespace protobuf {

// ===================================================================

class GetProvisionedServicesResponsePayloadProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fnv.soa.framework.protobuf.GetProvisionedServicesResponsePayloadProto) */ {
 public:
  GetProvisionedServicesResponsePayloadProto();
  virtual ~GetProvisionedServicesResponsePayloadProto();

  GetProvisionedServicesResponsePayloadProto(const GetProvisionedServicesResponsePayloadProto& from);

  inline GetProvisionedServicesResponsePayloadProto& operator=(const GetProvisionedServicesResponsePayloadProto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetProvisionedServicesResponsePayloadProto(GetProvisionedServicesResponsePayloadProto&& from) noexcept
    : GetProvisionedServicesResponsePayloadProto() {
    *this = ::std::move(from);
  }

  inline GetProvisionedServicesResponsePayloadProto& operator=(GetProvisionedServicesResponsePayloadProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetProvisionedServicesResponsePayloadProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetProvisionedServicesResponsePayloadProto* internal_default_instance() {
    return reinterpret_cast<const GetProvisionedServicesResponsePayloadProto*>(
               &_GetProvisionedServicesResponsePayloadProto_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(GetProvisionedServicesResponsePayloadProto* other);
  friend void swap(GetProvisionedServicesResponsePayloadProto& a, GetProvisionedServicesResponsePayloadProto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetProvisionedServicesResponsePayloadProto* New() const PROTOBUF_FINAL { return New(NULL); }

  GetProvisionedServicesResponsePayloadProto* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetProvisionedServicesResponsePayloadProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string metadata = 2;
  int metadata_size() const;
  void clear_metadata();
  static const int kMetadataFieldNumber = 2;
  const ::std::string& metadata(int index) const;
  ::std::string* mutable_metadata(int index);
  void set_metadata(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_metadata(int index, ::std::string&& value);
  #endif
  void set_metadata(int index, const char* value);
  void set_metadata(int index, const char* value, size_t size);
  ::std::string* add_metadata();
  void add_metadata(const ::std::string& value);
  #if LANG_CXX11
  void add_metadata(::std::string&& value);
  #endif
  void add_metadata(const char* value);
  void add_metadata(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& metadata() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_metadata();

  // optional .fnv.soa.framework.protobuf.SmTransactionStatus.Status transactionStatus = 1 [default = OK];
  bool has_transactionstatus() const;
  void clear_transactionstatus();
  static const int kTransactionStatusFieldNumber = 1;
  ::fnv::soa::framework::protobuf::SmTransactionStatus_Status transactionstatus() const;
  void set_transactionstatus(::fnv::soa::framework::protobuf::SmTransactionStatus_Status value);

  // @@protoc_insertion_point(class_scope:fnv.soa.framework.protobuf.GetProvisionedServicesResponsePayloadProto)
 private:
  void set_has_transactionstatus();
  void clear_has_transactionstatus();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> metadata_;
  int transactionstatus_;
  friend struct ::protobuf_GetProvisionedServicesResponsePayload_2eproto::TableStruct;
  friend void ::protobuf_GetProvisionedServicesResponsePayload_2eproto::InitDefaultsGetProvisionedServicesResponsePayloadProtoImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GetProvisionedServicesResponsePayloadProto

// optional .fnv.soa.framework.protobuf.SmTransactionStatus.Status transactionStatus = 1 [default = OK];
inline bool GetProvisionedServicesResponsePayloadProto::has_transactionstatus() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetProvisionedServicesResponsePayloadProto::set_has_transactionstatus() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetProvisionedServicesResponsePayloadProto::clear_has_transactionstatus() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetProvisionedServicesResponsePayloadProto::clear_transactionstatus() {
  transactionstatus_ = 1;
  clear_has_transactionstatus();
}
inline ::fnv::soa::framework::protobuf::SmTransactionStatus_Status GetProvisionedServicesResponsePayloadProto::transactionstatus() const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.protobuf.GetProvisionedServicesResponsePayloadProto.transactionStatus)
  return static_cast< ::fnv::soa::framework::protobuf::SmTransactionStatus_Status >(transactionstatus_);
}
inline void GetProvisionedServicesResponsePayloadProto::set_transactionstatus(::fnv::soa::framework::protobuf::SmTransactionStatus_Status value) {
  assert(::fnv::soa::framework::protobuf::SmTransactionStatus_Status_IsValid(value));
  set_has_transactionstatus();
  transactionstatus_ = value;
  // @@protoc_insertion_point(field_set:fnv.soa.framework.protobuf.GetProvisionedServicesResponsePayloadProto.transactionStatus)
}

// repeated string metadata = 2;
inline int GetProvisionedServicesResponsePayloadProto::metadata_size() const {
  return metadata_.size();
}
inline void GetProvisionedServicesResponsePayloadProto::clear_metadata() {
  metadata_.Clear();
}
inline const ::std::string& GetProvisionedServicesResponsePayloadProto::metadata(int index) const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.protobuf.GetProvisionedServicesResponsePayloadProto.metadata)
  return metadata_.Get(index);
}
inline ::std::string* GetProvisionedServicesResponsePayloadProto::mutable_metadata(int index) {
  // @@protoc_insertion_point(field_mutable:fnv.soa.framework.protobuf.GetProvisionedServicesResponsePayloadProto.metadata)
  return metadata_.Mutable(index);
}
inline void GetProvisionedServicesResponsePayloadProto::set_metadata(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:fnv.soa.framework.protobuf.GetProvisionedServicesResponsePayloadProto.metadata)
  metadata_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void GetProvisionedServicesResponsePayloadProto::set_metadata(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:fnv.soa.framework.protobuf.GetProvisionedServicesResponsePayloadProto.metadata)
  metadata_.Mutable(index)->assign(std::move(value));
}
#endif
inline void GetProvisionedServicesResponsePayloadProto::set_metadata(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  metadata_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:fnv.soa.framework.protobuf.GetProvisionedServicesResponsePayloadProto.metadata)
}
inline void GetProvisionedServicesResponsePayloadProto::set_metadata(int index, const char* value, size_t size) {
  metadata_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:fnv.soa.framework.protobuf.GetProvisionedServicesResponsePayloadProto.metadata)
}
inline ::std::string* GetProvisionedServicesResponsePayloadProto::add_metadata() {
  // @@protoc_insertion_point(field_add_mutable:fnv.soa.framework.protobuf.GetProvisionedServicesResponsePayloadProto.metadata)
  return metadata_.Add();
}
inline void GetProvisionedServicesResponsePayloadProto::add_metadata(const ::std::string& value) {
  metadata_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:fnv.soa.framework.protobuf.GetProvisionedServicesResponsePayloadProto.metadata)
}
#if LANG_CXX11
inline void GetProvisionedServicesResponsePayloadProto::add_metadata(::std::string&& value) {
  metadata_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:fnv.soa.framework.protobuf.GetProvisionedServicesResponsePayloadProto.metadata)
}
#endif
inline void GetProvisionedServicesResponsePayloadProto::add_metadata(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  metadata_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:fnv.soa.framework.protobuf.GetProvisionedServicesResponsePayloadProto.metadata)
}
inline void GetProvisionedServicesResponsePayloadProto::add_metadata(const char* value, size_t size) {
  metadata_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:fnv.soa.framework.protobuf.GetProvisionedServicesResponsePayloadProto.metadata)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
GetProvisionedServicesResponsePayloadProto::metadata() const {
  // @@protoc_insertion_point(field_list:fnv.soa.framework.protobuf.GetProvisionedServicesResponsePayloadProto.metadata)
  return metadata_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
GetProvisionedServicesResponsePayloadProto::mutable_metadata() {
  // @@protoc_insertion_point(field_mutable_list:fnv.soa.framework.protobuf.GetProvisionedServicesResponsePayloadProto.metadata)
  return &metadata_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace framework
}  // namespace soa
}  // namespace fnv

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_GetProvisionedServicesResponsePayload_2eproto__INCLUDED
