// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PingServiceResponsePayload.proto

#ifndef PROTOBUF_PingServiceResponsePayload_2eproto__INCLUDED
#define PROTOBUF_PingServiceResponsePayload_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "sm_transaction_status_public.pb.h"  // IWYU pragma: export
#include "ProvisionedServiceStatusMetadata.pb.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

namespace protobuf_PingServiceResponsePayload_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsPingServiceResponsePayloadImpl();
void InitDefaultsPingServiceResponsePayload();
inline void InitDefaults() {
  InitDefaultsPingServiceResponsePayload();
}
}  // namespace protobuf_PingServiceResponsePayload_2eproto
namespace fnv {
namespace soa {
namespace framework {
namespace protobuf {
class PingServiceResponsePayload;
class PingServiceResponsePayloadDefaultTypeInternal;
extern PingServiceResponsePayloadDefaultTypeInternal _PingServiceResponsePayload_default_instance_;
}  // namespace protobuf
}  // namespace framework
}  // namespace soa
}  // namespace fnv
namespace fnv {
namespace soa {
namespace framework {
namespace protobuf {

// ===================================================================

class PingServiceResponsePayload : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fnv.soa.framework.protobuf.PingServiceResponsePayload) */ {
 public:
  PingServiceResponsePayload();
  virtual ~PingServiceResponsePayload();

  PingServiceResponsePayload(const PingServiceResponsePayload& from);

  inline PingServiceResponsePayload& operator=(const PingServiceResponsePayload& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PingServiceResponsePayload(PingServiceResponsePayload&& from) noexcept
    : PingServiceResponsePayload() {
    *this = ::std::move(from);
  }

  inline PingServiceResponsePayload& operator=(PingServiceResponsePayload&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PingServiceResponsePayload& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PingServiceResponsePayload* internal_default_instance() {
    return reinterpret_cast<const PingServiceResponsePayload*>(
               &_PingServiceResponsePayload_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(PingServiceResponsePayload* other);
  friend void swap(PingServiceResponsePayload& a, PingServiceResponsePayload& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PingServiceResponsePayload* New() const PROTOBUF_FINAL { return New(NULL); }

  PingServiceResponsePayload* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PingServiceResponsePayload* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .fnv.soa.framework.protobuf.ProvisionedServiceStatusMetadata status = 2;
  bool has_status() const;
  void clear_status();
  static const int kStatusFieldNumber = 2;
  const ::fnv::soa::framework::protobuf::ProvisionedServiceStatusMetadata& status() const;
  ::fnv::soa::framework::protobuf::ProvisionedServiceStatusMetadata* release_status();
  ::fnv::soa::framework::protobuf::ProvisionedServiceStatusMetadata* mutable_status();
  void set_allocated_status(::fnv::soa::framework::protobuf::ProvisionedServiceStatusMetadata* status);

  // optional .fnv.soa.framework.protobuf.SmTransactionStatus.Status transactionStatus = 1 [default = OK];
  bool has_transactionstatus() const;
  void clear_transactionstatus();
  static const int kTransactionStatusFieldNumber = 1;
  ::fnv::soa::framework::protobuf::SmTransactionStatus_Status transactionstatus() const;
  void set_transactionstatus(::fnv::soa::framework::protobuf::SmTransactionStatus_Status value);

  // @@protoc_insertion_point(class_scope:fnv.soa.framework.protobuf.PingServiceResponsePayload)
 private:
  void set_has_transactionstatus();
  void clear_has_transactionstatus();
  void set_has_status();
  void clear_has_status();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::fnv::soa::framework::protobuf::ProvisionedServiceStatusMetadata* status_;
  int transactionstatus_;
  friend struct ::protobuf_PingServiceResponsePayload_2eproto::TableStruct;
  friend void ::protobuf_PingServiceResponsePayload_2eproto::InitDefaultsPingServiceResponsePayloadImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PingServiceResponsePayload

// optional .fnv.soa.framework.protobuf.SmTransactionStatus.Status transactionStatus = 1 [default = OK];
inline bool PingServiceResponsePayload::has_transactionstatus() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PingServiceResponsePayload::set_has_transactionstatus() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PingServiceResponsePayload::clear_has_transactionstatus() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PingServiceResponsePayload::clear_transactionstatus() {
  transactionstatus_ = 1;
  clear_has_transactionstatus();
}
inline ::fnv::soa::framework::protobuf::SmTransactionStatus_Status PingServiceResponsePayload::transactionstatus() const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.protobuf.PingServiceResponsePayload.transactionStatus)
  return static_cast< ::fnv::soa::framework::protobuf::SmTransactionStatus_Status >(transactionstatus_);
}
inline void PingServiceResponsePayload::set_transactionstatus(::fnv::soa::framework::protobuf::SmTransactionStatus_Status value) {
  assert(::fnv::soa::framework::protobuf::SmTransactionStatus_Status_IsValid(value));
  set_has_transactionstatus();
  transactionstatus_ = value;
  // @@protoc_insertion_point(field_set:fnv.soa.framework.protobuf.PingServiceResponsePayload.transactionStatus)
}

// optional .fnv.soa.framework.protobuf.ProvisionedServiceStatusMetadata status = 2;
inline bool PingServiceResponsePayload::has_status() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PingServiceResponsePayload::set_has_status() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PingServiceResponsePayload::clear_has_status() {
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::fnv::soa::framework::protobuf::ProvisionedServiceStatusMetadata& PingServiceResponsePayload::status() const {
  const ::fnv::soa::framework::protobuf::ProvisionedServiceStatusMetadata* p = status_;
  // @@protoc_insertion_point(field_get:fnv.soa.framework.protobuf.PingServiceResponsePayload.status)
  return p != NULL ? *p : *reinterpret_cast<const ::fnv::soa::framework::protobuf::ProvisionedServiceStatusMetadata*>(
      &::fnv::soa::framework::protobuf::_ProvisionedServiceStatusMetadata_default_instance_);
}
inline ::fnv::soa::framework::protobuf::ProvisionedServiceStatusMetadata* PingServiceResponsePayload::release_status() {
  // @@protoc_insertion_point(field_release:fnv.soa.framework.protobuf.PingServiceResponsePayload.status)
  clear_has_status();
  ::fnv::soa::framework::protobuf::ProvisionedServiceStatusMetadata* temp = status_;
  status_ = NULL;
  return temp;
}
inline ::fnv::soa::framework::protobuf::ProvisionedServiceStatusMetadata* PingServiceResponsePayload::mutable_status() {
  set_has_status();
  if (status_ == NULL) {
    status_ = new ::fnv::soa::framework::protobuf::ProvisionedServiceStatusMetadata;
  }
  // @@protoc_insertion_point(field_mutable:fnv.soa.framework.protobuf.PingServiceResponsePayload.status)
  return status_;
}
inline void PingServiceResponsePayload::set_allocated_status(::fnv::soa::framework::protobuf::ProvisionedServiceStatusMetadata* status) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(status_);
  }
  if (status) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      status = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, status, submessage_arena);
    }
    set_has_status();
  } else {
    clear_has_status();
  }
  status_ = status;
  // @@protoc_insertion_point(field_set_allocated:fnv.soa.framework.protobuf.PingServiceResponsePayload.status)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace framework
}  // namespace soa
}  // namespace fnv

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_PingServiceResponsePayload_2eproto__INCLUDED
