// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProvisionedServiceMetadata.proto

#ifndef PROTOBUF_ProvisionedServiceMetadata_2eproto__INCLUDED
#define PROTOBUF_ProvisionedServiceMetadata_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "ServiceContract.pb.h"  // IWYU pragma: export
#include "soa_service_status.pb.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

namespace protobuf_ProvisionedServiceMetadata_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsProvisionedServiceMetadataImpl();
void InitDefaultsProvisionedServiceMetadata();
inline void InitDefaults() {
  InitDefaultsProvisionedServiceMetadata();
}
}  // namespace protobuf_ProvisionedServiceMetadata_2eproto
namespace fnv {
namespace soa {
namespace framework {
namespace protobuf {
class ProvisionedServiceMetadata;
class ProvisionedServiceMetadataDefaultTypeInternal;
extern ProvisionedServiceMetadataDefaultTypeInternal _ProvisionedServiceMetadata_default_instance_;
}  // namespace protobuf
}  // namespace framework
}  // namespace soa
}  // namespace fnv
namespace fnv {
namespace soa {
namespace framework {
namespace protobuf {

// ===================================================================

class ProvisionedServiceMetadata : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fnv.soa.framework.protobuf.ProvisionedServiceMetadata) */ {
 public:
  ProvisionedServiceMetadata();
  virtual ~ProvisionedServiceMetadata();

  ProvisionedServiceMetadata(const ProvisionedServiceMetadata& from);

  inline ProvisionedServiceMetadata& operator=(const ProvisionedServiceMetadata& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ProvisionedServiceMetadata(ProvisionedServiceMetadata&& from) noexcept
    : ProvisionedServiceMetadata() {
    *this = ::std::move(from);
  }

  inline ProvisionedServiceMetadata& operator=(ProvisionedServiceMetadata&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProvisionedServiceMetadata& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ProvisionedServiceMetadata* internal_default_instance() {
    return reinterpret_cast<const ProvisionedServiceMetadata*>(
               &_ProvisionedServiceMetadata_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(ProvisionedServiceMetadata* other);
  friend void swap(ProvisionedServiceMetadata& a, ProvisionedServiceMetadata& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ProvisionedServiceMetadata* New() const PROTOBUF_FINAL { return New(NULL); }

  ProvisionedServiceMetadata* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ProvisionedServiceMetadata* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .fnv.soa.framework.protobuf.ServiceContract contract = 1;
  bool has_contract() const;
  void clear_contract();
  static const int kContractFieldNumber = 1;
  const ::fnv::soa::framework::protobuf::ServiceContract& contract() const;
  ::fnv::soa::framework::protobuf::ServiceContract* release_contract();
  ::fnv::soa::framework::protobuf::ServiceContract* mutable_contract();
  void set_allocated_contract(::fnv::soa::framework::protobuf::ServiceContract* contract);

  // optional .fnv.soa.framework.protobuf.ServiceStatus.Values status = 2 [default = AVAILABLE];
  bool has_status() const;
  void clear_status();
  static const int kStatusFieldNumber = 2;
  ::fnv::soa::framework::protobuf::ServiceStatus::Values status() const;
  void set_status(::fnv::soa::framework::protobuf::ServiceStatus::Values value);

  // @@protoc_insertion_point(class_scope:fnv.soa.framework.protobuf.ProvisionedServiceMetadata)
 private:
  void set_has_contract();
  void clear_has_contract();
  void set_has_status();
  void clear_has_status();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::fnv::soa::framework::protobuf::ServiceContract* contract_;
  int status_;
  friend struct ::protobuf_ProvisionedServiceMetadata_2eproto::TableStruct;
  friend void ::protobuf_ProvisionedServiceMetadata_2eproto::InitDefaultsProvisionedServiceMetadataImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ProvisionedServiceMetadata

// optional .fnv.soa.framework.protobuf.ServiceContract contract = 1;
inline bool ProvisionedServiceMetadata::has_contract() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProvisionedServiceMetadata::set_has_contract() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProvisionedServiceMetadata::clear_has_contract() {
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::fnv::soa::framework::protobuf::ServiceContract& ProvisionedServiceMetadata::contract() const {
  const ::fnv::soa::framework::protobuf::ServiceContract* p = contract_;
  // @@protoc_insertion_point(field_get:fnv.soa.framework.protobuf.ProvisionedServiceMetadata.contract)
  return p != NULL ? *p : *reinterpret_cast<const ::fnv::soa::framework::protobuf::ServiceContract*>(
      &::fnv::soa::framework::protobuf::_ServiceContract_default_instance_);
}
inline ::fnv::soa::framework::protobuf::ServiceContract* ProvisionedServiceMetadata::release_contract() {
  // @@protoc_insertion_point(field_release:fnv.soa.framework.protobuf.ProvisionedServiceMetadata.contract)
  clear_has_contract();
  ::fnv::soa::framework::protobuf::ServiceContract* temp = contract_;
  contract_ = NULL;
  return temp;
}
inline ::fnv::soa::framework::protobuf::ServiceContract* ProvisionedServiceMetadata::mutable_contract() {
  set_has_contract();
  if (contract_ == NULL) {
    contract_ = new ::fnv::soa::framework::protobuf::ServiceContract;
  }
  // @@protoc_insertion_point(field_mutable:fnv.soa.framework.protobuf.ProvisionedServiceMetadata.contract)
  return contract_;
}
inline void ProvisionedServiceMetadata::set_allocated_contract(::fnv::soa::framework::protobuf::ServiceContract* contract) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(contract_);
  }
  if (contract) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      contract = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, contract, submessage_arena);
    }
    set_has_contract();
  } else {
    clear_has_contract();
  }
  contract_ = contract;
  // @@protoc_insertion_point(field_set_allocated:fnv.soa.framework.protobuf.ProvisionedServiceMetadata.contract)
}

// optional .fnv.soa.framework.protobuf.ServiceStatus.Values status = 2 [default = AVAILABLE];
inline bool ProvisionedServiceMetadata::has_status() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProvisionedServiceMetadata::set_has_status() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProvisionedServiceMetadata::clear_has_status() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProvisionedServiceMetadata::clear_status() {
  status_ = 2;
  clear_has_status();
}
inline ::fnv::soa::framework::protobuf::ServiceStatus::Values ProvisionedServiceMetadata::status() const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.protobuf.ProvisionedServiceMetadata.status)
  return static_cast< ::fnv::soa::framework::protobuf::ServiceStatus::Values >(status_);
}
inline void ProvisionedServiceMetadata::set_status(::fnv::soa::framework::protobuf::ServiceStatus::Values value) {
  assert(::fnv::soa::framework::protobuf::ServiceStatus::Values_IsValid(value));
  set_has_status();
  status_ = value;
  // @@protoc_insertion_point(field_set:fnv.soa.framework.protobuf.ProvisionedServiceMetadata.status)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace framework
}  // namespace soa
}  // namespace fnv

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ProvisionedServiceMetadata_2eproto__INCLUDED
