// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProvisionedServicesListPayload.proto

#ifndef PROTOBUF_ProvisionedServicesListPayload_2eproto__INCLUDED
#define PROTOBUF_ProvisionedServicesListPayload_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "sm_transaction_status_public.pb.h"  // IWYU pragma: export
#include "ProvisionedServiceMetadata.pb.h"  // IWYU pragma: export
#include "Endpoint.pb.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

namespace protobuf_ProvisionedServicesListPayload_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsProvisionedServicesListPayloadImpl();
void InitDefaultsProvisionedServicesListPayload();
inline void InitDefaults() {
  InitDefaultsProvisionedServicesListPayload();
}
}  // namespace protobuf_ProvisionedServicesListPayload_2eproto
namespace fnv {
namespace soa {
namespace framework {
namespace protobuf {
class ProvisionedServicesListPayload;
class ProvisionedServicesListPayloadDefaultTypeInternal;
extern ProvisionedServicesListPayloadDefaultTypeInternal _ProvisionedServicesListPayload_default_instance_;
}  // namespace protobuf
}  // namespace framework
}  // namespace soa
}  // namespace fnv
namespace fnv {
namespace soa {
namespace framework {
namespace protobuf {

// ===================================================================

class ProvisionedServicesListPayload : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fnv.soa.framework.protobuf.ProvisionedServicesListPayload) */ {
 public:
  ProvisionedServicesListPayload();
  virtual ~ProvisionedServicesListPayload();

  ProvisionedServicesListPayload(const ProvisionedServicesListPayload& from);

  inline ProvisionedServicesListPayload& operator=(const ProvisionedServicesListPayload& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ProvisionedServicesListPayload(ProvisionedServicesListPayload&& from) noexcept
    : ProvisionedServicesListPayload() {
    *this = ::std::move(from);
  }

  inline ProvisionedServicesListPayload& operator=(ProvisionedServicesListPayload&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProvisionedServicesListPayload& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ProvisionedServicesListPayload* internal_default_instance() {
    return reinterpret_cast<const ProvisionedServicesListPayload*>(
               &_ProvisionedServicesListPayload_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(ProvisionedServicesListPayload* other);
  friend void swap(ProvisionedServicesListPayload& a, ProvisionedServicesListPayload& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ProvisionedServicesListPayload* New() const PROTOBUF_FINAL { return New(NULL); }

  ProvisionedServicesListPayload* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ProvisionedServicesListPayload* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .fnv.soa.framework.protobuf.ProvisionedServiceMetadata serviceMetadata = 2;
  int servicemetadata_size() const;
  void clear_servicemetadata();
  static const int kServiceMetadataFieldNumber = 2;
  const ::fnv::soa::framework::protobuf::ProvisionedServiceMetadata& servicemetadata(int index) const;
  ::fnv::soa::framework::protobuf::ProvisionedServiceMetadata* mutable_servicemetadata(int index);
  ::fnv::soa::framework::protobuf::ProvisionedServiceMetadata* add_servicemetadata();
  ::google::protobuf::RepeatedPtrField< ::fnv::soa::framework::protobuf::ProvisionedServiceMetadata >*
      mutable_servicemetadata();
  const ::google::protobuf::RepeatedPtrField< ::fnv::soa::framework::protobuf::ProvisionedServiceMetadata >&
      servicemetadata() const;

  // optional .fnv.soa.framework.protobuf.Endpoint serviceDomainEndpoint = 3;
  bool has_servicedomainendpoint() const;
  void clear_servicedomainendpoint();
  static const int kServiceDomainEndpointFieldNumber = 3;
  const ::fnv::soa::framework::protobuf::Endpoint& servicedomainendpoint() const;
  ::fnv::soa::framework::protobuf::Endpoint* release_servicedomainendpoint();
  ::fnv::soa::framework::protobuf::Endpoint* mutable_servicedomainendpoint();
  void set_allocated_servicedomainendpoint(::fnv::soa::framework::protobuf::Endpoint* servicedomainendpoint);

  // optional .fnv.soa.framework.protobuf.SmTransactionStatus.Status transactionStatus = 1 [default = OK];
  bool has_transactionstatus() const;
  void clear_transactionstatus();
  static const int kTransactionStatusFieldNumber = 1;
  ::fnv::soa::framework::protobuf::SmTransactionStatus_Status transactionstatus() const;
  void set_transactionstatus(::fnv::soa::framework::protobuf::SmTransactionStatus_Status value);

  // @@protoc_insertion_point(class_scope:fnv.soa.framework.protobuf.ProvisionedServicesListPayload)
 private:
  void set_has_transactionstatus();
  void clear_has_transactionstatus();
  void set_has_servicedomainendpoint();
  void clear_has_servicedomainendpoint();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::fnv::soa::framework::protobuf::ProvisionedServiceMetadata > servicemetadata_;
  ::fnv::soa::framework::protobuf::Endpoint* servicedomainendpoint_;
  int transactionstatus_;
  friend struct ::protobuf_ProvisionedServicesListPayload_2eproto::TableStruct;
  friend void ::protobuf_ProvisionedServicesListPayload_2eproto::InitDefaultsProvisionedServicesListPayloadImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ProvisionedServicesListPayload

// optional .fnv.soa.framework.protobuf.SmTransactionStatus.Status transactionStatus = 1 [default = OK];
inline bool ProvisionedServicesListPayload::has_transactionstatus() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProvisionedServicesListPayload::set_has_transactionstatus() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProvisionedServicesListPayload::clear_has_transactionstatus() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProvisionedServicesListPayload::clear_transactionstatus() {
  transactionstatus_ = 1;
  clear_has_transactionstatus();
}
inline ::fnv::soa::framework::protobuf::SmTransactionStatus_Status ProvisionedServicesListPayload::transactionstatus() const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.protobuf.ProvisionedServicesListPayload.transactionStatus)
  return static_cast< ::fnv::soa::framework::protobuf::SmTransactionStatus_Status >(transactionstatus_);
}
inline void ProvisionedServicesListPayload::set_transactionstatus(::fnv::soa::framework::protobuf::SmTransactionStatus_Status value) {
  assert(::fnv::soa::framework::protobuf::SmTransactionStatus_Status_IsValid(value));
  set_has_transactionstatus();
  transactionstatus_ = value;
  // @@protoc_insertion_point(field_set:fnv.soa.framework.protobuf.ProvisionedServicesListPayload.transactionStatus)
}

// repeated .fnv.soa.framework.protobuf.ProvisionedServiceMetadata serviceMetadata = 2;
inline int ProvisionedServicesListPayload::servicemetadata_size() const {
  return servicemetadata_.size();
}
inline const ::fnv::soa::framework::protobuf::ProvisionedServiceMetadata& ProvisionedServicesListPayload::servicemetadata(int index) const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.protobuf.ProvisionedServicesListPayload.serviceMetadata)
  return servicemetadata_.Get(index);
}
inline ::fnv::soa::framework::protobuf::ProvisionedServiceMetadata* ProvisionedServicesListPayload::mutable_servicemetadata(int index) {
  // @@protoc_insertion_point(field_mutable:fnv.soa.framework.protobuf.ProvisionedServicesListPayload.serviceMetadata)
  return servicemetadata_.Mutable(index);
}
inline ::fnv::soa::framework::protobuf::ProvisionedServiceMetadata* ProvisionedServicesListPayload::add_servicemetadata() {
  // @@protoc_insertion_point(field_add:fnv.soa.framework.protobuf.ProvisionedServicesListPayload.serviceMetadata)
  return servicemetadata_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::fnv::soa::framework::protobuf::ProvisionedServiceMetadata >*
ProvisionedServicesListPayload::mutable_servicemetadata() {
  // @@protoc_insertion_point(field_mutable_list:fnv.soa.framework.protobuf.ProvisionedServicesListPayload.serviceMetadata)
  return &servicemetadata_;
}
inline const ::google::protobuf::RepeatedPtrField< ::fnv::soa::framework::protobuf::ProvisionedServiceMetadata >&
ProvisionedServicesListPayload::servicemetadata() const {
  // @@protoc_insertion_point(field_list:fnv.soa.framework.protobuf.ProvisionedServicesListPayload.serviceMetadata)
  return servicemetadata_;
}

// optional .fnv.soa.framework.protobuf.Endpoint serviceDomainEndpoint = 3;
inline bool ProvisionedServicesListPayload::has_servicedomainendpoint() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProvisionedServicesListPayload::set_has_servicedomainendpoint() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProvisionedServicesListPayload::clear_has_servicedomainendpoint() {
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::fnv::soa::framework::protobuf::Endpoint& ProvisionedServicesListPayload::servicedomainendpoint() const {
  const ::fnv::soa::framework::protobuf::Endpoint* p = servicedomainendpoint_;
  // @@protoc_insertion_point(field_get:fnv.soa.framework.protobuf.ProvisionedServicesListPayload.serviceDomainEndpoint)
  return p != NULL ? *p : *reinterpret_cast<const ::fnv::soa::framework::protobuf::Endpoint*>(
      &::fnv::soa::framework::protobuf::_Endpoint_default_instance_);
}
inline ::fnv::soa::framework::protobuf::Endpoint* ProvisionedServicesListPayload::release_servicedomainendpoint() {
  // @@protoc_insertion_point(field_release:fnv.soa.framework.protobuf.ProvisionedServicesListPayload.serviceDomainEndpoint)
  clear_has_servicedomainendpoint();
  ::fnv::soa::framework::protobuf::Endpoint* temp = servicedomainendpoint_;
  servicedomainendpoint_ = NULL;
  return temp;
}
inline ::fnv::soa::framework::protobuf::Endpoint* ProvisionedServicesListPayload::mutable_servicedomainendpoint() {
  set_has_servicedomainendpoint();
  if (servicedomainendpoint_ == NULL) {
    servicedomainendpoint_ = new ::fnv::soa::framework::protobuf::Endpoint;
  }
  // @@protoc_insertion_point(field_mutable:fnv.soa.framework.protobuf.ProvisionedServicesListPayload.serviceDomainEndpoint)
  return servicedomainendpoint_;
}
inline void ProvisionedServicesListPayload::set_allocated_servicedomainendpoint(::fnv::soa::framework::protobuf::Endpoint* servicedomainendpoint) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(servicedomainendpoint_);
  }
  if (servicedomainendpoint) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      servicedomainendpoint = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, servicedomainendpoint, submessage_arena);
    }
    set_has_servicedomainendpoint();
  } else {
    clear_has_servicedomainendpoint();
  }
  servicedomainendpoint_ = servicedomainendpoint;
  // @@protoc_insertion_point(field_set_allocated:fnv.soa.framework.protobuf.ProvisionedServicesListPayload.serviceDomainEndpoint)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace framework
}  // namespace soa
}  // namespace fnv

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ProvisionedServicesListPayload_2eproto__INCLUDED
