/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ProvisionedServiceMetadata.proto */

#ifndef PROTOBUF_C_ProvisionedServiceMetadata_2eproto__INCLUDED
#define PROTOBUF_C_ProvisionedServiceMetadata_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "ServiceContract.pb-c.h"
#include "soa_service_status.pb-c.h"

typedef struct _Fnv__Soa__Framework__Protobuf__ProvisionedServiceMetadata Fnv__Soa__Framework__Protobuf__ProvisionedServiceMetadata;


/* --- enums --- */


/* --- messages --- */

/*
 **
 * @fnv_message_proto
 * @fnv_deprecated
 */
struct  _Fnv__Soa__Framework__Protobuf__ProvisionedServiceMetadata
{
  ProtobufCMessage base;
  Fnv__Soa__Framework__Protobuf__ServiceContract *contract;
  protobuf_c_boolean has_status;
  Fnv__Soa__Framework__Protobuf__ServiceStatus__Values status;
};
#define FNV__SOA__FRAMEWORK__PROTOBUF__PROVISIONED_SERVICE_METADATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fnv__soa__framework__protobuf__provisioned_service_metadata__descriptor) \
    , NULL, 0, FNV__SOA__FRAMEWORK__PROTOBUF__SERVICE_STATUS__VALUES__AVAILABLE }


/* Fnv__Soa__Framework__Protobuf__ProvisionedServiceMetadata methods */
void   fnv__soa__framework__protobuf__provisioned_service_metadata__init
                     (Fnv__Soa__Framework__Protobuf__ProvisionedServiceMetadata         *message);
size_t fnv__soa__framework__protobuf__provisioned_service_metadata__get_packed_size
                     (const Fnv__Soa__Framework__Protobuf__ProvisionedServiceMetadata   *message);
size_t fnv__soa__framework__protobuf__provisioned_service_metadata__pack
                     (const Fnv__Soa__Framework__Protobuf__ProvisionedServiceMetadata   *message,
                      uint8_t             *out);
size_t fnv__soa__framework__protobuf__provisioned_service_metadata__pack_to_buffer
                     (const Fnv__Soa__Framework__Protobuf__ProvisionedServiceMetadata   *message,
                      ProtobufCBuffer     *buffer);
Fnv__Soa__Framework__Protobuf__ProvisionedServiceMetadata *
       fnv__soa__framework__protobuf__provisioned_service_metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fnv__soa__framework__protobuf__provisioned_service_metadata__free_unpacked
                     (Fnv__Soa__Framework__Protobuf__ProvisionedServiceMetadata *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Fnv__Soa__Framework__Protobuf__ProvisionedServiceMetadata_Closure)
                 (const Fnv__Soa__Framework__Protobuf__ProvisionedServiceMetadata *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor fnv__soa__framework__protobuf__provisioned_service_metadata__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_ProvisionedServiceMetadata_2eproto__INCLUDED */
