// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RegisterServicesRequestPayload.proto

#ifndef PROTOBUF_RegisterServicesRequestPayload_2eproto__INCLUDED
#define PROTOBUF_RegisterServicesRequestPayload_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "ServiceHostMetadata.pb.h"  // IWYU pragma: export
#include "Endpoint.pb.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

namespace protobuf_RegisterServicesRequestPayload_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsRegisterServicesRequestPayloadImpl();
void InitDefaultsRegisterServicesRequestPayload();
inline void InitDefaults() {
  InitDefaultsRegisterServicesRequestPayload();
}
}  // namespace protobuf_RegisterServicesRequestPayload_2eproto
namespace fnv {
namespace soa {
namespace framework {
namespace protobuf {
class RegisterServicesRequestPayload;
class RegisterServicesRequestPayloadDefaultTypeInternal;
extern RegisterServicesRequestPayloadDefaultTypeInternal _RegisterServicesRequestPayload_default_instance_;
}  // namespace protobuf
}  // namespace framework
}  // namespace soa
}  // namespace fnv
namespace fnv {
namespace soa {
namespace framework {
namespace protobuf {

// ===================================================================

class RegisterServicesRequestPayload : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fnv.soa.framework.protobuf.RegisterServicesRequestPayload) */ {
 public:
  RegisterServicesRequestPayload();
  virtual ~RegisterServicesRequestPayload();

  RegisterServicesRequestPayload(const RegisterServicesRequestPayload& from);

  inline RegisterServicesRequestPayload& operator=(const RegisterServicesRequestPayload& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RegisterServicesRequestPayload(RegisterServicesRequestPayload&& from) noexcept
    : RegisterServicesRequestPayload() {
    *this = ::std::move(from);
  }

  inline RegisterServicesRequestPayload& operator=(RegisterServicesRequestPayload&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RegisterServicesRequestPayload& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RegisterServicesRequestPayload* internal_default_instance() {
    return reinterpret_cast<const RegisterServicesRequestPayload*>(
               &_RegisterServicesRequestPayload_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(RegisterServicesRequestPayload* other);
  friend void swap(RegisterServicesRequestPayload& a, RegisterServicesRequestPayload& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RegisterServicesRequestPayload* New() const PROTOBUF_FINAL { return New(NULL); }

  RegisterServicesRequestPayload* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RegisterServicesRequestPayload* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .fnv.soa.framework.protobuf.ServiceHostMetadataProto metadata = 1;
  int metadata_size() const;
  void clear_metadata();
  static const int kMetadataFieldNumber = 1;
  const ::fnv::soa::framework::protobuf::ServiceHostMetadataProto& metadata(int index) const;
  ::fnv::soa::framework::protobuf::ServiceHostMetadataProto* mutable_metadata(int index);
  ::fnv::soa::framework::protobuf::ServiceHostMetadataProto* add_metadata();
  ::google::protobuf::RepeatedPtrField< ::fnv::soa::framework::protobuf::ServiceHostMetadataProto >*
      mutable_metadata();
  const ::google::protobuf::RepeatedPtrField< ::fnv::soa::framework::protobuf::ServiceHostMetadataProto >&
      metadata() const;

  // @@protoc_insertion_point(class_scope:fnv.soa.framework.protobuf.RegisterServicesRequestPayload)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::fnv::soa::framework::protobuf::ServiceHostMetadataProto > metadata_;
  friend struct ::protobuf_RegisterServicesRequestPayload_2eproto::TableStruct;
  friend void ::protobuf_RegisterServicesRequestPayload_2eproto::InitDefaultsRegisterServicesRequestPayloadImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RegisterServicesRequestPayload

// repeated .fnv.soa.framework.protobuf.ServiceHostMetadataProto metadata = 1;
inline int RegisterServicesRequestPayload::metadata_size() const {
  return metadata_.size();
}
inline const ::fnv::soa::framework::protobuf::ServiceHostMetadataProto& RegisterServicesRequestPayload::metadata(int index) const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.protobuf.RegisterServicesRequestPayload.metadata)
  return metadata_.Get(index);
}
inline ::fnv::soa::framework::protobuf::ServiceHostMetadataProto* RegisterServicesRequestPayload::mutable_metadata(int index) {
  // @@protoc_insertion_point(field_mutable:fnv.soa.framework.protobuf.RegisterServicesRequestPayload.metadata)
  return metadata_.Mutable(index);
}
inline ::fnv::soa::framework::protobuf::ServiceHostMetadataProto* RegisterServicesRequestPayload::add_metadata() {
  // @@protoc_insertion_point(field_add:fnv.soa.framework.protobuf.RegisterServicesRequestPayload.metadata)
  return metadata_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::fnv::soa::framework::protobuf::ServiceHostMetadataProto >*
RegisterServicesRequestPayload::mutable_metadata() {
  // @@protoc_insertion_point(field_mutable_list:fnv.soa.framework.protobuf.RegisterServicesRequestPayload.metadata)
  return &metadata_;
}
inline const ::google::protobuf::RepeatedPtrField< ::fnv::soa::framework::protobuf::ServiceHostMetadataProto >&
RegisterServicesRequestPayload::metadata() const {
  // @@protoc_insertion_point(field_list:fnv.soa.framework.protobuf.RegisterServicesRequestPayload.metadata)
  return metadata_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace framework
}  // namespace soa
}  // namespace fnv

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_RegisterServicesRequestPayload_2eproto__INCLUDED
