// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServiceStatusRequestPayload.proto

#ifndef PROTOBUF_ServiceStatusRequestPayload_2eproto__INCLUDED
#define PROTOBUF_ServiceStatusRequestPayload_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "ServiceStatusRequestMetadata.pb.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

namespace protobuf_ServiceStatusRequestPayload_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsServiceStatusRequestPayloadProtoImpl();
void InitDefaultsServiceStatusRequestPayloadProto();
inline void InitDefaults() {
  InitDefaultsServiceStatusRequestPayloadProto();
}
}  // namespace protobuf_ServiceStatusRequestPayload_2eproto
namespace fnv {
namespace soa {
namespace framework {
namespace protobuf {
class ServiceStatusRequestPayloadProto;
class ServiceStatusRequestPayloadProtoDefaultTypeInternal;
extern ServiceStatusRequestPayloadProtoDefaultTypeInternal _ServiceStatusRequestPayloadProto_default_instance_;
}  // namespace protobuf
}  // namespace framework
}  // namespace soa
}  // namespace fnv
namespace fnv {
namespace soa {
namespace framework {
namespace protobuf {

// ===================================================================

class ServiceStatusRequestPayloadProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fnv.soa.framework.protobuf.ServiceStatusRequestPayloadProto) */ {
 public:
  ServiceStatusRequestPayloadProto();
  virtual ~ServiceStatusRequestPayloadProto();

  ServiceStatusRequestPayloadProto(const ServiceStatusRequestPayloadProto& from);

  inline ServiceStatusRequestPayloadProto& operator=(const ServiceStatusRequestPayloadProto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ServiceStatusRequestPayloadProto(ServiceStatusRequestPayloadProto&& from) noexcept
    : ServiceStatusRequestPayloadProto() {
    *this = ::std::move(from);
  }

  inline ServiceStatusRequestPayloadProto& operator=(ServiceStatusRequestPayloadProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ServiceStatusRequestPayloadProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ServiceStatusRequestPayloadProto* internal_default_instance() {
    return reinterpret_cast<const ServiceStatusRequestPayloadProto*>(
               &_ServiceStatusRequestPayloadProto_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(ServiceStatusRequestPayloadProto* other);
  friend void swap(ServiceStatusRequestPayloadProto& a, ServiceStatusRequestPayloadProto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ServiceStatusRequestPayloadProto* New() const PROTOBUF_FINAL { return New(NULL); }

  ServiceStatusRequestPayloadProto* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ServiceStatusRequestPayloadProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .fnv.soa.framework.protobuf.ServiceStatusRequestMetadataProto metadata = 1;
  int metadata_size() const;
  void clear_metadata();
  static const int kMetadataFieldNumber = 1;
  const ::fnv::soa::framework::protobuf::ServiceStatusRequestMetadataProto& metadata(int index) const;
  ::fnv::soa::framework::protobuf::ServiceStatusRequestMetadataProto* mutable_metadata(int index);
  ::fnv::soa::framework::protobuf::ServiceStatusRequestMetadataProto* add_metadata();
  ::google::protobuf::RepeatedPtrField< ::fnv::soa::framework::protobuf::ServiceStatusRequestMetadataProto >*
      mutable_metadata();
  const ::google::protobuf::RepeatedPtrField< ::fnv::soa::framework::protobuf::ServiceStatusRequestMetadataProto >&
      metadata() const;

  // @@protoc_insertion_point(class_scope:fnv.soa.framework.protobuf.ServiceStatusRequestPayloadProto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::fnv::soa::framework::protobuf::ServiceStatusRequestMetadataProto > metadata_;
  friend struct ::protobuf_ServiceStatusRequestPayload_2eproto::TableStruct;
  friend void ::protobuf_ServiceStatusRequestPayload_2eproto::InitDefaultsServiceStatusRequestPayloadProtoImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ServiceStatusRequestPayloadProto

// repeated .fnv.soa.framework.protobuf.ServiceStatusRequestMetadataProto metadata = 1;
inline int ServiceStatusRequestPayloadProto::metadata_size() const {
  return metadata_.size();
}
inline const ::fnv::soa::framework::protobuf::ServiceStatusRequestMetadataProto& ServiceStatusRequestPayloadProto::metadata(int index) const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.protobuf.ServiceStatusRequestPayloadProto.metadata)
  return metadata_.Get(index);
}
inline ::fnv::soa::framework::protobuf::ServiceStatusRequestMetadataProto* ServiceStatusRequestPayloadProto::mutable_metadata(int index) {
  // @@protoc_insertion_point(field_mutable:fnv.soa.framework.protobuf.ServiceStatusRequestPayloadProto.metadata)
  return metadata_.Mutable(index);
}
inline ::fnv::soa::framework::protobuf::ServiceStatusRequestMetadataProto* ServiceStatusRequestPayloadProto::add_metadata() {
  // @@protoc_insertion_point(field_add:fnv.soa.framework.protobuf.ServiceStatusRequestPayloadProto.metadata)
  return metadata_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::fnv::soa::framework::protobuf::ServiceStatusRequestMetadataProto >*
ServiceStatusRequestPayloadProto::mutable_metadata() {
  // @@protoc_insertion_point(field_mutable_list:fnv.soa.framework.protobuf.ServiceStatusRequestPayloadProto.metadata)
  return &metadata_;
}
inline const ::google::protobuf::RepeatedPtrField< ::fnv::soa::framework::protobuf::ServiceStatusRequestMetadataProto >&
ServiceStatusRequestPayloadProto::metadata() const {
  // @@protoc_insertion_point(field_list:fnv.soa.framework.protobuf.ServiceStatusRequestPayloadProto.metadata)
  return metadata_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace framework
}  // namespace soa
}  // namespace fnv

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ServiceStatusRequestPayload_2eproto__INCLUDED
