/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ServiceStatusResponsePayload.proto */

#ifndef PROTOBUF_C_ServiceStatusResponsePayload_2eproto__INCLUDED
#define PROTOBUF_C_ServiceStatusResponsePayload_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "sm_transaction_status_public.pb-c.h"
#include "ServiceStatusMetadata.pb-c.h"

typedef struct _Fnv__Soa__Framework__Protobuf__ServiceStatusResponsePayloadProto Fnv__Soa__Framework__Protobuf__ServiceStatusResponsePayloadProto;


/* --- enums --- */


/* --- messages --- */

/*
 **
 * @fnv_message_proto
 * @fnv_deprecated
 */
struct  _Fnv__Soa__Framework__Protobuf__ServiceStatusResponsePayloadProto
{
  ProtobufCMessage base;
  protobuf_c_boolean has_transactionstatus;
  Fnv__Soa__Framework__Protobuf__SmTransactionStatus__Status transactionstatus;
  size_t n_metadata;
  Fnv__Soa__Framework__Protobuf__ServiceStatusMetadataProto **metadata;
};
#define FNV__SOA__FRAMEWORK__PROTOBUF__SERVICE_STATUS_RESPONSE_PAYLOAD_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fnv__soa__framework__protobuf__service_status_response_payload_proto__descriptor) \
    , 0, FNV__SOA__FRAMEWORK__PROTOBUF__SM_TRANSACTION_STATUS__STATUS__OK, 0,NULL }


/* Fnv__Soa__Framework__Protobuf__ServiceStatusResponsePayloadProto methods */
void   fnv__soa__framework__protobuf__service_status_response_payload_proto__init
                     (Fnv__Soa__Framework__Protobuf__ServiceStatusResponsePayloadProto         *message);
size_t fnv__soa__framework__protobuf__service_status_response_payload_proto__get_packed_size
                     (const Fnv__Soa__Framework__Protobuf__ServiceStatusResponsePayloadProto   *message);
size_t fnv__soa__framework__protobuf__service_status_response_payload_proto__pack
                     (const Fnv__Soa__Framework__Protobuf__ServiceStatusResponsePayloadProto   *message,
                      uint8_t             *out);
size_t fnv__soa__framework__protobuf__service_status_response_payload_proto__pack_to_buffer
                     (const Fnv__Soa__Framework__Protobuf__ServiceStatusResponsePayloadProto   *message,
                      ProtobufCBuffer     *buffer);
Fnv__Soa__Framework__Protobuf__ServiceStatusResponsePayloadProto *
       fnv__soa__framework__protobuf__service_status_response_payload_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fnv__soa__framework__protobuf__service_status_response_payload_proto__free_unpacked
                     (Fnv__Soa__Framework__Protobuf__ServiceStatusResponsePayloadProto *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Fnv__Soa__Framework__Protobuf__ServiceStatusResponsePayloadProto_Closure)
                 (const Fnv__Soa__Framework__Protobuf__ServiceStatusResponsePayloadProto *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor fnv__soa__framework__protobuf__service_status_response_payload_proto__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_ServiceStatusResponsePayload_2eproto__INCLUDED */
