// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServicePermissions.proto

#ifndef PROTOBUF_ServicePermissions_2eproto__INCLUDED
#define PROTOBUF_ServicePermissions_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_ServicePermissions_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsServicePermissionsImpl();
void InitDefaultsServicePermissions();
inline void InitDefaults() {
  InitDefaultsServicePermissions();
}
}  // namespace protobuf_ServicePermissions_2eproto
namespace fnv {
namespace soa {
namespace framework {
namespace protobuf {
class ServicePermissions;
class ServicePermissionsDefaultTypeInternal;
extern ServicePermissionsDefaultTypeInternal _ServicePermissions_default_instance_;
}  // namespace protobuf
}  // namespace framework
}  // namespace soa
}  // namespace fnv
namespace fnv {
namespace soa {
namespace framework {
namespace protobuf {

// ===================================================================

class ServicePermissions : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fnv.soa.framework.protobuf.ServicePermissions) */ {
 public:
  ServicePermissions();
  virtual ~ServicePermissions();

  ServicePermissions(const ServicePermissions& from);

  inline ServicePermissions& operator=(const ServicePermissions& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ServicePermissions(ServicePermissions&& from) noexcept
    : ServicePermissions() {
    *this = ::std::move(from);
  }

  inline ServicePermissions& operator=(ServicePermissions&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ServicePermissions& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ServicePermissions* internal_default_instance() {
    return reinterpret_cast<const ServicePermissions*>(
               &_ServicePermissions_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(ServicePermissions* other);
  friend void swap(ServicePermissions& a, ServicePermissions& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ServicePermissions* New() const PROTOBUF_FINAL { return New(NULL); }

  ServicePermissions* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ServicePermissions* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string clientId = 1;
  bool has_clientid() const;
  void clear_clientid();
  static const int kClientIdFieldNumber = 1;
  const ::std::string& clientid() const;
  void set_clientid(const ::std::string& value);
  #if LANG_CXX11
  void set_clientid(::std::string&& value);
  #endif
  void set_clientid(const char* value);
  void set_clientid(const char* value, size_t size);
  ::std::string* mutable_clientid();
  ::std::string* release_clientid();
  void set_allocated_clientid(::std::string* clientid);

  // @@protoc_insertion_point(class_scope:fnv.soa.framework.protobuf.ServicePermissions)
 private:
  void set_has_clientid();
  void clear_has_clientid();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr clientid_;
  friend struct ::protobuf_ServicePermissions_2eproto::TableStruct;
  friend void ::protobuf_ServicePermissions_2eproto::InitDefaultsServicePermissionsImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ServicePermissions

// required string clientId = 1;
inline bool ServicePermissions::has_clientid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ServicePermissions::set_has_clientid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ServicePermissions::clear_has_clientid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ServicePermissions::clear_clientid() {
  clientid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_clientid();
}
inline const ::std::string& ServicePermissions::clientid() const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.protobuf.ServicePermissions.clientId)
  return clientid_.GetNoArena();
}
inline void ServicePermissions::set_clientid(const ::std::string& value) {
  set_has_clientid();
  clientid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fnv.soa.framework.protobuf.ServicePermissions.clientId)
}
#if LANG_CXX11
inline void ServicePermissions::set_clientid(::std::string&& value) {
  set_has_clientid();
  clientid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fnv.soa.framework.protobuf.ServicePermissions.clientId)
}
#endif
inline void ServicePermissions::set_clientid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_clientid();
  clientid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fnv.soa.framework.protobuf.ServicePermissions.clientId)
}
inline void ServicePermissions::set_clientid(const char* value, size_t size) {
  set_has_clientid();
  clientid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fnv.soa.framework.protobuf.ServicePermissions.clientId)
}
inline ::std::string* ServicePermissions::mutable_clientid() {
  set_has_clientid();
  // @@protoc_insertion_point(field_mutable:fnv.soa.framework.protobuf.ServicePermissions.clientId)
  return clientid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ServicePermissions::release_clientid() {
  // @@protoc_insertion_point(field_release:fnv.soa.framework.protobuf.ServicePermissions.clientId)
  clear_has_clientid();
  return clientid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ServicePermissions::set_allocated_clientid(::std::string* clientid) {
  if (clientid != NULL) {
    set_has_clientid();
  } else {
    clear_has_clientid();
  }
  clientid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), clientid);
  // @@protoc_insertion_point(field_set_allocated:fnv.soa.framework.protobuf.ServicePermissions.clientId)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace framework
}  // namespace soa
}  // namespace fnv

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ServicePermissions_2eproto__INCLUDED
