// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServiceStatusMetadata.proto

#ifndef PROTOBUF_ServiceStatusMetadata_2eproto__INCLUDED
#define PROTOBUF_ServiceStatusMetadata_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "soa_service_status.pb.h"  // IWYU pragma: export
#include "Endpoint.pb.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

namespace protobuf_ServiceStatusMetadata_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsServiceStatusMetadataProtoImpl();
void InitDefaultsServiceStatusMetadataProto();
inline void InitDefaults() {
  InitDefaultsServiceStatusMetadataProto();
}
}  // namespace protobuf_ServiceStatusMetadata_2eproto
namespace fnv {
namespace soa {
namespace framework {
namespace protobuf {
class ServiceStatusMetadataProto;
class ServiceStatusMetadataProtoDefaultTypeInternal;
extern ServiceStatusMetadataProtoDefaultTypeInternal _ServiceStatusMetadataProto_default_instance_;
}  // namespace protobuf
}  // namespace framework
}  // namespace soa
}  // namespace fnv
namespace fnv {
namespace soa {
namespace framework {
namespace protobuf {

// ===================================================================

class ServiceStatusMetadataProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fnv.soa.framework.protobuf.ServiceStatusMetadataProto) */ {
 public:
  ServiceStatusMetadataProto();
  virtual ~ServiceStatusMetadataProto();

  ServiceStatusMetadataProto(const ServiceStatusMetadataProto& from);

  inline ServiceStatusMetadataProto& operator=(const ServiceStatusMetadataProto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ServiceStatusMetadataProto(ServiceStatusMetadataProto&& from) noexcept
    : ServiceStatusMetadataProto() {
    *this = ::std::move(from);
  }

  inline ServiceStatusMetadataProto& operator=(ServiceStatusMetadataProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ServiceStatusMetadataProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ServiceStatusMetadataProto* internal_default_instance() {
    return reinterpret_cast<const ServiceStatusMetadataProto*>(
               &_ServiceStatusMetadataProto_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(ServiceStatusMetadataProto* other);
  friend void swap(ServiceStatusMetadataProto& a, ServiceStatusMetadataProto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ServiceStatusMetadataProto* New() const PROTOBUF_FINAL { return New(NULL); }

  ServiceStatusMetadataProto* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ServiceStatusMetadataProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .fnv.soa.framework.protobuf.Endpoint serviceEndpoint = 1;
  bool has_serviceendpoint() const;
  void clear_serviceendpoint();
  static const int kServiceEndpointFieldNumber = 1;
  const ::fnv::soa::framework::protobuf::Endpoint& serviceendpoint() const;
  ::fnv::soa::framework::protobuf::Endpoint* release_serviceendpoint();
  ::fnv::soa::framework::protobuf::Endpoint* mutable_serviceendpoint();
  void set_allocated_serviceendpoint(::fnv::soa::framework::protobuf::Endpoint* serviceendpoint);

  // optional .fnv.soa.framework.protobuf.ServiceStatus.Values serviceStatus = 2 [default = NOT_AVAILABLE];
  bool has_servicestatus() const;
  void clear_servicestatus();
  static const int kServiceStatusFieldNumber = 2;
  ::fnv::soa::framework::protobuf::ServiceStatus::Values servicestatus() const;
  void set_servicestatus(::fnv::soa::framework::protobuf::ServiceStatus::Values value);

  // @@protoc_insertion_point(class_scope:fnv.soa.framework.protobuf.ServiceStatusMetadataProto)
 private:
  void set_has_serviceendpoint();
  void clear_has_serviceendpoint();
  void set_has_servicestatus();
  void clear_has_servicestatus();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::fnv::soa::framework::protobuf::Endpoint* serviceendpoint_;
  int servicestatus_;
  friend struct ::protobuf_ServiceStatusMetadata_2eproto::TableStruct;
  friend void ::protobuf_ServiceStatusMetadata_2eproto::InitDefaultsServiceStatusMetadataProtoImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ServiceStatusMetadataProto

// optional .fnv.soa.framework.protobuf.Endpoint serviceEndpoint = 1;
inline bool ServiceStatusMetadataProto::has_serviceendpoint() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ServiceStatusMetadataProto::set_has_serviceendpoint() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ServiceStatusMetadataProto::clear_has_serviceendpoint() {
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::fnv::soa::framework::protobuf::Endpoint& ServiceStatusMetadataProto::serviceendpoint() const {
  const ::fnv::soa::framework::protobuf::Endpoint* p = serviceendpoint_;
  // @@protoc_insertion_point(field_get:fnv.soa.framework.protobuf.ServiceStatusMetadataProto.serviceEndpoint)
  return p != NULL ? *p : *reinterpret_cast<const ::fnv::soa::framework::protobuf::Endpoint*>(
      &::fnv::soa::framework::protobuf::_Endpoint_default_instance_);
}
inline ::fnv::soa::framework::protobuf::Endpoint* ServiceStatusMetadataProto::release_serviceendpoint() {
  // @@protoc_insertion_point(field_release:fnv.soa.framework.protobuf.ServiceStatusMetadataProto.serviceEndpoint)
  clear_has_serviceendpoint();
  ::fnv::soa::framework::protobuf::Endpoint* temp = serviceendpoint_;
  serviceendpoint_ = NULL;
  return temp;
}
inline ::fnv::soa::framework::protobuf::Endpoint* ServiceStatusMetadataProto::mutable_serviceendpoint() {
  set_has_serviceendpoint();
  if (serviceendpoint_ == NULL) {
    serviceendpoint_ = new ::fnv::soa::framework::protobuf::Endpoint;
  }
  // @@protoc_insertion_point(field_mutable:fnv.soa.framework.protobuf.ServiceStatusMetadataProto.serviceEndpoint)
  return serviceendpoint_;
}
inline void ServiceStatusMetadataProto::set_allocated_serviceendpoint(::fnv::soa::framework::protobuf::Endpoint* serviceendpoint) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(serviceendpoint_);
  }
  if (serviceendpoint) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      serviceendpoint = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, serviceendpoint, submessage_arena);
    }
    set_has_serviceendpoint();
  } else {
    clear_has_serviceendpoint();
  }
  serviceendpoint_ = serviceendpoint;
  // @@protoc_insertion_point(field_set_allocated:fnv.soa.framework.protobuf.ServiceStatusMetadataProto.serviceEndpoint)
}

// optional .fnv.soa.framework.protobuf.ServiceStatus.Values serviceStatus = 2 [default = NOT_AVAILABLE];
inline bool ServiceStatusMetadataProto::has_servicestatus() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ServiceStatusMetadataProto::set_has_servicestatus() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ServiceStatusMetadataProto::clear_has_servicestatus() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ServiceStatusMetadataProto::clear_servicestatus() {
  servicestatus_ = 0;
  clear_has_servicestatus();
}
inline ::fnv::soa::framework::protobuf::ServiceStatus::Values ServiceStatusMetadataProto::servicestatus() const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.protobuf.ServiceStatusMetadataProto.serviceStatus)
  return static_cast< ::fnv::soa::framework::protobuf::ServiceStatus::Values >(servicestatus_);
}
inline void ServiceStatusMetadataProto::set_servicestatus(::fnv::soa::framework::protobuf::ServiceStatus::Values value) {
  assert(::fnv::soa::framework::protobuf::ServiceStatus::Values_IsValid(value));
  set_has_servicestatus();
  servicestatus_ = value;
  // @@protoc_insertion_point(field_set:fnv.soa.framework.protobuf.ServiceStatusMetadataProto.serviceStatus)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace framework
}  // namespace soa
}  // namespace fnv

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ServiceStatusMetadata_2eproto__INCLUDED
