// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sm_transaction_status_public.proto

#ifndef PROTOBUF_sm_5ftransaction_5fstatus_5fpublic_2eproto__INCLUDED
#define PROTOBUF_sm_5ftransaction_5fstatus_5fpublic_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_sm_5ftransaction_5fstatus_5fpublic_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsSmTransactionStatusImpl();
void InitDefaultsSmTransactionStatus();
inline void InitDefaults() {
  InitDefaultsSmTransactionStatus();
}
}  // namespace protobuf_sm_5ftransaction_5fstatus_5fpublic_2eproto
namespace fnv {
namespace soa {
namespace framework {
namespace protobuf {
class SmTransactionStatus;
class SmTransactionStatusDefaultTypeInternal;
extern SmTransactionStatusDefaultTypeInternal _SmTransactionStatus_default_instance_;
}  // namespace protobuf
}  // namespace framework
}  // namespace soa
}  // namespace fnv
namespace fnv {
namespace soa {
namespace framework {
namespace protobuf {

enum SmTransactionStatus_Status {
  SmTransactionStatus_Status_OK = 1,
  SmTransactionStatus_Status_ERROR_GENERAL_ERROR = 2,
  SmTransactionStatus_Status_ERROR_SERVICE_NOT_REGISTERED = 3,
  SmTransactionStatus_Status_ERROR_SERVICES_DB_ERROR = 4,
  SmTransactionStatus_Status_ERROR_API_DEPRECATED = 5,
  SmTransactionStatus_Status_ERROR_API_NOT_IMPLEMENTED = 6,
  SmTransactionStatus_Status_ERROR_BAD_PROTOBUF = 7,
  SmTransactionStatus_Status_WARNING_DB_NOT_UPDATED = 8
};
bool SmTransactionStatus_Status_IsValid(int value);
const SmTransactionStatus_Status SmTransactionStatus_Status_Status_MIN = SmTransactionStatus_Status_OK;
const SmTransactionStatus_Status SmTransactionStatus_Status_Status_MAX = SmTransactionStatus_Status_WARNING_DB_NOT_UPDATED;
const int SmTransactionStatus_Status_Status_ARRAYSIZE = SmTransactionStatus_Status_Status_MAX + 1;

const ::google::protobuf::EnumDescriptor* SmTransactionStatus_Status_descriptor();
inline const ::std::string& SmTransactionStatus_Status_Name(SmTransactionStatus_Status value) {
  return ::google::protobuf::internal::NameOfEnum(
    SmTransactionStatus_Status_descriptor(), value);
}
inline bool SmTransactionStatus_Status_Parse(
    const ::std::string& name, SmTransactionStatus_Status* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SmTransactionStatus_Status>(
    SmTransactionStatus_Status_descriptor(), name, value);
}
// ===================================================================

class SmTransactionStatus : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fnv.soa.framework.protobuf.SmTransactionStatus) */ {
 public:
  SmTransactionStatus();
  virtual ~SmTransactionStatus();

  SmTransactionStatus(const SmTransactionStatus& from);

  inline SmTransactionStatus& operator=(const SmTransactionStatus& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SmTransactionStatus(SmTransactionStatus&& from) noexcept
    : SmTransactionStatus() {
    *this = ::std::move(from);
  }

  inline SmTransactionStatus& operator=(SmTransactionStatus&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SmTransactionStatus& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SmTransactionStatus* internal_default_instance() {
    return reinterpret_cast<const SmTransactionStatus*>(
               &_SmTransactionStatus_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(SmTransactionStatus* other);
  friend void swap(SmTransactionStatus& a, SmTransactionStatus& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SmTransactionStatus* New() const PROTOBUF_FINAL { return New(NULL); }

  SmTransactionStatus* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SmTransactionStatus* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef SmTransactionStatus_Status Status;
  static const Status OK =
    SmTransactionStatus_Status_OK;
  static const Status ERROR_GENERAL_ERROR =
    SmTransactionStatus_Status_ERROR_GENERAL_ERROR;
  static const Status ERROR_SERVICE_NOT_REGISTERED =
    SmTransactionStatus_Status_ERROR_SERVICE_NOT_REGISTERED;
  static const Status ERROR_SERVICES_DB_ERROR =
    SmTransactionStatus_Status_ERROR_SERVICES_DB_ERROR;
  static const Status ERROR_API_DEPRECATED =
    SmTransactionStatus_Status_ERROR_API_DEPRECATED;
  static const Status ERROR_API_NOT_IMPLEMENTED =
    SmTransactionStatus_Status_ERROR_API_NOT_IMPLEMENTED;
  static const Status ERROR_BAD_PROTOBUF =
    SmTransactionStatus_Status_ERROR_BAD_PROTOBUF;
  static const Status WARNING_DB_NOT_UPDATED =
    SmTransactionStatus_Status_WARNING_DB_NOT_UPDATED;
  static inline bool Status_IsValid(int value) {
    return SmTransactionStatus_Status_IsValid(value);
  }
  static const Status Status_MIN =
    SmTransactionStatus_Status_Status_MIN;
  static const Status Status_MAX =
    SmTransactionStatus_Status_Status_MAX;
  static const int Status_ARRAYSIZE =
    SmTransactionStatus_Status_Status_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Status_descriptor() {
    return SmTransactionStatus_Status_descriptor();
  }
  static inline const ::std::string& Status_Name(Status value) {
    return SmTransactionStatus_Status_Name(value);
  }
  static inline bool Status_Parse(const ::std::string& name,
      Status* value) {
    return SmTransactionStatus_Status_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:fnv.soa.framework.protobuf.SmTransactionStatus)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  friend struct ::protobuf_sm_5ftransaction_5fstatus_5fpublic_2eproto::TableStruct;
  friend void ::protobuf_sm_5ftransaction_5fstatus_5fpublic_2eproto::InitDefaultsSmTransactionStatusImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SmTransactionStatus

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace framework
}  // namespace soa
}  // namespace fnv

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::fnv::soa::framework::protobuf::SmTransactionStatus_Status> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::fnv::soa::framework::protobuf::SmTransactionStatus_Status>() {
  return ::fnv::soa::framework::protobuf::SmTransactionStatus_Status_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_sm_5ftransaction_5fstatus_5fpublic_2eproto__INCLUDED
