// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: soa_on_demand_proto.proto

#ifndef PROTOBUF_soa_5fon_5fdemand_5fproto_2eproto__INCLUDED
#define PROTOBUF_soa_5fon_5fdemand_5fproto_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_soa_5fon_5fdemand_5fproto_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsSoaOnDemandProtoImpl();
void InitDefaultsSoaOnDemandProto();
inline void InitDefaults() {
  InitDefaultsSoaOnDemandProto();
}
}  // namespace protobuf_soa_5fon_5fdemand_5fproto_2eproto
namespace fnv {
namespace soa {
namespace framework {
class SoaOnDemandProto;
class SoaOnDemandProtoDefaultTypeInternal;
extern SoaOnDemandProtoDefaultTypeInternal _SoaOnDemandProto_default_instance_;
}  // namespace framework
}  // namespace soa
}  // namespace fnv
namespace fnv {
namespace soa {
namespace framework {

// ===================================================================

class SoaOnDemandProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fnv.soa.framework.SoaOnDemandProto) */ {
 public:
  SoaOnDemandProto();
  virtual ~SoaOnDemandProto();

  SoaOnDemandProto(const SoaOnDemandProto& from);

  inline SoaOnDemandProto& operator=(const SoaOnDemandProto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SoaOnDemandProto(SoaOnDemandProto&& from) noexcept
    : SoaOnDemandProto() {
    *this = ::std::move(from);
  }

  inline SoaOnDemandProto& operator=(SoaOnDemandProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SoaOnDemandProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SoaOnDemandProto* internal_default_instance() {
    return reinterpret_cast<const SoaOnDemandProto*>(
               &_SoaOnDemandProto_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(SoaOnDemandProto* other);
  friend void swap(SoaOnDemandProto& a, SoaOnDemandProto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SoaOnDemandProto* New() const PROTOBUF_FINAL { return New(NULL); }

  SoaOnDemandProto* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SoaOnDemandProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes usermessage = 1;
  bool has_usermessage() const;
  void clear_usermessage();
  static const int kUsermessageFieldNumber = 1;
  const ::std::string& usermessage() const;
  void set_usermessage(const ::std::string& value);
  #if LANG_CXX11
  void set_usermessage(::std::string&& value);
  #endif
  void set_usermessage(const char* value);
  void set_usermessage(const void* value, size_t size);
  ::std::string* mutable_usermessage();
  ::std::string* release_usermessage();
  void set_allocated_usermessage(::std::string* usermessage);

  // optional string clientid = 100;
  bool has_clientid() const;
  void clear_clientid();
  static const int kClientidFieldNumber = 100;
  const ::std::string& clientid() const;
  void set_clientid(const ::std::string& value);
  #if LANG_CXX11
  void set_clientid(::std::string&& value);
  #endif
  void set_clientid(const char* value);
  void set_clientid(const char* value, size_t size);
  ::std::string* mutable_clientid();
  ::std::string* release_clientid();
  void set_allocated_clientid(::std::string* clientid);

  // optional string consumerbaseendpoint = 101;
  bool has_consumerbaseendpoint() const;
  void clear_consumerbaseendpoint();
  static const int kConsumerbaseendpointFieldNumber = 101;
  const ::std::string& consumerbaseendpoint() const;
  void set_consumerbaseendpoint(const ::std::string& value);
  #if LANG_CXX11
  void set_consumerbaseendpoint(::std::string&& value);
  #endif
  void set_consumerbaseendpoint(const char* value);
  void set_consumerbaseendpoint(const char* value, size_t size);
  ::std::string* mutable_consumerbaseendpoint();
  ::std::string* release_consumerbaseendpoint();
  void set_allocated_consumerbaseendpoint(::std::string* consumerbaseendpoint);

  // optional int64 soahandle = 102;
  bool has_soahandle() const;
  void clear_soahandle();
  static const int kSoahandleFieldNumber = 102;
  ::google::protobuf::int64 soahandle() const;
  void set_soahandle(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:fnv.soa.framework.SoaOnDemandProto)
 private:
  void set_has_usermessage();
  void clear_has_usermessage();
  void set_has_clientid();
  void clear_has_clientid();
  void set_has_consumerbaseendpoint();
  void clear_has_consumerbaseendpoint();
  void set_has_soahandle();
  void clear_has_soahandle();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr usermessage_;
  ::google::protobuf::internal::ArenaStringPtr clientid_;
  ::google::protobuf::internal::ArenaStringPtr consumerbaseendpoint_;
  ::google::protobuf::int64 soahandle_;
  friend struct ::protobuf_soa_5fon_5fdemand_5fproto_2eproto::TableStruct;
  friend void ::protobuf_soa_5fon_5fdemand_5fproto_2eproto::InitDefaultsSoaOnDemandProtoImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SoaOnDemandProto

// optional bytes usermessage = 1;
inline bool SoaOnDemandProto::has_usermessage() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SoaOnDemandProto::set_has_usermessage() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SoaOnDemandProto::clear_has_usermessage() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SoaOnDemandProto::clear_usermessage() {
  usermessage_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_usermessage();
}
inline const ::std::string& SoaOnDemandProto::usermessage() const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.SoaOnDemandProto.usermessage)
  return usermessage_.GetNoArena();
}
inline void SoaOnDemandProto::set_usermessage(const ::std::string& value) {
  set_has_usermessage();
  usermessage_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fnv.soa.framework.SoaOnDemandProto.usermessage)
}
#if LANG_CXX11
inline void SoaOnDemandProto::set_usermessage(::std::string&& value) {
  set_has_usermessage();
  usermessage_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fnv.soa.framework.SoaOnDemandProto.usermessage)
}
#endif
inline void SoaOnDemandProto::set_usermessage(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_usermessage();
  usermessage_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fnv.soa.framework.SoaOnDemandProto.usermessage)
}
inline void SoaOnDemandProto::set_usermessage(const void* value, size_t size) {
  set_has_usermessage();
  usermessage_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fnv.soa.framework.SoaOnDemandProto.usermessage)
}
inline ::std::string* SoaOnDemandProto::mutable_usermessage() {
  set_has_usermessage();
  // @@protoc_insertion_point(field_mutable:fnv.soa.framework.SoaOnDemandProto.usermessage)
  return usermessage_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SoaOnDemandProto::release_usermessage() {
  // @@protoc_insertion_point(field_release:fnv.soa.framework.SoaOnDemandProto.usermessage)
  clear_has_usermessage();
  return usermessage_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SoaOnDemandProto::set_allocated_usermessage(::std::string* usermessage) {
  if (usermessage != NULL) {
    set_has_usermessage();
  } else {
    clear_has_usermessage();
  }
  usermessage_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), usermessage);
  // @@protoc_insertion_point(field_set_allocated:fnv.soa.framework.SoaOnDemandProto.usermessage)
}

// optional string clientid = 100;
inline bool SoaOnDemandProto::has_clientid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SoaOnDemandProto::set_has_clientid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SoaOnDemandProto::clear_has_clientid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SoaOnDemandProto::clear_clientid() {
  clientid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_clientid();
}
inline const ::std::string& SoaOnDemandProto::clientid() const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.SoaOnDemandProto.clientid)
  return clientid_.GetNoArena();
}
inline void SoaOnDemandProto::set_clientid(const ::std::string& value) {
  set_has_clientid();
  clientid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fnv.soa.framework.SoaOnDemandProto.clientid)
}
#if LANG_CXX11
inline void SoaOnDemandProto::set_clientid(::std::string&& value) {
  set_has_clientid();
  clientid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fnv.soa.framework.SoaOnDemandProto.clientid)
}
#endif
inline void SoaOnDemandProto::set_clientid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_clientid();
  clientid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fnv.soa.framework.SoaOnDemandProto.clientid)
}
inline void SoaOnDemandProto::set_clientid(const char* value, size_t size) {
  set_has_clientid();
  clientid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fnv.soa.framework.SoaOnDemandProto.clientid)
}
inline ::std::string* SoaOnDemandProto::mutable_clientid() {
  set_has_clientid();
  // @@protoc_insertion_point(field_mutable:fnv.soa.framework.SoaOnDemandProto.clientid)
  return clientid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SoaOnDemandProto::release_clientid() {
  // @@protoc_insertion_point(field_release:fnv.soa.framework.SoaOnDemandProto.clientid)
  clear_has_clientid();
  return clientid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SoaOnDemandProto::set_allocated_clientid(::std::string* clientid) {
  if (clientid != NULL) {
    set_has_clientid();
  } else {
    clear_has_clientid();
  }
  clientid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), clientid);
  // @@protoc_insertion_point(field_set_allocated:fnv.soa.framework.SoaOnDemandProto.clientid)
}

// optional string consumerbaseendpoint = 101;
inline bool SoaOnDemandProto::has_consumerbaseendpoint() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SoaOnDemandProto::set_has_consumerbaseendpoint() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SoaOnDemandProto::clear_has_consumerbaseendpoint() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SoaOnDemandProto::clear_consumerbaseendpoint() {
  consumerbaseendpoint_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_consumerbaseendpoint();
}
inline const ::std::string& SoaOnDemandProto::consumerbaseendpoint() const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.SoaOnDemandProto.consumerbaseendpoint)
  return consumerbaseendpoint_.GetNoArena();
}
inline void SoaOnDemandProto::set_consumerbaseendpoint(const ::std::string& value) {
  set_has_consumerbaseendpoint();
  consumerbaseendpoint_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fnv.soa.framework.SoaOnDemandProto.consumerbaseendpoint)
}
#if LANG_CXX11
inline void SoaOnDemandProto::set_consumerbaseendpoint(::std::string&& value) {
  set_has_consumerbaseendpoint();
  consumerbaseendpoint_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fnv.soa.framework.SoaOnDemandProto.consumerbaseendpoint)
}
#endif
inline void SoaOnDemandProto::set_consumerbaseendpoint(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_consumerbaseendpoint();
  consumerbaseendpoint_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fnv.soa.framework.SoaOnDemandProto.consumerbaseendpoint)
}
inline void SoaOnDemandProto::set_consumerbaseendpoint(const char* value, size_t size) {
  set_has_consumerbaseendpoint();
  consumerbaseendpoint_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fnv.soa.framework.SoaOnDemandProto.consumerbaseendpoint)
}
inline ::std::string* SoaOnDemandProto::mutable_consumerbaseendpoint() {
  set_has_consumerbaseendpoint();
  // @@protoc_insertion_point(field_mutable:fnv.soa.framework.SoaOnDemandProto.consumerbaseendpoint)
  return consumerbaseendpoint_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SoaOnDemandProto::release_consumerbaseendpoint() {
  // @@protoc_insertion_point(field_release:fnv.soa.framework.SoaOnDemandProto.consumerbaseendpoint)
  clear_has_consumerbaseendpoint();
  return consumerbaseendpoint_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SoaOnDemandProto::set_allocated_consumerbaseendpoint(::std::string* consumerbaseendpoint) {
  if (consumerbaseendpoint != NULL) {
    set_has_consumerbaseendpoint();
  } else {
    clear_has_consumerbaseendpoint();
  }
  consumerbaseendpoint_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), consumerbaseendpoint);
  // @@protoc_insertion_point(field_set_allocated:fnv.soa.framework.SoaOnDemandProto.consumerbaseendpoint)
}

// optional int64 soahandle = 102;
inline bool SoaOnDemandProto::has_soahandle() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SoaOnDemandProto::set_has_soahandle() {
  _has_bits_[0] |= 0x00000008u;
}
inline void SoaOnDemandProto::clear_has_soahandle() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void SoaOnDemandProto::clear_soahandle() {
  soahandle_ = GOOGLE_LONGLONG(0);
  clear_has_soahandle();
}
inline ::google::protobuf::int64 SoaOnDemandProto::soahandle() const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.SoaOnDemandProto.soahandle)
  return soahandle_;
}
inline void SoaOnDemandProto::set_soahandle(::google::protobuf::int64 value) {
  set_has_soahandle();
  soahandle_ = value;
  // @@protoc_insertion_point(field_set:fnv.soa.framework.SoaOnDemandProto.soahandle)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace framework
}  // namespace soa
}  // namespace fnv

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_soa_5fon_5fdemand_5fproto_2eproto__INCLUDED
