// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: soa_message_proto.proto

#ifndef PROTOBUF_soa_5fmessage_5fproto_2eproto__INCLUDED
#define PROTOBUF_soa_5fmessage_5fproto_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_soa_5fmessage_5fproto_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsSoaMessageProtoImpl();
void InitDefaultsSoaMessageProto();
inline void InitDefaults() {
  InitDefaultsSoaMessageProto();
}
}  // namespace protobuf_soa_5fmessage_5fproto_2eproto
namespace fnv {
namespace soa {
namespace framework {
class SoaMessageProto;
class SoaMessageProtoDefaultTypeInternal;
extern SoaMessageProtoDefaultTypeInternal _SoaMessageProto_default_instance_;
}  // namespace framework
}  // namespace soa
}  // namespace fnv
namespace fnv {
namespace soa {
namespace framework {

enum SoaMessageProto_TransactionError {
  SoaMessageProto_TransactionError_NO_ERROR = 0,
  SoaMessageProto_TransactionError_GENERAL_ERROR = 1,
  SoaMessageProto_TransactionError_VERSION_MISMATCH = 2,
  SoaMessageProto_TransactionError_COMMAND_NOT_SUPPORTED = 3,
  SoaMessageProto_TransactionError_PROVIDER_CLOSED = 4,
  SoaMessageProto_TransactionError_PROVIDER_DISCONNECTED = 5
};
bool SoaMessageProto_TransactionError_IsValid(int value);
const SoaMessageProto_TransactionError SoaMessageProto_TransactionError_TransactionError_MIN = SoaMessageProto_TransactionError_NO_ERROR;
const SoaMessageProto_TransactionError SoaMessageProto_TransactionError_TransactionError_MAX = SoaMessageProto_TransactionError_PROVIDER_DISCONNECTED;
const int SoaMessageProto_TransactionError_TransactionError_ARRAYSIZE = SoaMessageProto_TransactionError_TransactionError_MAX + 1;

const ::google::protobuf::EnumDescriptor* SoaMessageProto_TransactionError_descriptor();
inline const ::std::string& SoaMessageProto_TransactionError_Name(SoaMessageProto_TransactionError value) {
  return ::google::protobuf::internal::NameOfEnum(
    SoaMessageProto_TransactionError_descriptor(), value);
}
inline bool SoaMessageProto_TransactionError_Parse(
    const ::std::string& name, SoaMessageProto_TransactionError* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SoaMessageProto_TransactionError>(
    SoaMessageProto_TransactionError_descriptor(), name, value);
}
// ===================================================================

class SoaMessageProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fnv.soa.framework.SoaMessageProto) */ {
 public:
  SoaMessageProto();
  virtual ~SoaMessageProto();

  SoaMessageProto(const SoaMessageProto& from);

  inline SoaMessageProto& operator=(const SoaMessageProto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SoaMessageProto(SoaMessageProto&& from) noexcept
    : SoaMessageProto() {
    *this = ::std::move(from);
  }

  inline SoaMessageProto& operator=(SoaMessageProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SoaMessageProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SoaMessageProto* internal_default_instance() {
    return reinterpret_cast<const SoaMessageProto*>(
               &_SoaMessageProto_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(SoaMessageProto* other);
  friend void swap(SoaMessageProto& a, SoaMessageProto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SoaMessageProto* New() const PROTOBUF_FINAL { return New(NULL); }

  SoaMessageProto* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SoaMessageProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef SoaMessageProto_TransactionError TransactionError;
  static const TransactionError NO_ERROR =
    SoaMessageProto_TransactionError_NO_ERROR;
  static const TransactionError GENERAL_ERROR =
    SoaMessageProto_TransactionError_GENERAL_ERROR;
  static const TransactionError VERSION_MISMATCH =
    SoaMessageProto_TransactionError_VERSION_MISMATCH;
  static const TransactionError COMMAND_NOT_SUPPORTED =
    SoaMessageProto_TransactionError_COMMAND_NOT_SUPPORTED;
  static const TransactionError PROVIDER_CLOSED =
    SoaMessageProto_TransactionError_PROVIDER_CLOSED;
  static const TransactionError PROVIDER_DISCONNECTED =
    SoaMessageProto_TransactionError_PROVIDER_DISCONNECTED;
  static inline bool TransactionError_IsValid(int value) {
    return SoaMessageProto_TransactionError_IsValid(value);
  }
  static const TransactionError TransactionError_MIN =
    SoaMessageProto_TransactionError_TransactionError_MIN;
  static const TransactionError TransactionError_MAX =
    SoaMessageProto_TransactionError_TransactionError_MAX;
  static const int TransactionError_ARRAYSIZE =
    SoaMessageProto_TransactionError_TransactionError_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  TransactionError_descriptor() {
    return SoaMessageProto_TransactionError_descriptor();
  }
  static inline const ::std::string& TransactionError_Name(TransactionError value) {
    return SoaMessageProto_TransactionError_Name(value);
  }
  static inline bool TransactionError_Parse(const ::std::string& name,
      TransactionError* value) {
    return SoaMessageProto_TransactionError_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional string serviceID = 1;
  bool has_serviceid() const;
  void clear_serviceid();
  static const int kServiceIDFieldNumber = 1;
  const ::std::string& serviceid() const;
  void set_serviceid(const ::std::string& value);
  #if LANG_CXX11
  void set_serviceid(::std::string&& value);
  #endif
  void set_serviceid(const char* value);
  void set_serviceid(const char* value, size_t size);
  ::std::string* mutable_serviceid();
  ::std::string* release_serviceid();
  void set_allocated_serviceid(::std::string* serviceid);

  // optional string commandID = 2;
  bool has_commandid() const;
  void clear_commandid();
  static const int kCommandIDFieldNumber = 2;
  const ::std::string& commandid() const;
  void set_commandid(const ::std::string& value);
  #if LANG_CXX11
  void set_commandid(::std::string&& value);
  #endif
  void set_commandid(const char* value);
  void set_commandid(const char* value, size_t size);
  ::std::string* mutable_commandid();
  ::std::string* release_commandid();
  void set_allocated_commandid(::std::string* commandid);

  // optional string serviceVersion = 3;
  bool has_serviceversion() const;
  void clear_serviceversion();
  static const int kServiceVersionFieldNumber = 3;
  const ::std::string& serviceversion() const;
  void set_serviceversion(const ::std::string& value);
  #if LANG_CXX11
  void set_serviceversion(::std::string&& value);
  #endif
  void set_serviceversion(const char* value);
  void set_serviceversion(const char* value, size_t size);
  ::std::string* mutable_serviceversion();
  ::std::string* release_serviceversion();
  void set_allocated_serviceversion(::std::string* serviceversion);

  // optional string transactionID = 4;
  bool has_transactionid() const;
  void clear_transactionid();
  static const int kTransactionIDFieldNumber = 4;
  const ::std::string& transactionid() const;
  void set_transactionid(const ::std::string& value);
  #if LANG_CXX11
  void set_transactionid(::std::string&& value);
  #endif
  void set_transactionid(const char* value);
  void set_transactionid(const char* value, size_t size);
  ::std::string* mutable_transactionid();
  ::std::string* release_transactionid();
  void set_allocated_transactionid(::std::string* transactionid);

  // optional string dataEndpoint = 5;
  bool has_dataendpoint() const;
  void clear_dataendpoint();
  static const int kDataEndpointFieldNumber = 5;
  const ::std::string& dataendpoint() const;
  void set_dataendpoint(const ::std::string& value);
  #if LANG_CXX11
  void set_dataendpoint(::std::string&& value);
  #endif
  void set_dataendpoint(const char* value);
  void set_dataendpoint(const char* value, size_t size);
  ::std::string* mutable_dataendpoint();
  ::std::string* release_dataendpoint();
  void set_allocated_dataendpoint(::std::string* dataendpoint);

  // optional string consumerEndpoint = 6;
  bool has_consumerendpoint() const;
  void clear_consumerendpoint();
  static const int kConsumerEndpointFieldNumber = 6;
  const ::std::string& consumerendpoint() const;
  void set_consumerendpoint(const ::std::string& value);
  #if LANG_CXX11
  void set_consumerendpoint(::std::string&& value);
  #endif
  void set_consumerendpoint(const char* value);
  void set_consumerendpoint(const char* value, size_t size);
  ::std::string* mutable_consumerendpoint();
  ::std::string* release_consumerendpoint();
  void set_allocated_consumerendpoint(::std::string* consumerendpoint);

  // optional bytes payload = 7;
  bool has_payload() const;
  void clear_payload();
  static const int kPayloadFieldNumber = 7;
  const ::std::string& payload() const;
  void set_payload(const ::std::string& value);
  #if LANG_CXX11
  void set_payload(::std::string&& value);
  #endif
  void set_payload(const char* value);
  void set_payload(const void* value, size_t size);
  ::std::string* mutable_payload();
  ::std::string* release_payload();
  void set_allocated_payload(::std::string* payload);

  // optional string transactionErrorDetailes = 9;
  bool has_transactionerrordetailes() const;
  void clear_transactionerrordetailes();
  static const int kTransactionErrorDetailesFieldNumber = 9;
  const ::std::string& transactionerrordetailes() const;
  void set_transactionerrordetailes(const ::std::string& value);
  #if LANG_CXX11
  void set_transactionerrordetailes(::std::string&& value);
  #endif
  void set_transactionerrordetailes(const char* value);
  void set_transactionerrordetailes(const char* value, size_t size);
  ::std::string* mutable_transactionerrordetailes();
  ::std::string* release_transactionerrordetailes();
  void set_allocated_transactionerrordetailes(::std::string* transactionerrordetailes);

  // optional string sender_ecu_id = 10;
  bool has_sender_ecu_id() const;
  void clear_sender_ecu_id();
  static const int kSenderEcuIdFieldNumber = 10;
  const ::std::string& sender_ecu_id() const;
  void set_sender_ecu_id(const ::std::string& value);
  #if LANG_CXX11
  void set_sender_ecu_id(::std::string&& value);
  #endif
  void set_sender_ecu_id(const char* value);
  void set_sender_ecu_id(const char* value, size_t size);
  ::std::string* mutable_sender_ecu_id();
  ::std::string* release_sender_ecu_id();
  void set_allocated_sender_ecu_id(::std::string* sender_ecu_id);

  // optional string sender_uid = 11;
  bool has_sender_uid() const;
  void clear_sender_uid();
  static const int kSenderUidFieldNumber = 11;
  const ::std::string& sender_uid() const;
  void set_sender_uid(const ::std::string& value);
  #if LANG_CXX11
  void set_sender_uid(::std::string&& value);
  #endif
  void set_sender_uid(const char* value);
  void set_sender_uid(const char* value, size_t size);
  ::std::string* mutable_sender_uid();
  ::std::string* release_sender_uid();
  void set_allocated_sender_uid(::std::string* sender_uid);

  // optional bytes context = 101;
  bool has_context() const;
  void clear_context();
  static const int kContextFieldNumber = 101;
  const ::std::string& context() const;
  void set_context(const ::std::string& value);
  #if LANG_CXX11
  void set_context(::std::string&& value);
  #endif
  void set_context(const char* value);
  void set_context(const void* value, size_t size);
  ::std::string* mutable_context();
  ::std::string* release_context();
  void set_allocated_context(::std::string* context);

  // optional .fnv.soa.framework.SoaMessageProto.TransactionError transactionError = 8 [default = NO_ERROR];
  bool has_transactionerror() const;
  void clear_transactionerror();
  static const int kTransactionErrorFieldNumber = 8;
  ::fnv::soa::framework::SoaMessageProto_TransactionError transactionerror() const;
  void set_transactionerror(::fnv::soa::framework::SoaMessageProto_TransactionError value);

  // @@protoc_insertion_point(class_scope:fnv.soa.framework.SoaMessageProto)
 private:
  void set_has_serviceid();
  void clear_has_serviceid();
  void set_has_commandid();
  void clear_has_commandid();
  void set_has_serviceversion();
  void clear_has_serviceversion();
  void set_has_transactionid();
  void clear_has_transactionid();
  void set_has_dataendpoint();
  void clear_has_dataendpoint();
  void set_has_consumerendpoint();
  void clear_has_consumerendpoint();
  void set_has_payload();
  void clear_has_payload();
  void set_has_transactionerror();
  void clear_has_transactionerror();
  void set_has_transactionerrordetailes();
  void clear_has_transactionerrordetailes();
  void set_has_sender_ecu_id();
  void clear_has_sender_ecu_id();
  void set_has_sender_uid();
  void clear_has_sender_uid();
  void set_has_context();
  void clear_has_context();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr serviceid_;
  ::google::protobuf::internal::ArenaStringPtr commandid_;
  ::google::protobuf::internal::ArenaStringPtr serviceversion_;
  ::google::protobuf::internal::ArenaStringPtr transactionid_;
  ::google::protobuf::internal::ArenaStringPtr dataendpoint_;
  ::google::protobuf::internal::ArenaStringPtr consumerendpoint_;
  ::google::protobuf::internal::ArenaStringPtr payload_;
  ::google::protobuf::internal::ArenaStringPtr transactionerrordetailes_;
  ::google::protobuf::internal::ArenaStringPtr sender_ecu_id_;
  ::google::protobuf::internal::ArenaStringPtr sender_uid_;
  ::google::protobuf::internal::ArenaStringPtr context_;
  int transactionerror_;
  friend struct ::protobuf_soa_5fmessage_5fproto_2eproto::TableStruct;
  friend void ::protobuf_soa_5fmessage_5fproto_2eproto::InitDefaultsSoaMessageProtoImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SoaMessageProto

// optional string serviceID = 1;
inline bool SoaMessageProto::has_serviceid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SoaMessageProto::set_has_serviceid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SoaMessageProto::clear_has_serviceid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SoaMessageProto::clear_serviceid() {
  serviceid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_serviceid();
}
inline const ::std::string& SoaMessageProto::serviceid() const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.SoaMessageProto.serviceID)
  return serviceid_.GetNoArena();
}
inline void SoaMessageProto::set_serviceid(const ::std::string& value) {
  set_has_serviceid();
  serviceid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fnv.soa.framework.SoaMessageProto.serviceID)
}
#if LANG_CXX11
inline void SoaMessageProto::set_serviceid(::std::string&& value) {
  set_has_serviceid();
  serviceid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fnv.soa.framework.SoaMessageProto.serviceID)
}
#endif
inline void SoaMessageProto::set_serviceid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_serviceid();
  serviceid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fnv.soa.framework.SoaMessageProto.serviceID)
}
inline void SoaMessageProto::set_serviceid(const char* value, size_t size) {
  set_has_serviceid();
  serviceid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fnv.soa.framework.SoaMessageProto.serviceID)
}
inline ::std::string* SoaMessageProto::mutable_serviceid() {
  set_has_serviceid();
  // @@protoc_insertion_point(field_mutable:fnv.soa.framework.SoaMessageProto.serviceID)
  return serviceid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SoaMessageProto::release_serviceid() {
  // @@protoc_insertion_point(field_release:fnv.soa.framework.SoaMessageProto.serviceID)
  clear_has_serviceid();
  return serviceid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SoaMessageProto::set_allocated_serviceid(::std::string* serviceid) {
  if (serviceid != NULL) {
    set_has_serviceid();
  } else {
    clear_has_serviceid();
  }
  serviceid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), serviceid);
  // @@protoc_insertion_point(field_set_allocated:fnv.soa.framework.SoaMessageProto.serviceID)
}

// optional string commandID = 2;
inline bool SoaMessageProto::has_commandid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SoaMessageProto::set_has_commandid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SoaMessageProto::clear_has_commandid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SoaMessageProto::clear_commandid() {
  commandid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_commandid();
}
inline const ::std::string& SoaMessageProto::commandid() const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.SoaMessageProto.commandID)
  return commandid_.GetNoArena();
}
inline void SoaMessageProto::set_commandid(const ::std::string& value) {
  set_has_commandid();
  commandid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fnv.soa.framework.SoaMessageProto.commandID)
}
#if LANG_CXX11
inline void SoaMessageProto::set_commandid(::std::string&& value) {
  set_has_commandid();
  commandid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fnv.soa.framework.SoaMessageProto.commandID)
}
#endif
inline void SoaMessageProto::set_commandid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_commandid();
  commandid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fnv.soa.framework.SoaMessageProto.commandID)
}
inline void SoaMessageProto::set_commandid(const char* value, size_t size) {
  set_has_commandid();
  commandid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fnv.soa.framework.SoaMessageProto.commandID)
}
inline ::std::string* SoaMessageProto::mutable_commandid() {
  set_has_commandid();
  // @@protoc_insertion_point(field_mutable:fnv.soa.framework.SoaMessageProto.commandID)
  return commandid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SoaMessageProto::release_commandid() {
  // @@protoc_insertion_point(field_release:fnv.soa.framework.SoaMessageProto.commandID)
  clear_has_commandid();
  return commandid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SoaMessageProto::set_allocated_commandid(::std::string* commandid) {
  if (commandid != NULL) {
    set_has_commandid();
  } else {
    clear_has_commandid();
  }
  commandid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), commandid);
  // @@protoc_insertion_point(field_set_allocated:fnv.soa.framework.SoaMessageProto.commandID)
}

// optional string serviceVersion = 3;
inline bool SoaMessageProto::has_serviceversion() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SoaMessageProto::set_has_serviceversion() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SoaMessageProto::clear_has_serviceversion() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SoaMessageProto::clear_serviceversion() {
  serviceversion_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_serviceversion();
}
inline const ::std::string& SoaMessageProto::serviceversion() const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.SoaMessageProto.serviceVersion)
  return serviceversion_.GetNoArena();
}
inline void SoaMessageProto::set_serviceversion(const ::std::string& value) {
  set_has_serviceversion();
  serviceversion_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fnv.soa.framework.SoaMessageProto.serviceVersion)
}
#if LANG_CXX11
inline void SoaMessageProto::set_serviceversion(::std::string&& value) {
  set_has_serviceversion();
  serviceversion_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fnv.soa.framework.SoaMessageProto.serviceVersion)
}
#endif
inline void SoaMessageProto::set_serviceversion(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_serviceversion();
  serviceversion_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fnv.soa.framework.SoaMessageProto.serviceVersion)
}
inline void SoaMessageProto::set_serviceversion(const char* value, size_t size) {
  set_has_serviceversion();
  serviceversion_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fnv.soa.framework.SoaMessageProto.serviceVersion)
}
inline ::std::string* SoaMessageProto::mutable_serviceversion() {
  set_has_serviceversion();
  // @@protoc_insertion_point(field_mutable:fnv.soa.framework.SoaMessageProto.serviceVersion)
  return serviceversion_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SoaMessageProto::release_serviceversion() {
  // @@protoc_insertion_point(field_release:fnv.soa.framework.SoaMessageProto.serviceVersion)
  clear_has_serviceversion();
  return serviceversion_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SoaMessageProto::set_allocated_serviceversion(::std::string* serviceversion) {
  if (serviceversion != NULL) {
    set_has_serviceversion();
  } else {
    clear_has_serviceversion();
  }
  serviceversion_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), serviceversion);
  // @@protoc_insertion_point(field_set_allocated:fnv.soa.framework.SoaMessageProto.serviceVersion)
}

// optional string transactionID = 4;
inline bool SoaMessageProto::has_transactionid() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SoaMessageProto::set_has_transactionid() {
  _has_bits_[0] |= 0x00000008u;
}
inline void SoaMessageProto::clear_has_transactionid() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void SoaMessageProto::clear_transactionid() {
  transactionid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_transactionid();
}
inline const ::std::string& SoaMessageProto::transactionid() const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.SoaMessageProto.transactionID)
  return transactionid_.GetNoArena();
}
inline void SoaMessageProto::set_transactionid(const ::std::string& value) {
  set_has_transactionid();
  transactionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fnv.soa.framework.SoaMessageProto.transactionID)
}
#if LANG_CXX11
inline void SoaMessageProto::set_transactionid(::std::string&& value) {
  set_has_transactionid();
  transactionid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fnv.soa.framework.SoaMessageProto.transactionID)
}
#endif
inline void SoaMessageProto::set_transactionid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_transactionid();
  transactionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fnv.soa.framework.SoaMessageProto.transactionID)
}
inline void SoaMessageProto::set_transactionid(const char* value, size_t size) {
  set_has_transactionid();
  transactionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fnv.soa.framework.SoaMessageProto.transactionID)
}
inline ::std::string* SoaMessageProto::mutable_transactionid() {
  set_has_transactionid();
  // @@protoc_insertion_point(field_mutable:fnv.soa.framework.SoaMessageProto.transactionID)
  return transactionid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SoaMessageProto::release_transactionid() {
  // @@protoc_insertion_point(field_release:fnv.soa.framework.SoaMessageProto.transactionID)
  clear_has_transactionid();
  return transactionid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SoaMessageProto::set_allocated_transactionid(::std::string* transactionid) {
  if (transactionid != NULL) {
    set_has_transactionid();
  } else {
    clear_has_transactionid();
  }
  transactionid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), transactionid);
  // @@protoc_insertion_point(field_set_allocated:fnv.soa.framework.SoaMessageProto.transactionID)
}

// optional string dataEndpoint = 5;
inline bool SoaMessageProto::has_dataendpoint() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void SoaMessageProto::set_has_dataendpoint() {
  _has_bits_[0] |= 0x00000010u;
}
inline void SoaMessageProto::clear_has_dataendpoint() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void SoaMessageProto::clear_dataendpoint() {
  dataendpoint_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_dataendpoint();
}
inline const ::std::string& SoaMessageProto::dataendpoint() const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.SoaMessageProto.dataEndpoint)
  return dataendpoint_.GetNoArena();
}
inline void SoaMessageProto::set_dataendpoint(const ::std::string& value) {
  set_has_dataendpoint();
  dataendpoint_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fnv.soa.framework.SoaMessageProto.dataEndpoint)
}
#if LANG_CXX11
inline void SoaMessageProto::set_dataendpoint(::std::string&& value) {
  set_has_dataendpoint();
  dataendpoint_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fnv.soa.framework.SoaMessageProto.dataEndpoint)
}
#endif
inline void SoaMessageProto::set_dataendpoint(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_dataendpoint();
  dataendpoint_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fnv.soa.framework.SoaMessageProto.dataEndpoint)
}
inline void SoaMessageProto::set_dataendpoint(const char* value, size_t size) {
  set_has_dataendpoint();
  dataendpoint_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fnv.soa.framework.SoaMessageProto.dataEndpoint)
}
inline ::std::string* SoaMessageProto::mutable_dataendpoint() {
  set_has_dataendpoint();
  // @@protoc_insertion_point(field_mutable:fnv.soa.framework.SoaMessageProto.dataEndpoint)
  return dataendpoint_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SoaMessageProto::release_dataendpoint() {
  // @@protoc_insertion_point(field_release:fnv.soa.framework.SoaMessageProto.dataEndpoint)
  clear_has_dataendpoint();
  return dataendpoint_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SoaMessageProto::set_allocated_dataendpoint(::std::string* dataendpoint) {
  if (dataendpoint != NULL) {
    set_has_dataendpoint();
  } else {
    clear_has_dataendpoint();
  }
  dataendpoint_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), dataendpoint);
  // @@protoc_insertion_point(field_set_allocated:fnv.soa.framework.SoaMessageProto.dataEndpoint)
}

// optional string consumerEndpoint = 6;
inline bool SoaMessageProto::has_consumerendpoint() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void SoaMessageProto::set_has_consumerendpoint() {
  _has_bits_[0] |= 0x00000020u;
}
inline void SoaMessageProto::clear_has_consumerendpoint() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void SoaMessageProto::clear_consumerendpoint() {
  consumerendpoint_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_consumerendpoint();
}
inline const ::std::string& SoaMessageProto::consumerendpoint() const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.SoaMessageProto.consumerEndpoint)
  return consumerendpoint_.GetNoArena();
}
inline void SoaMessageProto::set_consumerendpoint(const ::std::string& value) {
  set_has_consumerendpoint();
  consumerendpoint_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fnv.soa.framework.SoaMessageProto.consumerEndpoint)
}
#if LANG_CXX11
inline void SoaMessageProto::set_consumerendpoint(::std::string&& value) {
  set_has_consumerendpoint();
  consumerendpoint_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fnv.soa.framework.SoaMessageProto.consumerEndpoint)
}
#endif
inline void SoaMessageProto::set_consumerendpoint(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_consumerendpoint();
  consumerendpoint_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fnv.soa.framework.SoaMessageProto.consumerEndpoint)
}
inline void SoaMessageProto::set_consumerendpoint(const char* value, size_t size) {
  set_has_consumerendpoint();
  consumerendpoint_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fnv.soa.framework.SoaMessageProto.consumerEndpoint)
}
inline ::std::string* SoaMessageProto::mutable_consumerendpoint() {
  set_has_consumerendpoint();
  // @@protoc_insertion_point(field_mutable:fnv.soa.framework.SoaMessageProto.consumerEndpoint)
  return consumerendpoint_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SoaMessageProto::release_consumerendpoint() {
  // @@protoc_insertion_point(field_release:fnv.soa.framework.SoaMessageProto.consumerEndpoint)
  clear_has_consumerendpoint();
  return consumerendpoint_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SoaMessageProto::set_allocated_consumerendpoint(::std::string* consumerendpoint) {
  if (consumerendpoint != NULL) {
    set_has_consumerendpoint();
  } else {
    clear_has_consumerendpoint();
  }
  consumerendpoint_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), consumerendpoint);
  // @@protoc_insertion_point(field_set_allocated:fnv.soa.framework.SoaMessageProto.consumerEndpoint)
}

// optional bytes payload = 7;
inline bool SoaMessageProto::has_payload() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void SoaMessageProto::set_has_payload() {
  _has_bits_[0] |= 0x00000040u;
}
inline void SoaMessageProto::clear_has_payload() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void SoaMessageProto::clear_payload() {
  payload_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_payload();
}
inline const ::std::string& SoaMessageProto::payload() const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.SoaMessageProto.payload)
  return payload_.GetNoArena();
}
inline void SoaMessageProto::set_payload(const ::std::string& value) {
  set_has_payload();
  payload_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fnv.soa.framework.SoaMessageProto.payload)
}
#if LANG_CXX11
inline void SoaMessageProto::set_payload(::std::string&& value) {
  set_has_payload();
  payload_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fnv.soa.framework.SoaMessageProto.payload)
}
#endif
inline void SoaMessageProto::set_payload(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_payload();
  payload_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fnv.soa.framework.SoaMessageProto.payload)
}
inline void SoaMessageProto::set_payload(const void* value, size_t size) {
  set_has_payload();
  payload_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fnv.soa.framework.SoaMessageProto.payload)
}
inline ::std::string* SoaMessageProto::mutable_payload() {
  set_has_payload();
  // @@protoc_insertion_point(field_mutable:fnv.soa.framework.SoaMessageProto.payload)
  return payload_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SoaMessageProto::release_payload() {
  // @@protoc_insertion_point(field_release:fnv.soa.framework.SoaMessageProto.payload)
  clear_has_payload();
  return payload_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SoaMessageProto::set_allocated_payload(::std::string* payload) {
  if (payload != NULL) {
    set_has_payload();
  } else {
    clear_has_payload();
  }
  payload_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), payload);
  // @@protoc_insertion_point(field_set_allocated:fnv.soa.framework.SoaMessageProto.payload)
}

// optional .fnv.soa.framework.SoaMessageProto.TransactionError transactionError = 8 [default = NO_ERROR];
inline bool SoaMessageProto::has_transactionerror() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void SoaMessageProto::set_has_transactionerror() {
  _has_bits_[0] |= 0x00000800u;
}
inline void SoaMessageProto::clear_has_transactionerror() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void SoaMessageProto::clear_transactionerror() {
  transactionerror_ = 0;
  clear_has_transactionerror();
}
inline ::fnv::soa::framework::SoaMessageProto_TransactionError SoaMessageProto::transactionerror() const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.SoaMessageProto.transactionError)
  return static_cast< ::fnv::soa::framework::SoaMessageProto_TransactionError >(transactionerror_);
}
inline void SoaMessageProto::set_transactionerror(::fnv::soa::framework::SoaMessageProto_TransactionError value) {
  assert(::fnv::soa::framework::SoaMessageProto_TransactionError_IsValid(value));
  set_has_transactionerror();
  transactionerror_ = value;
  // @@protoc_insertion_point(field_set:fnv.soa.framework.SoaMessageProto.transactionError)
}

// optional string transactionErrorDetailes = 9;
inline bool SoaMessageProto::has_transactionerrordetailes() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void SoaMessageProto::set_has_transactionerrordetailes() {
  _has_bits_[0] |= 0x00000080u;
}
inline void SoaMessageProto::clear_has_transactionerrordetailes() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void SoaMessageProto::clear_transactionerrordetailes() {
  transactionerrordetailes_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_transactionerrordetailes();
}
inline const ::std::string& SoaMessageProto::transactionerrordetailes() const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.SoaMessageProto.transactionErrorDetailes)
  return transactionerrordetailes_.GetNoArena();
}
inline void SoaMessageProto::set_transactionerrordetailes(const ::std::string& value) {
  set_has_transactionerrordetailes();
  transactionerrordetailes_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fnv.soa.framework.SoaMessageProto.transactionErrorDetailes)
}
#if LANG_CXX11
inline void SoaMessageProto::set_transactionerrordetailes(::std::string&& value) {
  set_has_transactionerrordetailes();
  transactionerrordetailes_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fnv.soa.framework.SoaMessageProto.transactionErrorDetailes)
}
#endif
inline void SoaMessageProto::set_transactionerrordetailes(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_transactionerrordetailes();
  transactionerrordetailes_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fnv.soa.framework.SoaMessageProto.transactionErrorDetailes)
}
inline void SoaMessageProto::set_transactionerrordetailes(const char* value, size_t size) {
  set_has_transactionerrordetailes();
  transactionerrordetailes_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fnv.soa.framework.SoaMessageProto.transactionErrorDetailes)
}
inline ::std::string* SoaMessageProto::mutable_transactionerrordetailes() {
  set_has_transactionerrordetailes();
  // @@protoc_insertion_point(field_mutable:fnv.soa.framework.SoaMessageProto.transactionErrorDetailes)
  return transactionerrordetailes_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SoaMessageProto::release_transactionerrordetailes() {
  // @@protoc_insertion_point(field_release:fnv.soa.framework.SoaMessageProto.transactionErrorDetailes)
  clear_has_transactionerrordetailes();
  return transactionerrordetailes_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SoaMessageProto::set_allocated_transactionerrordetailes(::std::string* transactionerrordetailes) {
  if (transactionerrordetailes != NULL) {
    set_has_transactionerrordetailes();
  } else {
    clear_has_transactionerrordetailes();
  }
  transactionerrordetailes_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), transactionerrordetailes);
  // @@protoc_insertion_point(field_set_allocated:fnv.soa.framework.SoaMessageProto.transactionErrorDetailes)
}

// optional string sender_ecu_id = 10;
inline bool SoaMessageProto::has_sender_ecu_id() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void SoaMessageProto::set_has_sender_ecu_id() {
  _has_bits_[0] |= 0x00000100u;
}
inline void SoaMessageProto::clear_has_sender_ecu_id() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void SoaMessageProto::clear_sender_ecu_id() {
  sender_ecu_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_sender_ecu_id();
}
inline const ::std::string& SoaMessageProto::sender_ecu_id() const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.SoaMessageProto.sender_ecu_id)
  return sender_ecu_id_.GetNoArena();
}
inline void SoaMessageProto::set_sender_ecu_id(const ::std::string& value) {
  set_has_sender_ecu_id();
  sender_ecu_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fnv.soa.framework.SoaMessageProto.sender_ecu_id)
}
#if LANG_CXX11
inline void SoaMessageProto::set_sender_ecu_id(::std::string&& value) {
  set_has_sender_ecu_id();
  sender_ecu_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fnv.soa.framework.SoaMessageProto.sender_ecu_id)
}
#endif
inline void SoaMessageProto::set_sender_ecu_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_sender_ecu_id();
  sender_ecu_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fnv.soa.framework.SoaMessageProto.sender_ecu_id)
}
inline void SoaMessageProto::set_sender_ecu_id(const char* value, size_t size) {
  set_has_sender_ecu_id();
  sender_ecu_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fnv.soa.framework.SoaMessageProto.sender_ecu_id)
}
inline ::std::string* SoaMessageProto::mutable_sender_ecu_id() {
  set_has_sender_ecu_id();
  // @@protoc_insertion_point(field_mutable:fnv.soa.framework.SoaMessageProto.sender_ecu_id)
  return sender_ecu_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SoaMessageProto::release_sender_ecu_id() {
  // @@protoc_insertion_point(field_release:fnv.soa.framework.SoaMessageProto.sender_ecu_id)
  clear_has_sender_ecu_id();
  return sender_ecu_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SoaMessageProto::set_allocated_sender_ecu_id(::std::string* sender_ecu_id) {
  if (sender_ecu_id != NULL) {
    set_has_sender_ecu_id();
  } else {
    clear_has_sender_ecu_id();
  }
  sender_ecu_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sender_ecu_id);
  // @@protoc_insertion_point(field_set_allocated:fnv.soa.framework.SoaMessageProto.sender_ecu_id)
}

// optional string sender_uid = 11;
inline bool SoaMessageProto::has_sender_uid() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void SoaMessageProto::set_has_sender_uid() {
  _has_bits_[0] |= 0x00000200u;
}
inline void SoaMessageProto::clear_has_sender_uid() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void SoaMessageProto::clear_sender_uid() {
  sender_uid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_sender_uid();
}
inline const ::std::string& SoaMessageProto::sender_uid() const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.SoaMessageProto.sender_uid)
  return sender_uid_.GetNoArena();
}
inline void SoaMessageProto::set_sender_uid(const ::std::string& value) {
  set_has_sender_uid();
  sender_uid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fnv.soa.framework.SoaMessageProto.sender_uid)
}
#if LANG_CXX11
inline void SoaMessageProto::set_sender_uid(::std::string&& value) {
  set_has_sender_uid();
  sender_uid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fnv.soa.framework.SoaMessageProto.sender_uid)
}
#endif
inline void SoaMessageProto::set_sender_uid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_sender_uid();
  sender_uid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fnv.soa.framework.SoaMessageProto.sender_uid)
}
inline void SoaMessageProto::set_sender_uid(const char* value, size_t size) {
  set_has_sender_uid();
  sender_uid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fnv.soa.framework.SoaMessageProto.sender_uid)
}
inline ::std::string* SoaMessageProto::mutable_sender_uid() {
  set_has_sender_uid();
  // @@protoc_insertion_point(field_mutable:fnv.soa.framework.SoaMessageProto.sender_uid)
  return sender_uid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SoaMessageProto::release_sender_uid() {
  // @@protoc_insertion_point(field_release:fnv.soa.framework.SoaMessageProto.sender_uid)
  clear_has_sender_uid();
  return sender_uid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SoaMessageProto::set_allocated_sender_uid(::std::string* sender_uid) {
  if (sender_uid != NULL) {
    set_has_sender_uid();
  } else {
    clear_has_sender_uid();
  }
  sender_uid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sender_uid);
  // @@protoc_insertion_point(field_set_allocated:fnv.soa.framework.SoaMessageProto.sender_uid)
}

// optional bytes context = 101;
inline bool SoaMessageProto::has_context() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void SoaMessageProto::set_has_context() {
  _has_bits_[0] |= 0x00000400u;
}
inline void SoaMessageProto::clear_has_context() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void SoaMessageProto::clear_context() {
  context_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_context();
}
inline const ::std::string& SoaMessageProto::context() const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.SoaMessageProto.context)
  return context_.GetNoArena();
}
inline void SoaMessageProto::set_context(const ::std::string& value) {
  set_has_context();
  context_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fnv.soa.framework.SoaMessageProto.context)
}
#if LANG_CXX11
inline void SoaMessageProto::set_context(::std::string&& value) {
  set_has_context();
  context_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fnv.soa.framework.SoaMessageProto.context)
}
#endif
inline void SoaMessageProto::set_context(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_context();
  context_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fnv.soa.framework.SoaMessageProto.context)
}
inline void SoaMessageProto::set_context(const void* value, size_t size) {
  set_has_context();
  context_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fnv.soa.framework.SoaMessageProto.context)
}
inline ::std::string* SoaMessageProto::mutable_context() {
  set_has_context();
  // @@protoc_insertion_point(field_mutable:fnv.soa.framework.SoaMessageProto.context)
  return context_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SoaMessageProto::release_context() {
  // @@protoc_insertion_point(field_release:fnv.soa.framework.SoaMessageProto.context)
  clear_has_context();
  return context_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SoaMessageProto::set_allocated_context(::std::string* context) {
  if (context != NULL) {
    set_has_context();
  } else {
    clear_has_context();
  }
  context_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), context);
  // @@protoc_insertion_point(field_set_allocated:fnv.soa.framework.SoaMessageProto.context)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace framework
}  // namespace soa
}  // namespace fnv

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::fnv::soa::framework::SoaMessageProto_TransactionError> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::fnv::soa::framework::SoaMessageProto_TransactionError>() {
  return ::fnv::soa::framework::SoaMessageProto_TransactionError_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_soa_5fmessage_5fproto_2eproto__INCLUDED
