/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: soa_lwt.proto */

#ifndef PROTOBUF_C_soa_5flwt_2eproto__INCLUDED
#define PROTOBUF_C_soa_5flwt_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Fnv__Soa__Framework__SoaLwtProto Fnv__Soa__Framework__SoaLwtProto;


/* --- enums --- */


/* --- messages --- */

/*
 **
 * @fnv_proto
 * Contains payload definition for a SOA Last Will and Testament message
 * @fnv_topic SERVICES/LWT
 * @fnv_scope ECG_INTERNAL
 * @fnv_api_source INTERNAL
 * @fnv_message_version 1.0
 */
struct  _Fnv__Soa__Framework__SoaLwtProto
{
  ProtobufCMessage base;
  /*
   * Client Id
   */
  char *clientid;
  /*
   * ECU Id
   */
  char *ecuid;
  /*
   * Process Id on the ECU
   */
  protobuf_c_boolean has_processid;
  int32_t processid;
};
#define FNV__SOA__FRAMEWORK__SOA_LWT_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fnv__soa__framework__soa_lwt_proto__descriptor) \
    , NULL, NULL, 0, -1 }


/* Fnv__Soa__Framework__SoaLwtProto methods */
void   fnv__soa__framework__soa_lwt_proto__init
                     (Fnv__Soa__Framework__SoaLwtProto         *message);
size_t fnv__soa__framework__soa_lwt_proto__get_packed_size
                     (const Fnv__Soa__Framework__SoaLwtProto   *message);
size_t fnv__soa__framework__soa_lwt_proto__pack
                     (const Fnv__Soa__Framework__SoaLwtProto   *message,
                      uint8_t             *out);
size_t fnv__soa__framework__soa_lwt_proto__pack_to_buffer
                     (const Fnv__Soa__Framework__SoaLwtProto   *message,
                      ProtobufCBuffer     *buffer);
Fnv__Soa__Framework__SoaLwtProto *
       fnv__soa__framework__soa_lwt_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fnv__soa__framework__soa_lwt_proto__free_unpacked
                     (Fnv__Soa__Framework__SoaLwtProto *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Fnv__Soa__Framework__SoaLwtProto_Closure)
                 (const Fnv__Soa__Framework__SoaLwtProto *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor fnv__soa__framework__soa_lwt_proto__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_soa_5flwt_2eproto__INCLUDED */
