/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: soa_service_status.proto */

#ifndef PROTOBUF_C_soa_5fservice_5fstatus_2eproto__INCLUDED
#define PROTOBUF_C_soa_5fservice_5fstatus_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif




/* --- enums --- */

/*
 * Lifecycle service status enum. This service status can only be controlled by priviledged componenets like ALM
 * Interfaces: "updateServiceStatus".
 */
typedef enum _Fnv__Soa__Framework__Protobuf__ServiceStatus__Values {
  /*
   * Service is not available. There is no service records in the database
   */
  FNV__SOA__FRAMEWORK__PROTOBUF__SERVICE_STATUS__VALUES__NOT_AVAILABLE = 0,
  /*
   * service is temporarily cannot be started for reasons:
   *      1. The app is being updated
   *      2. The app is about to be uninstalled. If uninstall is canceled the status will be changed to "AVAILABLE"
   */
  FNV__SOA__FRAMEWORK__PROTOBUF__SERVICE_STATUS__VALUES__TEMPORARILY_NOT_AVAILABLE = 1,
  /*
   * Service is available and can be started.
   */
  FNV__SOA__FRAMEWORK__PROTOBUF__SERVICE_STATUS__VALUES__AVAILABLE = 2,
  /*
   * Service is active and can be accessed by service consumers
   */
  FNV__SOA__FRAMEWORK__PROTOBUF__SERVICE_STATUS__VALUES__RUNNING = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(FNV__SOA__FRAMEWORK__PROTOBUF__SERVICE_STATUS__VALUES)
} Fnv__Soa__Framework__Protobuf__ServiceStatus__Values;

/* --- messages --- */

/* --- per-message closures --- */


/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    fnv__soa__framework__protobuf__service_status__values__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_soa_5fservice_5fstatus_2eproto__INCLUDED */
