/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: SoaGatewayFesn.proto */

#ifndef PROTOBUF_C_SoaGatewayFesn_2eproto__INCLUDED
#define PROTOBUF_C_SoaGatewayFesn_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Fnv__Soa__Gateway__SoaGatewayFesn Fnv__Soa__Gateway__SoaGatewayFesn;


/* --- enums --- */


/* --- messages --- */

/*
 **
 * @fnv_proto
 * Reads the FESN from the local ECU the Gateway is running on and sends it to the ECG 
 * @fnv_topic SERVICES/DATA/GATEWAY/ESN
 * @fnv_scope ECG_INTERNAL
 * @fnv_api_source INTERNAL
 * @fnv_message_version 1.0
 */
struct  _Fnv__Soa__Gateway__SoaGatewayFesn
{
  ProtobufCMessage base;
  /*
   * ECU name e.g. TCU, SYNC. Same name as what is provided in the CommonName field of the TLS Certificat
   */
  char *ecuname;
  /*
   * Ford ESN
   */
  char *esn;
};
#define FNV__SOA__GATEWAY__SOA_GATEWAY_FESN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fnv__soa__gateway__soa_gateway_fesn__descriptor) \
    , NULL, NULL }


/* Fnv__Soa__Gateway__SoaGatewayFesn methods */
void   fnv__soa__gateway__soa_gateway_fesn__init
                     (Fnv__Soa__Gateway__SoaGatewayFesn         *message);
size_t fnv__soa__gateway__soa_gateway_fesn__get_packed_size
                     (const Fnv__Soa__Gateway__SoaGatewayFesn   *message);
size_t fnv__soa__gateway__soa_gateway_fesn__pack
                     (const Fnv__Soa__Gateway__SoaGatewayFesn   *message,
                      uint8_t             *out);
size_t fnv__soa__gateway__soa_gateway_fesn__pack_to_buffer
                     (const Fnv__Soa__Gateway__SoaGatewayFesn   *message,
                      ProtobufCBuffer     *buffer);
Fnv__Soa__Gateway__SoaGatewayFesn *
       fnv__soa__gateway__soa_gateway_fesn__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fnv__soa__gateway__soa_gateway_fesn__free_unpacked
                     (Fnv__Soa__Gateway__SoaGatewayFesn *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Fnv__Soa__Gateway__SoaGatewayFesn_Closure)
                 (const Fnv__Soa__Gateway__SoaGatewayFesn *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor fnv__soa__gateway__soa_gateway_fesn__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_SoaGatewayFesn_2eproto__INCLUDED */
