/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: SoaGatewayConnectionState.proto */

#ifndef PROTOBUF_C_SoaGatewayConnectionState_2eproto__INCLUDED
#define PROTOBUF_C_SoaGatewayConnectionState_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Fnv__Soa__Gateway__SoaGatewayConnectionState Fnv__Soa__Gateway__SoaGatewayConnectionState;


/* --- enums --- */

typedef enum _Fnv__Soa__Gateway__SoaGatewayConnectionState__ConnectionState {
  FNV__SOA__GATEWAY__SOA_GATEWAY_CONNECTION_STATE__CONNECTION_STATE__CONNECTED = 0,
  FNV__SOA__GATEWAY__SOA_GATEWAY_CONNECTION_STATE__CONNECTION_STATE__DISCONNECTED = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(FNV__SOA__GATEWAY__SOA_GATEWAY_CONNECTION_STATE__CONNECTION_STATE)
} Fnv__Soa__Gateway__SoaGatewayConnectionState__ConnectionState;

/* --- messages --- */

/*
 **
 * @fnv_proto
 * Defines the connection information sent by the SOA Gateway when it connects to the ECG 
 * @fnv_topic SERVICES/DATA/GATEWAY/CONNECTIONSTATE
 * @fnv_scope ECG_INTERNAL
 * @fnv_api_source INTERNAL
 * @fnv_message_version 1.0
 */
struct  _Fnv__Soa__Gateway__SoaGatewayConnectionState
{
  ProtobufCMessage base;
  /*
   * The connection state
   */
  Fnv__Soa__Gateway__SoaGatewayConnectionState__ConnectionState connectionstate;
  /*
   * ECU name e.g. TCU, SYNC. Same name as what is provided in the CommonName field of the TLS Certificat
   */
  char *ecuname;
  /*
   * IP address
   */
  char *ipaddress;
  /*
   * Number of connection retries since previous report
   */
  protobuf_c_boolean has_retrycount;
  int32_t retrycount;
};
#define FNV__SOA__GATEWAY__SOA_GATEWAY_CONNECTION_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fnv__soa__gateway__soa_gateway_connection_state__descriptor) \
    , FNV__SOA__GATEWAY__SOA_GATEWAY_CONNECTION_STATE__CONNECTION_STATE__CONNECTED, NULL, NULL, 0, 0 }


/* Fnv__Soa__Gateway__SoaGatewayConnectionState methods */
void   fnv__soa__gateway__soa_gateway_connection_state__init
                     (Fnv__Soa__Gateway__SoaGatewayConnectionState         *message);
size_t fnv__soa__gateway__soa_gateway_connection_state__get_packed_size
                     (const Fnv__Soa__Gateway__SoaGatewayConnectionState   *message);
size_t fnv__soa__gateway__soa_gateway_connection_state__pack
                     (const Fnv__Soa__Gateway__SoaGatewayConnectionState   *message,
                      uint8_t             *out);
size_t fnv__soa__gateway__soa_gateway_connection_state__pack_to_buffer
                     (const Fnv__Soa__Gateway__SoaGatewayConnectionState   *message,
                      ProtobufCBuffer     *buffer);
Fnv__Soa__Gateway__SoaGatewayConnectionState *
       fnv__soa__gateway__soa_gateway_connection_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fnv__soa__gateway__soa_gateway_connection_state__free_unpacked
                     (Fnv__Soa__Gateway__SoaGatewayConnectionState *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Fnv__Soa__Gateway__SoaGatewayConnectionState_Closure)
                 (const Fnv__Soa__Gateway__SoaGatewayConnectionState *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor fnv__soa__gateway__soa_gateway_connection_state__descriptor;
extern const ProtobufCEnumDescriptor    fnv__soa__gateway__soa_gateway_connection_state__connection_state__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_SoaGatewayConnectionState_2eproto__INCLUDED */
