/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: SoaIpcConnectionOptions.proto */

#ifndef PROTOBUF_C_SoaIpcConnectionOptions_2eproto__INCLUDED
#define PROTOBUF_C_SoaIpcConnectionOptions_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Fnv__Soa__Gateway__SoaIpcConnectionOptions Fnv__Soa__Gateway__SoaIpcConnectionOptions;


/* --- enums --- */


/* --- messages --- */

/*
 **
 * @fnv_proto
 * Sends the connection options from the SOA Gateway client to the client 
 * @fnv_topic This GPB is used over the IPC interface and does not use SOA messaging
 * @fnv_scope ECG_INTERNAL
 * @fnv_api_source INTERNAL
 * @fnv_message_version 1.0
 */
struct  _Fnv__Soa__Gateway__SoaIpcConnectionOptions
{
  ProtobufCMessage base;
  char *serverfilepath;
  char *clientfilepath;
  protobuf_c_boolean has_cleansession;
  protobuf_c_boolean cleansession;
  protobuf_c_boolean has_keepalive;
  int32_t keepalive;
  protobuf_c_boolean has_lastwillandtestament;
  protobuf_c_boolean lastwillandtestament;
  protobuf_c_boolean has_retained;
  protobuf_c_boolean retained;
};
#define FNV__SOA__GATEWAY__SOA_IPC_CONNECTION_OPTIONS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fnv__soa__gateway__soa_ipc_connection_options__descriptor) \
    , NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0 }


/* Fnv__Soa__Gateway__SoaIpcConnectionOptions methods */
void   fnv__soa__gateway__soa_ipc_connection_options__init
                     (Fnv__Soa__Gateway__SoaIpcConnectionOptions         *message);
size_t fnv__soa__gateway__soa_ipc_connection_options__get_packed_size
                     (const Fnv__Soa__Gateway__SoaIpcConnectionOptions   *message);
size_t fnv__soa__gateway__soa_ipc_connection_options__pack
                     (const Fnv__Soa__Gateway__SoaIpcConnectionOptions   *message,
                      uint8_t             *out);
size_t fnv__soa__gateway__soa_ipc_connection_options__pack_to_buffer
                     (const Fnv__Soa__Gateway__SoaIpcConnectionOptions   *message,
                      ProtobufCBuffer     *buffer);
Fnv__Soa__Gateway__SoaIpcConnectionOptions *
       fnv__soa__gateway__soa_ipc_connection_options__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fnv__soa__gateway__soa_ipc_connection_options__free_unpacked
                     (Fnv__Soa__Gateway__SoaIpcConnectionOptions *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Fnv__Soa__Gateway__SoaIpcConnectionOptions_Closure)
                 (const Fnv__Soa__Gateway__SoaIpcConnectionOptions *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor fnv__soa__gateway__soa_ipc_connection_options__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_SoaIpcConnectionOptions_2eproto__INCLUDED */
