// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SoaStartServiceResponsePayload.proto

#ifndef PROTOBUF_SoaStartServiceResponsePayload_2eproto__INCLUDED
#define PROTOBUF_SoaStartServiceResponsePayload_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "sm_transaction_status_public.pb.h"  // IWYU pragma: export
#include "Endpoint.pb.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

namespace protobuf_SoaStartServiceResponsePayload_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsSoaStartServiceResultProtoImpl();
void InitDefaultsSoaStartServiceResultProto();
void InitDefaultsSoaStartServiceResponsePayloadProtoImpl();
void InitDefaultsSoaStartServiceResponsePayloadProto();
inline void InitDefaults() {
  InitDefaultsSoaStartServiceResultProto();
  InitDefaultsSoaStartServiceResponsePayloadProto();
}
}  // namespace protobuf_SoaStartServiceResponsePayload_2eproto
namespace fnv {
namespace soa {
namespace framework {
namespace protobuf {
class SoaStartServiceResponsePayloadProto;
class SoaStartServiceResponsePayloadProtoDefaultTypeInternal;
extern SoaStartServiceResponsePayloadProtoDefaultTypeInternal _SoaStartServiceResponsePayloadProto_default_instance_;
class SoaStartServiceResultProto;
class SoaStartServiceResultProtoDefaultTypeInternal;
extern SoaStartServiceResultProtoDefaultTypeInternal _SoaStartServiceResultProto_default_instance_;
}  // namespace protobuf
}  // namespace framework
}  // namespace soa
}  // namespace fnv
namespace fnv {
namespace soa {
namespace framework {
namespace protobuf {

enum SoaStartServiceResultProto_ActionStatus {
  SoaStartServiceResultProto_ActionStatus_OK = 0,
  SoaStartServiceResultProto_ActionStatus_ERROR_SERVICE_NOT_AVAILABLE = 1,
  SoaStartServiceResultProto_ActionStatus_ERROR_GENERAL_ERROR = 2,
  SoaStartServiceResultProto_ActionStatus_ERROR_ALM_ERROR = 3,
  SoaStartServiceResultProto_ActionStatus_ERROR_SERVICES_DB_ERROR = 4,
  SoaStartServiceResultProto_ActionStatus_ERROR_SERVICE_TYPE_ERROR = 5
};
bool SoaStartServiceResultProto_ActionStatus_IsValid(int value);
const SoaStartServiceResultProto_ActionStatus SoaStartServiceResultProto_ActionStatus_ActionStatus_MIN = SoaStartServiceResultProto_ActionStatus_OK;
const SoaStartServiceResultProto_ActionStatus SoaStartServiceResultProto_ActionStatus_ActionStatus_MAX = SoaStartServiceResultProto_ActionStatus_ERROR_SERVICE_TYPE_ERROR;
const int SoaStartServiceResultProto_ActionStatus_ActionStatus_ARRAYSIZE = SoaStartServiceResultProto_ActionStatus_ActionStatus_MAX + 1;

const ::google::protobuf::EnumDescriptor* SoaStartServiceResultProto_ActionStatus_descriptor();
inline const ::std::string& SoaStartServiceResultProto_ActionStatus_Name(SoaStartServiceResultProto_ActionStatus value) {
  return ::google::protobuf::internal::NameOfEnum(
    SoaStartServiceResultProto_ActionStatus_descriptor(), value);
}
inline bool SoaStartServiceResultProto_ActionStatus_Parse(
    const ::std::string& name, SoaStartServiceResultProto_ActionStatus* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SoaStartServiceResultProto_ActionStatus>(
    SoaStartServiceResultProto_ActionStatus_descriptor(), name, value);
}
// ===================================================================

class SoaStartServiceResultProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fnv.soa.framework.protobuf.SoaStartServiceResultProto) */ {
 public:
  SoaStartServiceResultProto();
  virtual ~SoaStartServiceResultProto();

  SoaStartServiceResultProto(const SoaStartServiceResultProto& from);

  inline SoaStartServiceResultProto& operator=(const SoaStartServiceResultProto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SoaStartServiceResultProto(SoaStartServiceResultProto&& from) noexcept
    : SoaStartServiceResultProto() {
    *this = ::std::move(from);
  }

  inline SoaStartServiceResultProto& operator=(SoaStartServiceResultProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SoaStartServiceResultProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SoaStartServiceResultProto* internal_default_instance() {
    return reinterpret_cast<const SoaStartServiceResultProto*>(
               &_SoaStartServiceResultProto_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(SoaStartServiceResultProto* other);
  friend void swap(SoaStartServiceResultProto& a, SoaStartServiceResultProto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SoaStartServiceResultProto* New() const PROTOBUF_FINAL { return New(NULL); }

  SoaStartServiceResultProto* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SoaStartServiceResultProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef SoaStartServiceResultProto_ActionStatus ActionStatus;
  static const ActionStatus OK =
    SoaStartServiceResultProto_ActionStatus_OK;
  static const ActionStatus ERROR_SERVICE_NOT_AVAILABLE =
    SoaStartServiceResultProto_ActionStatus_ERROR_SERVICE_NOT_AVAILABLE;
  static const ActionStatus ERROR_GENERAL_ERROR =
    SoaStartServiceResultProto_ActionStatus_ERROR_GENERAL_ERROR;
  static const ActionStatus ERROR_ALM_ERROR =
    SoaStartServiceResultProto_ActionStatus_ERROR_ALM_ERROR;
  static const ActionStatus ERROR_SERVICES_DB_ERROR =
    SoaStartServiceResultProto_ActionStatus_ERROR_SERVICES_DB_ERROR;
  static const ActionStatus ERROR_SERVICE_TYPE_ERROR =
    SoaStartServiceResultProto_ActionStatus_ERROR_SERVICE_TYPE_ERROR;
  static inline bool ActionStatus_IsValid(int value) {
    return SoaStartServiceResultProto_ActionStatus_IsValid(value);
  }
  static const ActionStatus ActionStatus_MIN =
    SoaStartServiceResultProto_ActionStatus_ActionStatus_MIN;
  static const ActionStatus ActionStatus_MAX =
    SoaStartServiceResultProto_ActionStatus_ActionStatus_MAX;
  static const int ActionStatus_ARRAYSIZE =
    SoaStartServiceResultProto_ActionStatus_ActionStatus_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ActionStatus_descriptor() {
    return SoaStartServiceResultProto_ActionStatus_descriptor();
  }
  static inline const ::std::string& ActionStatus_Name(ActionStatus value) {
    return SoaStartServiceResultProto_ActionStatus_Name(value);
  }
  static inline bool ActionStatus_Parse(const ::std::string& name,
      ActionStatus* value) {
    return SoaStartServiceResultProto_ActionStatus_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .fnv.soa.framework.protobuf.Endpoint endpoint = 1;
  bool has_endpoint() const;
  void clear_endpoint();
  static const int kEndpointFieldNumber = 1;
  const ::fnv::soa::framework::protobuf::Endpoint& endpoint() const;
  ::fnv::soa::framework::protobuf::Endpoint* release_endpoint();
  ::fnv::soa::framework::protobuf::Endpoint* mutable_endpoint();
  void set_allocated_endpoint(::fnv::soa::framework::protobuf::Endpoint* endpoint);

  // optional .fnv.soa.framework.protobuf.SoaStartServiceResultProto.ActionStatus status = 2 [default = OK];
  bool has_status() const;
  void clear_status();
  static const int kStatusFieldNumber = 2;
  ::fnv::soa::framework::protobuf::SoaStartServiceResultProto_ActionStatus status() const;
  void set_status(::fnv::soa::framework::protobuf::SoaStartServiceResultProto_ActionStatus value);

  // @@protoc_insertion_point(class_scope:fnv.soa.framework.protobuf.SoaStartServiceResultProto)
 private:
  void set_has_endpoint();
  void clear_has_endpoint();
  void set_has_status();
  void clear_has_status();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::fnv::soa::framework::protobuf::Endpoint* endpoint_;
  int status_;
  friend struct ::protobuf_SoaStartServiceResponsePayload_2eproto::TableStruct;
  friend void ::protobuf_SoaStartServiceResponsePayload_2eproto::InitDefaultsSoaStartServiceResultProtoImpl();
};
// -------------------------------------------------------------------

class SoaStartServiceResponsePayloadProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fnv.soa.framework.protobuf.SoaStartServiceResponsePayloadProto) */ {
 public:
  SoaStartServiceResponsePayloadProto();
  virtual ~SoaStartServiceResponsePayloadProto();

  SoaStartServiceResponsePayloadProto(const SoaStartServiceResponsePayloadProto& from);

  inline SoaStartServiceResponsePayloadProto& operator=(const SoaStartServiceResponsePayloadProto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SoaStartServiceResponsePayloadProto(SoaStartServiceResponsePayloadProto&& from) noexcept
    : SoaStartServiceResponsePayloadProto() {
    *this = ::std::move(from);
  }

  inline SoaStartServiceResponsePayloadProto& operator=(SoaStartServiceResponsePayloadProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SoaStartServiceResponsePayloadProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SoaStartServiceResponsePayloadProto* internal_default_instance() {
    return reinterpret_cast<const SoaStartServiceResponsePayloadProto*>(
               &_SoaStartServiceResponsePayloadProto_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(SoaStartServiceResponsePayloadProto* other);
  friend void swap(SoaStartServiceResponsePayloadProto& a, SoaStartServiceResponsePayloadProto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SoaStartServiceResponsePayloadProto* New() const PROTOBUF_FINAL { return New(NULL); }

  SoaStartServiceResponsePayloadProto* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SoaStartServiceResponsePayloadProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .fnv.soa.framework.protobuf.SoaStartServiceResultProto metadata = 2;
  int metadata_size() const;
  void clear_metadata();
  static const int kMetadataFieldNumber = 2;
  const ::fnv::soa::framework::protobuf::SoaStartServiceResultProto& metadata(int index) const;
  ::fnv::soa::framework::protobuf::SoaStartServiceResultProto* mutable_metadata(int index);
  ::fnv::soa::framework::protobuf::SoaStartServiceResultProto* add_metadata();
  ::google::protobuf::RepeatedPtrField< ::fnv::soa::framework::protobuf::SoaStartServiceResultProto >*
      mutable_metadata();
  const ::google::protobuf::RepeatedPtrField< ::fnv::soa::framework::protobuf::SoaStartServiceResultProto >&
      metadata() const;

  // optional .fnv.soa.framework.protobuf.SmTransactionStatus.Status transactionStatus = 1 [default = OK];
  bool has_transactionstatus() const;
  void clear_transactionstatus();
  static const int kTransactionStatusFieldNumber = 1;
  ::fnv::soa::framework::protobuf::SmTransactionStatus_Status transactionstatus() const;
  void set_transactionstatus(::fnv::soa::framework::protobuf::SmTransactionStatus_Status value);

  // @@protoc_insertion_point(class_scope:fnv.soa.framework.protobuf.SoaStartServiceResponsePayloadProto)
 private:
  void set_has_transactionstatus();
  void clear_has_transactionstatus();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::fnv::soa::framework::protobuf::SoaStartServiceResultProto > metadata_;
  int transactionstatus_;
  friend struct ::protobuf_SoaStartServiceResponsePayload_2eproto::TableStruct;
  friend void ::protobuf_SoaStartServiceResponsePayload_2eproto::InitDefaultsSoaStartServiceResponsePayloadProtoImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SoaStartServiceResultProto

// optional .fnv.soa.framework.protobuf.Endpoint endpoint = 1;
inline bool SoaStartServiceResultProto::has_endpoint() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SoaStartServiceResultProto::set_has_endpoint() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SoaStartServiceResultProto::clear_has_endpoint() {
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::fnv::soa::framework::protobuf::Endpoint& SoaStartServiceResultProto::endpoint() const {
  const ::fnv::soa::framework::protobuf::Endpoint* p = endpoint_;
  // @@protoc_insertion_point(field_get:fnv.soa.framework.protobuf.SoaStartServiceResultProto.endpoint)
  return p != NULL ? *p : *reinterpret_cast<const ::fnv::soa::framework::protobuf::Endpoint*>(
      &::fnv::soa::framework::protobuf::_Endpoint_default_instance_);
}
inline ::fnv::soa::framework::protobuf::Endpoint* SoaStartServiceResultProto::release_endpoint() {
  // @@protoc_insertion_point(field_release:fnv.soa.framework.protobuf.SoaStartServiceResultProto.endpoint)
  clear_has_endpoint();
  ::fnv::soa::framework::protobuf::Endpoint* temp = endpoint_;
  endpoint_ = NULL;
  return temp;
}
inline ::fnv::soa::framework::protobuf::Endpoint* SoaStartServiceResultProto::mutable_endpoint() {
  set_has_endpoint();
  if (endpoint_ == NULL) {
    endpoint_ = new ::fnv::soa::framework::protobuf::Endpoint;
  }
  // @@protoc_insertion_point(field_mutable:fnv.soa.framework.protobuf.SoaStartServiceResultProto.endpoint)
  return endpoint_;
}
inline void SoaStartServiceResultProto::set_allocated_endpoint(::fnv::soa::framework::protobuf::Endpoint* endpoint) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(endpoint_);
  }
  if (endpoint) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      endpoint = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, endpoint, submessage_arena);
    }
    set_has_endpoint();
  } else {
    clear_has_endpoint();
  }
  endpoint_ = endpoint;
  // @@protoc_insertion_point(field_set_allocated:fnv.soa.framework.protobuf.SoaStartServiceResultProto.endpoint)
}

// optional .fnv.soa.framework.protobuf.SoaStartServiceResultProto.ActionStatus status = 2 [default = OK];
inline bool SoaStartServiceResultProto::has_status() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SoaStartServiceResultProto::set_has_status() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SoaStartServiceResultProto::clear_has_status() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SoaStartServiceResultProto::clear_status() {
  status_ = 0;
  clear_has_status();
}
inline ::fnv::soa::framework::protobuf::SoaStartServiceResultProto_ActionStatus SoaStartServiceResultProto::status() const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.protobuf.SoaStartServiceResultProto.status)
  return static_cast< ::fnv::soa::framework::protobuf::SoaStartServiceResultProto_ActionStatus >(status_);
}
inline void SoaStartServiceResultProto::set_status(::fnv::soa::framework::protobuf::SoaStartServiceResultProto_ActionStatus value) {
  assert(::fnv::soa::framework::protobuf::SoaStartServiceResultProto_ActionStatus_IsValid(value));
  set_has_status();
  status_ = value;
  // @@protoc_insertion_point(field_set:fnv.soa.framework.protobuf.SoaStartServiceResultProto.status)
}

// -------------------------------------------------------------------

// SoaStartServiceResponsePayloadProto

// optional .fnv.soa.framework.protobuf.SmTransactionStatus.Status transactionStatus = 1 [default = OK];
inline bool SoaStartServiceResponsePayloadProto::has_transactionstatus() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SoaStartServiceResponsePayloadProto::set_has_transactionstatus() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SoaStartServiceResponsePayloadProto::clear_has_transactionstatus() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SoaStartServiceResponsePayloadProto::clear_transactionstatus() {
  transactionstatus_ = 1;
  clear_has_transactionstatus();
}
inline ::fnv::soa::framework::protobuf::SmTransactionStatus_Status SoaStartServiceResponsePayloadProto::transactionstatus() const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.protobuf.SoaStartServiceResponsePayloadProto.transactionStatus)
  return static_cast< ::fnv::soa::framework::protobuf::SmTransactionStatus_Status >(transactionstatus_);
}
inline void SoaStartServiceResponsePayloadProto::set_transactionstatus(::fnv::soa::framework::protobuf::SmTransactionStatus_Status value) {
  assert(::fnv::soa::framework::protobuf::SmTransactionStatus_Status_IsValid(value));
  set_has_transactionstatus();
  transactionstatus_ = value;
  // @@protoc_insertion_point(field_set:fnv.soa.framework.protobuf.SoaStartServiceResponsePayloadProto.transactionStatus)
}

// repeated .fnv.soa.framework.protobuf.SoaStartServiceResultProto metadata = 2;
inline int SoaStartServiceResponsePayloadProto::metadata_size() const {
  return metadata_.size();
}
inline void SoaStartServiceResponsePayloadProto::clear_metadata() {
  metadata_.Clear();
}
inline const ::fnv::soa::framework::protobuf::SoaStartServiceResultProto& SoaStartServiceResponsePayloadProto::metadata(int index) const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.protobuf.SoaStartServiceResponsePayloadProto.metadata)
  return metadata_.Get(index);
}
inline ::fnv::soa::framework::protobuf::SoaStartServiceResultProto* SoaStartServiceResponsePayloadProto::mutable_metadata(int index) {
  // @@protoc_insertion_point(field_mutable:fnv.soa.framework.protobuf.SoaStartServiceResponsePayloadProto.metadata)
  return metadata_.Mutable(index);
}
inline ::fnv::soa::framework::protobuf::SoaStartServiceResultProto* SoaStartServiceResponsePayloadProto::add_metadata() {
  // @@protoc_insertion_point(field_add:fnv.soa.framework.protobuf.SoaStartServiceResponsePayloadProto.metadata)
  return metadata_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::fnv::soa::framework::protobuf::SoaStartServiceResultProto >*
SoaStartServiceResponsePayloadProto::mutable_metadata() {
  // @@protoc_insertion_point(field_mutable_list:fnv.soa.framework.protobuf.SoaStartServiceResponsePayloadProto.metadata)
  return &metadata_;
}
inline const ::google::protobuf::RepeatedPtrField< ::fnv::soa::framework::protobuf::SoaStartServiceResultProto >&
SoaStartServiceResponsePayloadProto::metadata() const {
  // @@protoc_insertion_point(field_list:fnv.soa.framework.protobuf.SoaStartServiceResponsePayloadProto.metadata)
  return metadata_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace framework
}  // namespace soa
}  // namespace fnv

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::fnv::soa::framework::protobuf::SoaStartServiceResultProto_ActionStatus> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::fnv::soa::framework::protobuf::SoaStartServiceResultProto_ActionStatus>() {
  return ::fnv::soa::framework::protobuf::SoaStartServiceResultProto_ActionStatus_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_SoaStartServiceResponsePayload_2eproto__INCLUDED
