/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: SoaStartServiceResponsePayload.proto */

#ifndef PROTOBUF_C_SoaStartServiceResponsePayload_2eproto__INCLUDED
#define PROTOBUF_C_SoaStartServiceResponsePayload_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "sm_transaction_status_public.pb-c.h"
#include "Endpoint.pb-c.h"

typedef struct _Fnv__Soa__Framework__Protobuf__SoaStartServiceResultProto Fnv__Soa__Framework__Protobuf__SoaStartServiceResultProto;
typedef struct _Fnv__Soa__Framework__Protobuf__SoaStartServiceResponsePayloadProto Fnv__Soa__Framework__Protobuf__SoaStartServiceResponsePayloadProto;


/* --- enums --- */

typedef enum _Fnv__Soa__Framework__Protobuf__SoaStartServiceResultProto__ActionStatus {
  FNV__SOA__FRAMEWORK__PROTOBUF__SOA_START_SERVICE_RESULT_PROTO__ACTION_STATUS__OK = 0,
  FNV__SOA__FRAMEWORK__PROTOBUF__SOA_START_SERVICE_RESULT_PROTO__ACTION_STATUS__ERROR_SERVICE_NOT_AVAILABLE = 1,
  FNV__SOA__FRAMEWORK__PROTOBUF__SOA_START_SERVICE_RESULT_PROTO__ACTION_STATUS__ERROR_GENERAL_ERROR = 2,
  FNV__SOA__FRAMEWORK__PROTOBUF__SOA_START_SERVICE_RESULT_PROTO__ACTION_STATUS__ERROR_ALM_ERROR = 3,
  FNV__SOA__FRAMEWORK__PROTOBUF__SOA_START_SERVICE_RESULT_PROTO__ACTION_STATUS__ERROR_SERVICES_DB_ERROR = 4,
  FNV__SOA__FRAMEWORK__PROTOBUF__SOA_START_SERVICE_RESULT_PROTO__ACTION_STATUS__ERROR_SERVICE_TYPE_ERROR = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(FNV__SOA__FRAMEWORK__PROTOBUF__SOA_START_SERVICE_RESULT_PROTO__ACTION_STATUS)
} Fnv__Soa__Framework__Protobuf__SoaStartServiceResultProto__ActionStatus;

/* --- messages --- */

struct  _Fnv__Soa__Framework__Protobuf__SoaStartServiceResultProto
{
  ProtobufCMessage base;
  Fnv__Soa__Framework__Protobuf__Endpoint *endpoint;
  protobuf_c_boolean has_status;
  Fnv__Soa__Framework__Protobuf__SoaStartServiceResultProto__ActionStatus status;
};
#define FNV__SOA__FRAMEWORK__PROTOBUF__SOA_START_SERVICE_RESULT_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fnv__soa__framework__protobuf__soa_start_service_result_proto__descriptor) \
    , NULL, 0, FNV__SOA__FRAMEWORK__PROTOBUF__SOA_START_SERVICE_RESULT_PROTO__ACTION_STATUS__OK }


/*
 **
 * @fnv_proto
 * @fnv_message_proto
 */
struct  _Fnv__Soa__Framework__Protobuf__SoaStartServiceResponsePayloadProto
{
  ProtobufCMessage base;
  protobuf_c_boolean has_transactionstatus;
  Fnv__Soa__Framework__Protobuf__SmTransactionStatus__Status transactionstatus;
  size_t n_metadata;
  Fnv__Soa__Framework__Protobuf__SoaStartServiceResultProto **metadata;
};
#define FNV__SOA__FRAMEWORK__PROTOBUF__SOA_START_SERVICE_RESPONSE_PAYLOAD_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fnv__soa__framework__protobuf__soa_start_service_response_payload_proto__descriptor) \
    , 0, FNV__SOA__FRAMEWORK__PROTOBUF__SM_TRANSACTION_STATUS__STATUS__OK, 0,NULL }


/* Fnv__Soa__Framework__Protobuf__SoaStartServiceResultProto methods */
void   fnv__soa__framework__protobuf__soa_start_service_result_proto__init
                     (Fnv__Soa__Framework__Protobuf__SoaStartServiceResultProto         *message);
size_t fnv__soa__framework__protobuf__soa_start_service_result_proto__get_packed_size
                     (const Fnv__Soa__Framework__Protobuf__SoaStartServiceResultProto   *message);
size_t fnv__soa__framework__protobuf__soa_start_service_result_proto__pack
                     (const Fnv__Soa__Framework__Protobuf__SoaStartServiceResultProto   *message,
                      uint8_t             *out);
size_t fnv__soa__framework__protobuf__soa_start_service_result_proto__pack_to_buffer
                     (const Fnv__Soa__Framework__Protobuf__SoaStartServiceResultProto   *message,
                      ProtobufCBuffer     *buffer);
Fnv__Soa__Framework__Protobuf__SoaStartServiceResultProto *
       fnv__soa__framework__protobuf__soa_start_service_result_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fnv__soa__framework__protobuf__soa_start_service_result_proto__free_unpacked
                     (Fnv__Soa__Framework__Protobuf__SoaStartServiceResultProto *message,
                      ProtobufCAllocator *allocator);
/* Fnv__Soa__Framework__Protobuf__SoaStartServiceResponsePayloadProto methods */
void   fnv__soa__framework__protobuf__soa_start_service_response_payload_proto__init
                     (Fnv__Soa__Framework__Protobuf__SoaStartServiceResponsePayloadProto         *message);
size_t fnv__soa__framework__protobuf__soa_start_service_response_payload_proto__get_packed_size
                     (const Fnv__Soa__Framework__Protobuf__SoaStartServiceResponsePayloadProto   *message);
size_t fnv__soa__framework__protobuf__soa_start_service_response_payload_proto__pack
                     (const Fnv__Soa__Framework__Protobuf__SoaStartServiceResponsePayloadProto   *message,
                      uint8_t             *out);
size_t fnv__soa__framework__protobuf__soa_start_service_response_payload_proto__pack_to_buffer
                     (const Fnv__Soa__Framework__Protobuf__SoaStartServiceResponsePayloadProto   *message,
                      ProtobufCBuffer     *buffer);
Fnv__Soa__Framework__Protobuf__SoaStartServiceResponsePayloadProto *
       fnv__soa__framework__protobuf__soa_start_service_response_payload_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fnv__soa__framework__protobuf__soa_start_service_response_payload_proto__free_unpacked
                     (Fnv__Soa__Framework__Protobuf__SoaStartServiceResponsePayloadProto *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Fnv__Soa__Framework__Protobuf__SoaStartServiceResultProto_Closure)
                 (const Fnv__Soa__Framework__Protobuf__SoaStartServiceResultProto *message,
                  void *closure_data);
typedef void (*Fnv__Soa__Framework__Protobuf__SoaStartServiceResponsePayloadProto_Closure)
                 (const Fnv__Soa__Framework__Protobuf__SoaStartServiceResponsePayloadProto *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor fnv__soa__framework__protobuf__soa_start_service_result_proto__descriptor;
extern const ProtobufCEnumDescriptor    fnv__soa__framework__protobuf__soa_start_service_result_proto__action_status__descriptor;
extern const ProtobufCMessageDescriptor fnv__soa__framework__protobuf__soa_start_service_response_payload_proto__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_SoaStartServiceResponsePayload_2eproto__INCLUDED */
