// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StartStopServiceResult.proto

#ifndef PROTOBUF_StartStopServiceResult_2eproto__INCLUDED
#define PROTOBUF_StartStopServiceResult_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_StartStopServiceResult_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsStartStopServiceResultProtoImpl();
void InitDefaultsStartStopServiceResultProto();
inline void InitDefaults() {
  InitDefaultsStartStopServiceResultProto();
}
}  // namespace protobuf_StartStopServiceResult_2eproto
namespace fnv {
namespace soa {
namespace framework {
namespace protobuf {
class StartStopServiceResultProto;
class StartStopServiceResultProtoDefaultTypeInternal;
extern StartStopServiceResultProtoDefaultTypeInternal _StartStopServiceResultProto_default_instance_;
}  // namespace protobuf
}  // namespace framework
}  // namespace soa
}  // namespace fnv
namespace fnv {
namespace soa {
namespace framework {
namespace protobuf {

enum StartStopServiceResultProto_ActionStatus {
  StartStopServiceResultProto_ActionStatus_OK = 0,
  StartStopServiceResultProto_ActionStatus_ERROR_CLIENT_ALREADY_STARTED = 1,
  StartStopServiceResultProto_ActionStatus_ERROR_CLIENT_NOT_STARTED = 2,
  StartStopServiceResultProto_ActionStatus_ERROR_GENERAL_ERROR = 3
};
bool StartStopServiceResultProto_ActionStatus_IsValid(int value);
const StartStopServiceResultProto_ActionStatus StartStopServiceResultProto_ActionStatus_ActionStatus_MIN = StartStopServiceResultProto_ActionStatus_OK;
const StartStopServiceResultProto_ActionStatus StartStopServiceResultProto_ActionStatus_ActionStatus_MAX = StartStopServiceResultProto_ActionStatus_ERROR_GENERAL_ERROR;
const int StartStopServiceResultProto_ActionStatus_ActionStatus_ARRAYSIZE = StartStopServiceResultProto_ActionStatus_ActionStatus_MAX + 1;

const ::google::protobuf::EnumDescriptor* StartStopServiceResultProto_ActionStatus_descriptor();
inline const ::std::string& StartStopServiceResultProto_ActionStatus_Name(StartStopServiceResultProto_ActionStatus value) {
  return ::google::protobuf::internal::NameOfEnum(
    StartStopServiceResultProto_ActionStatus_descriptor(), value);
}
inline bool StartStopServiceResultProto_ActionStatus_Parse(
    const ::std::string& name, StartStopServiceResultProto_ActionStatus* value) {
  return ::google::protobuf::internal::ParseNamedEnum<StartStopServiceResultProto_ActionStatus>(
    StartStopServiceResultProto_ActionStatus_descriptor(), name, value);
}
// ===================================================================

class StartStopServiceResultProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fnv.soa.framework.protobuf.StartStopServiceResultProto) */ {
 public:
  StartStopServiceResultProto();
  virtual ~StartStopServiceResultProto();

  StartStopServiceResultProto(const StartStopServiceResultProto& from);

  inline StartStopServiceResultProto& operator=(const StartStopServiceResultProto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  StartStopServiceResultProto(StartStopServiceResultProto&& from) noexcept
    : StartStopServiceResultProto() {
    *this = ::std::move(from);
  }

  inline StartStopServiceResultProto& operator=(StartStopServiceResultProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StartStopServiceResultProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StartStopServiceResultProto* internal_default_instance() {
    return reinterpret_cast<const StartStopServiceResultProto*>(
               &_StartStopServiceResultProto_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(StartStopServiceResultProto* other);
  friend void swap(StartStopServiceResultProto& a, StartStopServiceResultProto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline StartStopServiceResultProto* New() const PROTOBUF_FINAL { return New(NULL); }

  StartStopServiceResultProto* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(StartStopServiceResultProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef StartStopServiceResultProto_ActionStatus ActionStatus;
  static const ActionStatus OK =
    StartStopServiceResultProto_ActionStatus_OK;
  static const ActionStatus ERROR_CLIENT_ALREADY_STARTED =
    StartStopServiceResultProto_ActionStatus_ERROR_CLIENT_ALREADY_STARTED;
  static const ActionStatus ERROR_CLIENT_NOT_STARTED =
    StartStopServiceResultProto_ActionStatus_ERROR_CLIENT_NOT_STARTED;
  static const ActionStatus ERROR_GENERAL_ERROR =
    StartStopServiceResultProto_ActionStatus_ERROR_GENERAL_ERROR;
  static inline bool ActionStatus_IsValid(int value) {
    return StartStopServiceResultProto_ActionStatus_IsValid(value);
  }
  static const ActionStatus ActionStatus_MIN =
    StartStopServiceResultProto_ActionStatus_ActionStatus_MIN;
  static const ActionStatus ActionStatus_MAX =
    StartStopServiceResultProto_ActionStatus_ActionStatus_MAX;
  static const int ActionStatus_ARRAYSIZE =
    StartStopServiceResultProto_ActionStatus_ActionStatus_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ActionStatus_descriptor() {
    return StartStopServiceResultProto_ActionStatus_descriptor();
  }
  static inline const ::std::string& ActionStatus_Name(ActionStatus value) {
    return StartStopServiceResultProto_ActionStatus_Name(value);
  }
  static inline bool ActionStatus_Parse(const ::std::string& name,
      ActionStatus* value) {
    return StartStopServiceResultProto_ActionStatus_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:fnv.soa.framework.protobuf.StartStopServiceResultProto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  friend struct ::protobuf_StartStopServiceResult_2eproto::TableStruct;
  friend void ::protobuf_StartStopServiceResult_2eproto::InitDefaultsStartStopServiceResultProtoImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// StartStopServiceResultProto

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace framework
}  // namespace soa
}  // namespace fnv

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::fnv::soa::framework::protobuf::StartStopServiceResultProto_ActionStatus> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::fnv::soa::framework::protobuf::StartStopServiceResultProto_ActionStatus>() {
  return ::fnv::soa::framework::protobuf::StartStopServiceResultProto_ActionStatus_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_StartStopServiceResult_2eproto__INCLUDED
