// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StartStopServiceRequestPayload.proto

#ifndef PROTOBUF_StartStopServiceRequestPayload_2eproto__INCLUDED
#define PROTOBUF_StartStopServiceRequestPayload_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_StartStopServiceRequestPayload_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsStartStopStopServiceRequestPayloadProtoImpl();
void InitDefaultsStartStopStopServiceRequestPayloadProto();
inline void InitDefaults() {
  InitDefaultsStartStopStopServiceRequestPayloadProto();
}
}  // namespace protobuf_StartStopServiceRequestPayload_2eproto
namespace fnv {
namespace soa {
namespace framework {
namespace protobuf {
class StartStopStopServiceRequestPayloadProto;
class StartStopStopServiceRequestPayloadProtoDefaultTypeInternal;
extern StartStopStopServiceRequestPayloadProtoDefaultTypeInternal _StartStopStopServiceRequestPayloadProto_default_instance_;
}  // namespace protobuf
}  // namespace framework
}  // namespace soa
}  // namespace fnv
namespace fnv {
namespace soa {
namespace framework {
namespace protobuf {

// ===================================================================

class StartStopStopServiceRequestPayloadProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fnv.soa.framework.protobuf.StartStopStopServiceRequestPayloadProto) */ {
 public:
  StartStopStopServiceRequestPayloadProto();
  virtual ~StartStopStopServiceRequestPayloadProto();

  StartStopStopServiceRequestPayloadProto(const StartStopStopServiceRequestPayloadProto& from);

  inline StartStopStopServiceRequestPayloadProto& operator=(const StartStopStopServiceRequestPayloadProto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  StartStopStopServiceRequestPayloadProto(StartStopStopServiceRequestPayloadProto&& from) noexcept
    : StartStopStopServiceRequestPayloadProto() {
    *this = ::std::move(from);
  }

  inline StartStopStopServiceRequestPayloadProto& operator=(StartStopStopServiceRequestPayloadProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StartStopStopServiceRequestPayloadProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StartStopStopServiceRequestPayloadProto* internal_default_instance() {
    return reinterpret_cast<const StartStopStopServiceRequestPayloadProto*>(
               &_StartStopStopServiceRequestPayloadProto_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(StartStopStopServiceRequestPayloadProto* other);
  friend void swap(StartStopStopServiceRequestPayloadProto& a, StartStopStopServiceRequestPayloadProto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline StartStopStopServiceRequestPayloadProto* New() const PROTOBUF_FINAL { return New(NULL); }

  StartStopStopServiceRequestPayloadProto* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(StartStopStopServiceRequestPayloadProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string metadata = 1;
  int metadata_size() const;
  void clear_metadata();
  static const int kMetadataFieldNumber = 1;
  const ::std::string& metadata(int index) const;
  ::std::string* mutable_metadata(int index);
  void set_metadata(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_metadata(int index, ::std::string&& value);
  #endif
  void set_metadata(int index, const char* value);
  void set_metadata(int index, const char* value, size_t size);
  ::std::string* add_metadata();
  void add_metadata(const ::std::string& value);
  #if LANG_CXX11
  void add_metadata(::std::string&& value);
  #endif
  void add_metadata(const char* value);
  void add_metadata(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& metadata() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_metadata();

  // @@protoc_insertion_point(class_scope:fnv.soa.framework.protobuf.StartStopStopServiceRequestPayloadProto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> metadata_;
  friend struct ::protobuf_StartStopServiceRequestPayload_2eproto::TableStruct;
  friend void ::protobuf_StartStopServiceRequestPayload_2eproto::InitDefaultsStartStopStopServiceRequestPayloadProtoImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// StartStopStopServiceRequestPayloadProto

// repeated string metadata = 1;
inline int StartStopStopServiceRequestPayloadProto::metadata_size() const {
  return metadata_.size();
}
inline void StartStopStopServiceRequestPayloadProto::clear_metadata() {
  metadata_.Clear();
}
inline const ::std::string& StartStopStopServiceRequestPayloadProto::metadata(int index) const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.protobuf.StartStopStopServiceRequestPayloadProto.metadata)
  return metadata_.Get(index);
}
inline ::std::string* StartStopStopServiceRequestPayloadProto::mutable_metadata(int index) {
  // @@protoc_insertion_point(field_mutable:fnv.soa.framework.protobuf.StartStopStopServiceRequestPayloadProto.metadata)
  return metadata_.Mutable(index);
}
inline void StartStopStopServiceRequestPayloadProto::set_metadata(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:fnv.soa.framework.protobuf.StartStopStopServiceRequestPayloadProto.metadata)
  metadata_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void StartStopStopServiceRequestPayloadProto::set_metadata(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:fnv.soa.framework.protobuf.StartStopStopServiceRequestPayloadProto.metadata)
  metadata_.Mutable(index)->assign(std::move(value));
}
#endif
inline void StartStopStopServiceRequestPayloadProto::set_metadata(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  metadata_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:fnv.soa.framework.protobuf.StartStopStopServiceRequestPayloadProto.metadata)
}
inline void StartStopStopServiceRequestPayloadProto::set_metadata(int index, const char* value, size_t size) {
  metadata_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:fnv.soa.framework.protobuf.StartStopStopServiceRequestPayloadProto.metadata)
}
inline ::std::string* StartStopStopServiceRequestPayloadProto::add_metadata() {
  // @@protoc_insertion_point(field_add_mutable:fnv.soa.framework.protobuf.StartStopStopServiceRequestPayloadProto.metadata)
  return metadata_.Add();
}
inline void StartStopStopServiceRequestPayloadProto::add_metadata(const ::std::string& value) {
  metadata_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:fnv.soa.framework.protobuf.StartStopStopServiceRequestPayloadProto.metadata)
}
#if LANG_CXX11
inline void StartStopStopServiceRequestPayloadProto::add_metadata(::std::string&& value) {
  metadata_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:fnv.soa.framework.protobuf.StartStopStopServiceRequestPayloadProto.metadata)
}
#endif
inline void StartStopStopServiceRequestPayloadProto::add_metadata(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  metadata_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:fnv.soa.framework.protobuf.StartStopStopServiceRequestPayloadProto.metadata)
}
inline void StartStopStopServiceRequestPayloadProto::add_metadata(const char* value, size_t size) {
  metadata_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:fnv.soa.framework.protobuf.StartStopStopServiceRequestPayloadProto.metadata)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
StartStopStopServiceRequestPayloadProto::metadata() const {
  // @@protoc_insertion_point(field_list:fnv.soa.framework.protobuf.StartStopStopServiceRequestPayloadProto.metadata)
  return metadata_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
StartStopStopServiceRequestPayloadProto::mutable_metadata() {
  // @@protoc_insertion_point(field_mutable_list:fnv.soa.framework.protobuf.StartStopStopServiceRequestPayloadProto.metadata)
  return &metadata_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace framework
}  // namespace soa
}  // namespace fnv

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_StartStopServiceRequestPayload_2eproto__INCLUDED
