/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: StartStopServiceResult.proto */

#ifndef PROTOBUF_C_StartStopServiceResult_2eproto__INCLUDED
#define PROTOBUF_C_StartStopServiceResult_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Fnv__Soa__Framework__Protobuf__StartStopServiceResultProto Fnv__Soa__Framework__Protobuf__StartStopServiceResultProto;


/* --- enums --- */

typedef enum _Fnv__Soa__Framework__Protobuf__StartStopServiceResultProto__ActionStatus {
  FNV__SOA__FRAMEWORK__PROTOBUF__START_STOP_SERVICE_RESULT_PROTO__ACTION_STATUS__OK = 0,
  FNV__SOA__FRAMEWORK__PROTOBUF__START_STOP_SERVICE_RESULT_PROTO__ACTION_STATUS__ERROR_CLIENT_ALREADY_STARTED = 1,
  FNV__SOA__FRAMEWORK__PROTOBUF__START_STOP_SERVICE_RESULT_PROTO__ACTION_STATUS__ERROR_CLIENT_NOT_STARTED = 2,
  FNV__SOA__FRAMEWORK__PROTOBUF__START_STOP_SERVICE_RESULT_PROTO__ACTION_STATUS__ERROR_GENERAL_ERROR = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(FNV__SOA__FRAMEWORK__PROTOBUF__START_STOP_SERVICE_RESULT_PROTO__ACTION_STATUS)
} Fnv__Soa__Framework__Protobuf__StartStopServiceResultProto__ActionStatus;

/* --- messages --- */

/*
 **
 * @fnv_message_proto
 * @fnv_deprecated
 */
struct  _Fnv__Soa__Framework__Protobuf__StartStopServiceResultProto
{
  ProtobufCMessage base;
};
#define FNV__SOA__FRAMEWORK__PROTOBUF__START_STOP_SERVICE_RESULT_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fnv__soa__framework__protobuf__start_stop_service_result_proto__descriptor) \
     }


/* Fnv__Soa__Framework__Protobuf__StartStopServiceResultProto methods */
void   fnv__soa__framework__protobuf__start_stop_service_result_proto__init
                     (Fnv__Soa__Framework__Protobuf__StartStopServiceResultProto         *message);
size_t fnv__soa__framework__protobuf__start_stop_service_result_proto__get_packed_size
                     (const Fnv__Soa__Framework__Protobuf__StartStopServiceResultProto   *message);
size_t fnv__soa__framework__protobuf__start_stop_service_result_proto__pack
                     (const Fnv__Soa__Framework__Protobuf__StartStopServiceResultProto   *message,
                      uint8_t             *out);
size_t fnv__soa__framework__protobuf__start_stop_service_result_proto__pack_to_buffer
                     (const Fnv__Soa__Framework__Protobuf__StartStopServiceResultProto   *message,
                      ProtobufCBuffer     *buffer);
Fnv__Soa__Framework__Protobuf__StartStopServiceResultProto *
       fnv__soa__framework__protobuf__start_stop_service_result_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fnv__soa__framework__protobuf__start_stop_service_result_proto__free_unpacked
                     (Fnv__Soa__Framework__Protobuf__StartStopServiceResultProto *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Fnv__Soa__Framework__Protobuf__StartStopServiceResultProto_Closure)
                 (const Fnv__Soa__Framework__Protobuf__StartStopServiceResultProto *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor fnv__soa__framework__protobuf__start_stop_service_result_proto__descriptor;
extern const ProtobufCEnumDescriptor    fnv__soa__framework__protobuf__start_stop_service_result_proto__action_status__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_StartStopServiceResult_2eproto__INCLUDED */
