// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StartStopServicesResponsePayload.proto

#ifndef PROTOBUF_StartStopServicesResponsePayload_2eproto__INCLUDED
#define PROTOBUF_StartStopServicesResponsePayload_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
#include "sm_transaction_status_public.pb.h"  // IWYU pragma: export
#include "StartStopServiceResult.pb.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

namespace protobuf_StartStopServicesResponsePayload_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsStartStopServicesResponsePayload_MetadataEntry_DoNotUseImpl();
void InitDefaultsStartStopServicesResponsePayload_MetadataEntry_DoNotUse();
void InitDefaultsStartStopServicesResponsePayloadImpl();
void InitDefaultsStartStopServicesResponsePayload();
inline void InitDefaults() {
  InitDefaultsStartStopServicesResponsePayload_MetadataEntry_DoNotUse();
  InitDefaultsStartStopServicesResponsePayload();
}
}  // namespace protobuf_StartStopServicesResponsePayload_2eproto
namespace fnv {
namespace soa {
namespace framework {
namespace protobuf {
class StartStopServicesResponsePayload;
class StartStopServicesResponsePayloadDefaultTypeInternal;
extern StartStopServicesResponsePayloadDefaultTypeInternal _StartStopServicesResponsePayload_default_instance_;
class StartStopServicesResponsePayload_MetadataEntry_DoNotUse;
class StartStopServicesResponsePayload_MetadataEntry_DoNotUseDefaultTypeInternal;
extern StartStopServicesResponsePayload_MetadataEntry_DoNotUseDefaultTypeInternal _StartStopServicesResponsePayload_MetadataEntry_DoNotUse_default_instance_;
}  // namespace protobuf
}  // namespace framework
}  // namespace soa
}  // namespace fnv
namespace fnv {
namespace soa {
namespace framework {
namespace protobuf {

// ===================================================================

class StartStopServicesResponsePayload_MetadataEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<StartStopServicesResponsePayload_MetadataEntry_DoNotUse, 
    ::std::string, ::fnv::soa::framework::protobuf::StartStopServiceResultProto_ActionStatus,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_ENUM,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<StartStopServicesResponsePayload_MetadataEntry_DoNotUse, 
    ::std::string, ::fnv::soa::framework::protobuf::StartStopServiceResultProto_ActionStatus,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_ENUM,
    0 > SuperType;
  StartStopServicesResponsePayload_MetadataEntry_DoNotUse();
  StartStopServicesResponsePayload_MetadataEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const StartStopServicesResponsePayload_MetadataEntry_DoNotUse& other);
  static const StartStopServicesResponsePayload_MetadataEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const StartStopServicesResponsePayload_MetadataEntry_DoNotUse*>(&_StartStopServicesResponsePayload_MetadataEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class StartStopServicesResponsePayload : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fnv.soa.framework.protobuf.StartStopServicesResponsePayload) */ {
 public:
  StartStopServicesResponsePayload();
  virtual ~StartStopServicesResponsePayload();

  StartStopServicesResponsePayload(const StartStopServicesResponsePayload& from);

  inline StartStopServicesResponsePayload& operator=(const StartStopServicesResponsePayload& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  StartStopServicesResponsePayload(StartStopServicesResponsePayload&& from) noexcept
    : StartStopServicesResponsePayload() {
    *this = ::std::move(from);
  }

  inline StartStopServicesResponsePayload& operator=(StartStopServicesResponsePayload&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StartStopServicesResponsePayload& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StartStopServicesResponsePayload* internal_default_instance() {
    return reinterpret_cast<const StartStopServicesResponsePayload*>(
               &_StartStopServicesResponsePayload_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(StartStopServicesResponsePayload* other);
  friend void swap(StartStopServicesResponsePayload& a, StartStopServicesResponsePayload& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline StartStopServicesResponsePayload* New() const PROTOBUF_FINAL { return New(NULL); }

  StartStopServicesResponsePayload* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(StartStopServicesResponsePayload* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, .fnv.soa.framework.protobuf.StartStopServiceResultProto.ActionStatus> metadata = 2;
  int metadata_size() const;
  void clear_metadata();
  static const int kMetadataFieldNumber = 2;
  const ::google::protobuf::Map< ::std::string, ::fnv::soa::framework::protobuf::StartStopServiceResultProto_ActionStatus >&
      metadata() const;
  ::google::protobuf::Map< ::std::string, ::fnv::soa::framework::protobuf::StartStopServiceResultProto_ActionStatus >*
      mutable_metadata();

  // optional .fnv.soa.framework.protobuf.SmTransactionStatus.Status transactionStatus = 1 [default = OK];
  bool has_transactionstatus() const;
  void clear_transactionstatus();
  static const int kTransactionStatusFieldNumber = 1;
  ::fnv::soa::framework::protobuf::SmTransactionStatus_Status transactionstatus() const;
  void set_transactionstatus(::fnv::soa::framework::protobuf::SmTransactionStatus_Status value);

  // @@protoc_insertion_point(class_scope:fnv.soa.framework.protobuf.StartStopServicesResponsePayload)
 private:
  void set_has_transactionstatus();
  void clear_has_transactionstatus();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::MapField<
      StartStopServicesResponsePayload_MetadataEntry_DoNotUse,
      ::std::string, ::fnv::soa::framework::protobuf::StartStopServiceResultProto_ActionStatus,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_ENUM,
      0 > metadata_;
  int transactionstatus_;
  friend struct ::protobuf_StartStopServicesResponsePayload_2eproto::TableStruct;
  friend void ::protobuf_StartStopServicesResponsePayload_2eproto::InitDefaultsStartStopServicesResponsePayloadImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// StartStopServicesResponsePayload

// optional .fnv.soa.framework.protobuf.SmTransactionStatus.Status transactionStatus = 1 [default = OK];
inline bool StartStopServicesResponsePayload::has_transactionstatus() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void StartStopServicesResponsePayload::set_has_transactionstatus() {
  _has_bits_[0] |= 0x00000001u;
}
inline void StartStopServicesResponsePayload::clear_has_transactionstatus() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void StartStopServicesResponsePayload::clear_transactionstatus() {
  transactionstatus_ = 1;
  clear_has_transactionstatus();
}
inline ::fnv::soa::framework::protobuf::SmTransactionStatus_Status StartStopServicesResponsePayload::transactionstatus() const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.protobuf.StartStopServicesResponsePayload.transactionStatus)
  return static_cast< ::fnv::soa::framework::protobuf::SmTransactionStatus_Status >(transactionstatus_);
}
inline void StartStopServicesResponsePayload::set_transactionstatus(::fnv::soa::framework::protobuf::SmTransactionStatus_Status value) {
  assert(::fnv::soa::framework::protobuf::SmTransactionStatus_Status_IsValid(value));
  set_has_transactionstatus();
  transactionstatus_ = value;
  // @@protoc_insertion_point(field_set:fnv.soa.framework.protobuf.StartStopServicesResponsePayload.transactionStatus)
}

// map<string, .fnv.soa.framework.protobuf.StartStopServiceResultProto.ActionStatus> metadata = 2;
inline int StartStopServicesResponsePayload::metadata_size() const {
  return metadata_.size();
}
inline void StartStopServicesResponsePayload::clear_metadata() {
  metadata_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::fnv::soa::framework::protobuf::StartStopServiceResultProto_ActionStatus >&
StartStopServicesResponsePayload::metadata() const {
  // @@protoc_insertion_point(field_map:fnv.soa.framework.protobuf.StartStopServicesResponsePayload.metadata)
  return metadata_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::fnv::soa::framework::protobuf::StartStopServiceResultProto_ActionStatus >*
StartStopServicesResponsePayload::mutable_metadata() {
  // @@protoc_insertion_point(field_mutable_map:fnv.soa.framework.protobuf.StartStopServicesResponsePayload.metadata)
  return metadata_.MutableMap();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace framework
}  // namespace soa
}  // namespace fnv

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_StartStopServicesResponsePayload_2eproto__INCLUDED
