// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TransactionStatusPayload.proto

#ifndef PROTOBUF_TransactionStatusPayload_2eproto__INCLUDED
#define PROTOBUF_TransactionStatusPayload_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "sm_transaction_status_public.pb.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

namespace protobuf_TransactionStatusPayload_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsTransactionStatusPayloadImpl();
void InitDefaultsTransactionStatusPayload();
inline void InitDefaults() {
  InitDefaultsTransactionStatusPayload();
}
}  // namespace protobuf_TransactionStatusPayload_2eproto
namespace fnv {
namespace soa {
namespace framework {
namespace protobuf {
class TransactionStatusPayload;
class TransactionStatusPayloadDefaultTypeInternal;
extern TransactionStatusPayloadDefaultTypeInternal _TransactionStatusPayload_default_instance_;
}  // namespace protobuf
}  // namespace framework
}  // namespace soa
}  // namespace fnv
namespace fnv {
namespace soa {
namespace framework {
namespace protobuf {

// ===================================================================

class TransactionStatusPayload : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fnv.soa.framework.protobuf.TransactionStatusPayload) */ {
 public:
  TransactionStatusPayload();
  virtual ~TransactionStatusPayload();

  TransactionStatusPayload(const TransactionStatusPayload& from);

  inline TransactionStatusPayload& operator=(const TransactionStatusPayload& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TransactionStatusPayload(TransactionStatusPayload&& from) noexcept
    : TransactionStatusPayload() {
    *this = ::std::move(from);
  }

  inline TransactionStatusPayload& operator=(TransactionStatusPayload&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TransactionStatusPayload& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TransactionStatusPayload* internal_default_instance() {
    return reinterpret_cast<const TransactionStatusPayload*>(
               &_TransactionStatusPayload_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(TransactionStatusPayload* other);
  friend void swap(TransactionStatusPayload& a, TransactionStatusPayload& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TransactionStatusPayload* New() const PROTOBUF_FINAL { return New(NULL); }

  TransactionStatusPayload* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TransactionStatusPayload* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .fnv.soa.framework.protobuf.SmTransactionStatus.Status transactionStatus = 1 [default = OK];
  bool has_transactionstatus() const;
  void clear_transactionstatus();
  static const int kTransactionStatusFieldNumber = 1;
  ::fnv::soa::framework::protobuf::SmTransactionStatus_Status transactionstatus() const;
  void set_transactionstatus(::fnv::soa::framework::protobuf::SmTransactionStatus_Status value);

  // @@protoc_insertion_point(class_scope:fnv.soa.framework.protobuf.TransactionStatusPayload)
 private:
  void set_has_transactionstatus();
  void clear_has_transactionstatus();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  int transactionstatus_;
  friend struct ::protobuf_TransactionStatusPayload_2eproto::TableStruct;
  friend void ::protobuf_TransactionStatusPayload_2eproto::InitDefaultsTransactionStatusPayloadImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TransactionStatusPayload

// optional .fnv.soa.framework.protobuf.SmTransactionStatus.Status transactionStatus = 1 [default = OK];
inline bool TransactionStatusPayload::has_transactionstatus() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TransactionStatusPayload::set_has_transactionstatus() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TransactionStatusPayload::clear_has_transactionstatus() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TransactionStatusPayload::clear_transactionstatus() {
  transactionstatus_ = 1;
  clear_has_transactionstatus();
}
inline ::fnv::soa::framework::protobuf::SmTransactionStatus_Status TransactionStatusPayload::transactionstatus() const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.protobuf.TransactionStatusPayload.transactionStatus)
  return static_cast< ::fnv::soa::framework::protobuf::SmTransactionStatus_Status >(transactionstatus_);
}
inline void TransactionStatusPayload::set_transactionstatus(::fnv::soa::framework::protobuf::SmTransactionStatus_Status value) {
  assert(::fnv::soa::framework::protobuf::SmTransactionStatus_Status_IsValid(value));
  set_has_transactionstatus();
  transactionstatus_ = value;
  // @@protoc_insertion_point(field_set:fnv.soa.framework.protobuf.TransactionStatusPayload.transactionStatus)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace framework
}  // namespace soa
}  // namespace fnv

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_TransactionStatusPayload_2eproto__INCLUDED
