/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: UnregisterServiceResponsePayload.proto */

#ifndef PROTOBUF_C_UnregisterServiceResponsePayload_2eproto__INCLUDED
#define PROTOBUF_C_UnregisterServiceResponsePayload_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "sm_transaction_status_public.pb-c.h"

typedef struct _Fnv__Soa__Framework__Protobuf__UnregisterServiceResultProto Fnv__Soa__Framework__Protobuf__UnregisterServiceResultProto;
typedef struct _Fnv__Soa__Framework__Protobuf__UnregisterServiceResponsePayloadProto Fnv__Soa__Framework__Protobuf__UnregisterServiceResponsePayloadProto;
typedef struct _Fnv__Soa__Framework__Protobuf__UnregisterServiceResponsePayloadProto__MetadataEntry Fnv__Soa__Framework__Protobuf__UnregisterServiceResponsePayloadProto__MetadataEntry;


/* --- enums --- */

typedef enum _Fnv__Soa__Framework__Protobuf__UnregisterServiceResultProto__ActionStatus {
  FNV__SOA__FRAMEWORK__PROTOBUF__UNREGISTER_SERVICE_RESULT_PROTO__ACTION_STATUS__OK = 0,
  FNV__SOA__FRAMEWORK__PROTOBUF__UNREGISTER_SERVICE_RESULT_PROTO__ACTION_STATUS__ERROR_CLIENT_NOT_REGISTERED = 1,
  FNV__SOA__FRAMEWORK__PROTOBUF__UNREGISTER_SERVICE_RESULT_PROTO__ACTION_STATUS__ERROR_GENERAL_ERROR = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(FNV__SOA__FRAMEWORK__PROTOBUF__UNREGISTER_SERVICE_RESULT_PROTO__ACTION_STATUS)
} Fnv__Soa__Framework__Protobuf__UnregisterServiceResultProto__ActionStatus;

/* --- messages --- */

struct  _Fnv__Soa__Framework__Protobuf__UnregisterServiceResultProto
{
  ProtobufCMessage base;
};
#define FNV__SOA__FRAMEWORK__PROTOBUF__UNREGISTER_SERVICE_RESULT_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fnv__soa__framework__protobuf__unregister_service_result_proto__descriptor) \
     }


struct  _Fnv__Soa__Framework__Protobuf__UnregisterServiceResponsePayloadProto__MetadataEntry
{
  ProtobufCMessage base;
  char *key;
  protobuf_c_boolean has_value;
  Fnv__Soa__Framework__Protobuf__UnregisterServiceResultProto__ActionStatus value;
};
#define FNV__SOA__FRAMEWORK__PROTOBUF__UNREGISTER_SERVICE_RESPONSE_PAYLOAD_PROTO__METADATA_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fnv__soa__framework__protobuf__unregister_service_response_payload_proto__metadata_entry__descriptor) \
    , NULL, 0, FNV__SOA__FRAMEWORK__PROTOBUF__UNREGISTER_SERVICE_RESULT_PROTO__ACTION_STATUS__OK }


/*
 **
 * @fnv_message_proto
 * @fnv_deprecated
 */
struct  _Fnv__Soa__Framework__Protobuf__UnregisterServiceResponsePayloadProto
{
  ProtobufCMessage base;
  protobuf_c_boolean has_transactionstatus;
  Fnv__Soa__Framework__Protobuf__SmTransactionStatus__Status transactionstatus;
  size_t n_metadata;
  Fnv__Soa__Framework__Protobuf__UnregisterServiceResponsePayloadProto__MetadataEntry **metadata;
};
#define FNV__SOA__FRAMEWORK__PROTOBUF__UNREGISTER_SERVICE_RESPONSE_PAYLOAD_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fnv__soa__framework__protobuf__unregister_service_response_payload_proto__descriptor) \
    , 0, FNV__SOA__FRAMEWORK__PROTOBUF__SM_TRANSACTION_STATUS__STATUS__OK, 0,NULL }


/* Fnv__Soa__Framework__Protobuf__UnregisterServiceResultProto methods */
void   fnv__soa__framework__protobuf__unregister_service_result_proto__init
                     (Fnv__Soa__Framework__Protobuf__UnregisterServiceResultProto         *message);
size_t fnv__soa__framework__protobuf__unregister_service_result_proto__get_packed_size
                     (const Fnv__Soa__Framework__Protobuf__UnregisterServiceResultProto   *message);
size_t fnv__soa__framework__protobuf__unregister_service_result_proto__pack
                     (const Fnv__Soa__Framework__Protobuf__UnregisterServiceResultProto   *message,
                      uint8_t             *out);
size_t fnv__soa__framework__protobuf__unregister_service_result_proto__pack_to_buffer
                     (const Fnv__Soa__Framework__Protobuf__UnregisterServiceResultProto   *message,
                      ProtobufCBuffer     *buffer);
Fnv__Soa__Framework__Protobuf__UnregisterServiceResultProto *
       fnv__soa__framework__protobuf__unregister_service_result_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fnv__soa__framework__protobuf__unregister_service_result_proto__free_unpacked
                     (Fnv__Soa__Framework__Protobuf__UnregisterServiceResultProto *message,
                      ProtobufCAllocator *allocator);
/* Fnv__Soa__Framework__Protobuf__UnregisterServiceResponsePayloadProto__MetadataEntry methods */
void   fnv__soa__framework__protobuf__unregister_service_response_payload_proto__metadata_entry__init
                     (Fnv__Soa__Framework__Protobuf__UnregisterServiceResponsePayloadProto__MetadataEntry         *message);
/* Fnv__Soa__Framework__Protobuf__UnregisterServiceResponsePayloadProto methods */
void   fnv__soa__framework__protobuf__unregister_service_response_payload_proto__init
                     (Fnv__Soa__Framework__Protobuf__UnregisterServiceResponsePayloadProto         *message);
size_t fnv__soa__framework__protobuf__unregister_service_response_payload_proto__get_packed_size
                     (const Fnv__Soa__Framework__Protobuf__UnregisterServiceResponsePayloadProto   *message);
size_t fnv__soa__framework__protobuf__unregister_service_response_payload_proto__pack
                     (const Fnv__Soa__Framework__Protobuf__UnregisterServiceResponsePayloadProto   *message,
                      uint8_t             *out);
size_t fnv__soa__framework__protobuf__unregister_service_response_payload_proto__pack_to_buffer
                     (const Fnv__Soa__Framework__Protobuf__UnregisterServiceResponsePayloadProto   *message,
                      ProtobufCBuffer     *buffer);
Fnv__Soa__Framework__Protobuf__UnregisterServiceResponsePayloadProto *
       fnv__soa__framework__protobuf__unregister_service_response_payload_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fnv__soa__framework__protobuf__unregister_service_response_payload_proto__free_unpacked
                     (Fnv__Soa__Framework__Protobuf__UnregisterServiceResponsePayloadProto *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Fnv__Soa__Framework__Protobuf__UnregisterServiceResultProto_Closure)
                 (const Fnv__Soa__Framework__Protobuf__UnregisterServiceResultProto *message,
                  void *closure_data);
typedef void (*Fnv__Soa__Framework__Protobuf__UnregisterServiceResponsePayloadProto__MetadataEntry_Closure)
                 (const Fnv__Soa__Framework__Protobuf__UnregisterServiceResponsePayloadProto__MetadataEntry *message,
                  void *closure_data);
typedef void (*Fnv__Soa__Framework__Protobuf__UnregisterServiceResponsePayloadProto_Closure)
                 (const Fnv__Soa__Framework__Protobuf__UnregisterServiceResponsePayloadProto *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor fnv__soa__framework__protobuf__unregister_service_result_proto__descriptor;
extern const ProtobufCEnumDescriptor    fnv__soa__framework__protobuf__unregister_service_result_proto__action_status__descriptor;
extern const ProtobufCMessageDescriptor fnv__soa__framework__protobuf__unregister_service_response_payload_proto__descriptor;
extern const ProtobufCMessageDescriptor fnv__soa__framework__protobuf__unregister_service_response_payload_proto__metadata_entry__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_UnregisterServiceResponsePayload_2eproto__INCLUDED */
