/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: UnregisterServiceRequestPayload.proto */

#ifndef PROTOBUF_C_UnregisterServiceRequestPayload_2eproto__INCLUDED
#define PROTOBUF_C_UnregisterServiceRequestPayload_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Fnv__Soa__Framework__Protobuf__UnregisterServiceRequestPayloadProto Fnv__Soa__Framework__Protobuf__UnregisterServiceRequestPayloadProto;


/* --- enums --- */


/* --- messages --- */

/*
 **
 * @fnv_message_proto
 * @fnv_deprecated
 */
struct  _Fnv__Soa__Framework__Protobuf__UnregisterServiceRequestPayloadProto
{
  ProtobufCMessage base;
  size_t n_metadata;
  char **metadata;
};
#define FNV__SOA__FRAMEWORK__PROTOBUF__UNREGISTER_SERVICE_REQUEST_PAYLOAD_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fnv__soa__framework__protobuf__unregister_service_request_payload_proto__descriptor) \
    , 0,NULL }


/* Fnv__Soa__Framework__Protobuf__UnregisterServiceRequestPayloadProto methods */
void   fnv__soa__framework__protobuf__unregister_service_request_payload_proto__init
                     (Fnv__Soa__Framework__Protobuf__UnregisterServiceRequestPayloadProto         *message);
size_t fnv__soa__framework__protobuf__unregister_service_request_payload_proto__get_packed_size
                     (const Fnv__Soa__Framework__Protobuf__UnregisterServiceRequestPayloadProto   *message);
size_t fnv__soa__framework__protobuf__unregister_service_request_payload_proto__pack
                     (const Fnv__Soa__Framework__Protobuf__UnregisterServiceRequestPayloadProto   *message,
                      uint8_t             *out);
size_t fnv__soa__framework__protobuf__unregister_service_request_payload_proto__pack_to_buffer
                     (const Fnv__Soa__Framework__Protobuf__UnregisterServiceRequestPayloadProto   *message,
                      ProtobufCBuffer     *buffer);
Fnv__Soa__Framework__Protobuf__UnregisterServiceRequestPayloadProto *
       fnv__soa__framework__protobuf__unregister_service_request_payload_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fnv__soa__framework__protobuf__unregister_service_request_payload_proto__free_unpacked
                     (Fnv__Soa__Framework__Protobuf__UnregisterServiceRequestPayloadProto *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Fnv__Soa__Framework__Protobuf__UnregisterServiceRequestPayloadProto_Closure)
                 (const Fnv__Soa__Framework__Protobuf__UnregisterServiceRequestPayloadProto *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor fnv__soa__framework__protobuf__unregister_service_request_payload_proto__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_UnregisterServiceRequestPayload_2eproto__INCLUDED */
