// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UpdateProvisionedServiceStatusPayload.proto

#ifndef PROTOBUF_UpdateProvisionedServiceStatusPayload_2eproto__INCLUDED
#define PROTOBUF_UpdateProvisionedServiceStatusPayload_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "ProvisionedServiceStatusMetadata.pb.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

namespace protobuf_UpdateProvisionedServiceStatusPayload_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsUpdateProvisionedServiceStatusPayloadImpl();
void InitDefaultsUpdateProvisionedServiceStatusPayload();
inline void InitDefaults() {
  InitDefaultsUpdateProvisionedServiceStatusPayload();
}
}  // namespace protobuf_UpdateProvisionedServiceStatusPayload_2eproto
namespace fnv {
namespace soa {
namespace framework {
namespace protobuf {
class UpdateProvisionedServiceStatusPayload;
class UpdateProvisionedServiceStatusPayloadDefaultTypeInternal;
extern UpdateProvisionedServiceStatusPayloadDefaultTypeInternal _UpdateProvisionedServiceStatusPayload_default_instance_;
}  // namespace protobuf
}  // namespace framework
}  // namespace soa
}  // namespace fnv
namespace fnv {
namespace soa {
namespace framework {
namespace protobuf {

// ===================================================================

class UpdateProvisionedServiceStatusPayload : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fnv.soa.framework.protobuf.UpdateProvisionedServiceStatusPayload) */ {
 public:
  UpdateProvisionedServiceStatusPayload();
  virtual ~UpdateProvisionedServiceStatusPayload();

  UpdateProvisionedServiceStatusPayload(const UpdateProvisionedServiceStatusPayload& from);

  inline UpdateProvisionedServiceStatusPayload& operator=(const UpdateProvisionedServiceStatusPayload& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  UpdateProvisionedServiceStatusPayload(UpdateProvisionedServiceStatusPayload&& from) noexcept
    : UpdateProvisionedServiceStatusPayload() {
    *this = ::std::move(from);
  }

  inline UpdateProvisionedServiceStatusPayload& operator=(UpdateProvisionedServiceStatusPayload&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UpdateProvisionedServiceStatusPayload& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UpdateProvisionedServiceStatusPayload* internal_default_instance() {
    return reinterpret_cast<const UpdateProvisionedServiceStatusPayload*>(
               &_UpdateProvisionedServiceStatusPayload_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(UpdateProvisionedServiceStatusPayload* other);
  friend void swap(UpdateProvisionedServiceStatusPayload& a, UpdateProvisionedServiceStatusPayload& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline UpdateProvisionedServiceStatusPayload* New() const PROTOBUF_FINAL { return New(NULL); }

  UpdateProvisionedServiceStatusPayload* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UpdateProvisionedServiceStatusPayload* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .fnv.soa.framework.protobuf.ProvisionedServiceStatusMetadata status = 1;
  int status_size() const;
  void clear_status();
  static const int kStatusFieldNumber = 1;
  const ::fnv::soa::framework::protobuf::ProvisionedServiceStatusMetadata& status(int index) const;
  ::fnv::soa::framework::protobuf::ProvisionedServiceStatusMetadata* mutable_status(int index);
  ::fnv::soa::framework::protobuf::ProvisionedServiceStatusMetadata* add_status();
  ::google::protobuf::RepeatedPtrField< ::fnv::soa::framework::protobuf::ProvisionedServiceStatusMetadata >*
      mutable_status();
  const ::google::protobuf::RepeatedPtrField< ::fnv::soa::framework::protobuf::ProvisionedServiceStatusMetadata >&
      status() const;

  // @@protoc_insertion_point(class_scope:fnv.soa.framework.protobuf.UpdateProvisionedServiceStatusPayload)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::fnv::soa::framework::protobuf::ProvisionedServiceStatusMetadata > status_;
  friend struct ::protobuf_UpdateProvisionedServiceStatusPayload_2eproto::TableStruct;
  friend void ::protobuf_UpdateProvisionedServiceStatusPayload_2eproto::InitDefaultsUpdateProvisionedServiceStatusPayloadImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// UpdateProvisionedServiceStatusPayload

// repeated .fnv.soa.framework.protobuf.ProvisionedServiceStatusMetadata status = 1;
inline int UpdateProvisionedServiceStatusPayload::status_size() const {
  return status_.size();
}
inline const ::fnv::soa::framework::protobuf::ProvisionedServiceStatusMetadata& UpdateProvisionedServiceStatusPayload::status(int index) const {
  // @@protoc_insertion_point(field_get:fnv.soa.framework.protobuf.UpdateProvisionedServiceStatusPayload.status)
  return status_.Get(index);
}
inline ::fnv::soa::framework::protobuf::ProvisionedServiceStatusMetadata* UpdateProvisionedServiceStatusPayload::mutable_status(int index) {
  // @@protoc_insertion_point(field_mutable:fnv.soa.framework.protobuf.UpdateProvisionedServiceStatusPayload.status)
  return status_.Mutable(index);
}
inline ::fnv::soa::framework::protobuf::ProvisionedServiceStatusMetadata* UpdateProvisionedServiceStatusPayload::add_status() {
  // @@protoc_insertion_point(field_add:fnv.soa.framework.protobuf.UpdateProvisionedServiceStatusPayload.status)
  return status_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::fnv::soa::framework::protobuf::ProvisionedServiceStatusMetadata >*
UpdateProvisionedServiceStatusPayload::mutable_status() {
  // @@protoc_insertion_point(field_mutable_list:fnv.soa.framework.protobuf.UpdateProvisionedServiceStatusPayload.status)
  return &status_;
}
inline const ::google::protobuf::RepeatedPtrField< ::fnv::soa::framework::protobuf::ProvisionedServiceStatusMetadata >&
UpdateProvisionedServiceStatusPayload::status() const {
  // @@protoc_insertion_point(field_list:fnv.soa.framework.protobuf.UpdateProvisionedServiceStatusPayload.status)
  return status_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace framework
}  // namespace soa
}  // namespace fnv

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_UpdateProvisionedServiceStatusPayload_2eproto__INCLUDED
