/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: UpdateProvisionedServiceStatusPayload.proto */

#ifndef PROTOBUF_C_UpdateProvisionedServiceStatusPayload_2eproto__INCLUDED
#define PROTOBUF_C_UpdateProvisionedServiceStatusPayload_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "ProvisionedServiceStatusMetadata.pb-c.h"

typedef struct _Fnv__Soa__Framework__Protobuf__UpdateProvisionedServiceStatusPayload Fnv__Soa__Framework__Protobuf__UpdateProvisionedServiceStatusPayload;


/* --- enums --- */


/* --- messages --- */

/*
 **
 * @fnv_proto
 * @fnv_deprecated
 */
struct  _Fnv__Soa__Framework__Protobuf__UpdateProvisionedServiceStatusPayload
{
  ProtobufCMessage base;
  size_t n_status;
  Fnv__Soa__Framework__Protobuf__ProvisionedServiceStatusMetadata **status;
};
#define FNV__SOA__FRAMEWORK__PROTOBUF__UPDATE_PROVISIONED_SERVICE_STATUS_PAYLOAD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fnv__soa__framework__protobuf__update_provisioned_service_status_payload__descriptor) \
    , 0,NULL }


/* Fnv__Soa__Framework__Protobuf__UpdateProvisionedServiceStatusPayload methods */
void   fnv__soa__framework__protobuf__update_provisioned_service_status_payload__init
                     (Fnv__Soa__Framework__Protobuf__UpdateProvisionedServiceStatusPayload         *message);
size_t fnv__soa__framework__protobuf__update_provisioned_service_status_payload__get_packed_size
                     (const Fnv__Soa__Framework__Protobuf__UpdateProvisionedServiceStatusPayload   *message);
size_t fnv__soa__framework__protobuf__update_provisioned_service_status_payload__pack
                     (const Fnv__Soa__Framework__Protobuf__UpdateProvisionedServiceStatusPayload   *message,
                      uint8_t             *out);
size_t fnv__soa__framework__protobuf__update_provisioned_service_status_payload__pack_to_buffer
                     (const Fnv__Soa__Framework__Protobuf__UpdateProvisionedServiceStatusPayload   *message,
                      ProtobufCBuffer     *buffer);
Fnv__Soa__Framework__Protobuf__UpdateProvisionedServiceStatusPayload *
       fnv__soa__framework__protobuf__update_provisioned_service_status_payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fnv__soa__framework__protobuf__update_provisioned_service_status_payload__free_unpacked
                     (Fnv__Soa__Framework__Protobuf__UpdateProvisionedServiceStatusPayload *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Fnv__Soa__Framework__Protobuf__UpdateProvisionedServiceStatusPayload_Closure)
                 (const Fnv__Soa__Framework__Protobuf__UpdateProvisionedServiceStatusPayload *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor fnv__soa__framework__protobuf__update_provisioned_service_status_payload__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_UpdateProvisionedServiceStatusPayload_2eproto__INCLUDED */
