###########################################################
# Makefile rules to build libftcpidl.so
###########################################################

include $(FORD_COMMON_BUILD)/config.mk

ARTIFACT=libftcpidl.so

SRCS = $(call findsrc, ., cc)

include $(FORD_COMMON_BUILD)/idl_library_common.mk
