###########################################################
# Makefile rules to build libfnvsyncappsidl.so
###########################################################
include $(FORD_COMMON_BUILD)/config.mk

ARTIFACT=libfnvsyncappsidl.so

PUBLISH_HEADER_DIR = sync_apps

include $(FORD_COMMON_BUILD)/idl_library_common.mk
