###########################################################
# Makefile rules to build libcmidl.so
###########################################################

include $(FORD_COMMON_BUILD)/config.mk

ARTIFACT=libcmidl.so

SRCS = $(call findsrc, ., cc)

include $(FORD_COMMON_BUILD)/idl_library_common.mk
