###########################################################
# Makefile rules to build libipptidl.so
###########################################################

include $(FORD_COMMON_BUILD)/config.mk

ARTIFACT=libipptidl.so

SRCS = $(call findsrc, ., cc)

include $(FORD_COMMON_BUILD)/idl_library_common.mk
